// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Onepassword
{
    public static class GetEnvironment
    {
        /// <summary>
        /// Use this data source to read environment variables from a [1Password Environment](https://developer.1password.com/docs/environments/). 1Password Environments allow you to organize and manage project secrets as environment variables. This data source is only supported when using **service account** or **desktop app** authentication; it is not available with 1Password Connect.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Onepassword = Pulumi.Onepassword;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     // Read environment variables from a 1Password Environment.
        ///     // Requires service account or desktop app authentication (not 1Password Connect).
        ///     var example = Onepassword.GetEnvironment.Invoke(new()
        ///     {
        ///         EnvironmentId = "your-environment-id",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["envVariables"] = example.Apply(getEnvironmentResult =&gt; getEnvironmentResult.Variables),
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Task<GetEnvironmentResult> InvokeAsync(GetEnvironmentArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetEnvironmentResult>("onepassword:index/getEnvironment:getEnvironment", args ?? new GetEnvironmentArgs(), options.WithDefaults());

        /// <summary>
        /// Use this data source to read environment variables from a [1Password Environment](https://developer.1password.com/docs/environments/). 1Password Environments allow you to organize and manage project secrets as environment variables. This data source is only supported when using **service account** or **desktop app** authentication; it is not available with 1Password Connect.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Onepassword = Pulumi.Onepassword;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     // Read environment variables from a 1Password Environment.
        ///     // Requires service account or desktop app authentication (not 1Password Connect).
        ///     var example = Onepassword.GetEnvironment.Invoke(new()
        ///     {
        ///         EnvironmentId = "your-environment-id",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["envVariables"] = example.Apply(getEnvironmentResult =&gt; getEnvironmentResult.Variables),
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetEnvironmentResult> Invoke(GetEnvironmentInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetEnvironmentResult>("onepassword:index/getEnvironment:getEnvironment", args ?? new GetEnvironmentInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Use this data source to read environment variables from a [1Password Environment](https://developer.1password.com/docs/environments/). 1Password Environments allow you to organize and manage project secrets as environment variables. This data source is only supported when using **service account** or **desktop app** authentication; it is not available with 1Password Connect.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Onepassword = Pulumi.Onepassword;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     // Read environment variables from a 1Password Environment.
        ///     // Requires service account or desktop app authentication (not 1Password Connect).
        ///     var example = Onepassword.GetEnvironment.Invoke(new()
        ///     {
        ///         EnvironmentId = "your-environment-id",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["envVariables"] = example.Apply(getEnvironmentResult =&gt; getEnvironmentResult.Variables),
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetEnvironmentResult> Invoke(GetEnvironmentInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetEnvironmentResult>("onepassword:index/getEnvironment:getEnvironment", args ?? new GetEnvironmentInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetEnvironmentArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The unique identifier of the 1Password Environment. You can find this in the 1Password desktop app under Developer &gt; View Environments &gt; Manage environment &gt; Copy environment ID.
        /// </summary>
        [Input("environmentId", required: true)]
        public string EnvironmentId { get; set; } = null!;

        [Input("metadatas")]
        private List<Inputs.GetEnvironmentMetadataArgs>? _metadatas;

        /// <summary>
        /// Metadata for each environment variable (name, value, and masked flag). Use this when you need the full structure; use `Variables` for a simple name-to-value map.
        /// </summary>
        public List<Inputs.GetEnvironmentMetadataArgs> Metadatas
        {
            get => _metadatas ?? (_metadatas = new List<Inputs.GetEnvironmentMetadataArgs>());
            set => _metadatas = value;
        }

        public GetEnvironmentArgs()
        {
        }
        public static new GetEnvironmentArgs Empty => new GetEnvironmentArgs();
    }

    public sealed class GetEnvironmentInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The unique identifier of the 1Password Environment. You can find this in the 1Password desktop app under Developer &gt; View Environments &gt; Manage environment &gt; Copy environment ID.
        /// </summary>
        [Input("environmentId", required: true)]
        public Input<string> EnvironmentId { get; set; } = null!;

        [Input("metadatas")]
        private InputList<Inputs.GetEnvironmentMetadataInputArgs>? _metadatas;

        /// <summary>
        /// Metadata for each environment variable (name, value, and masked flag). Use this when you need the full structure; use `Variables` for a simple name-to-value map.
        /// </summary>
        public InputList<Inputs.GetEnvironmentMetadataInputArgs> Metadatas
        {
            get => _metadatas ?? (_metadatas = new InputList<Inputs.GetEnvironmentMetadataInputArgs>());
            set => _metadatas = value;
        }

        public GetEnvironmentInvokeArgs()
        {
        }
        public static new GetEnvironmentInvokeArgs Empty => new GetEnvironmentInvokeArgs();
    }


    [OutputType]
    public sealed class GetEnvironmentResult
    {
        /// <summary>
        /// The unique identifier of the 1Password Environment. You can find this in the 1Password desktop app under Developer &gt; View Environments &gt; Manage environment &gt; Copy environment ID.
        /// </summary>
        public readonly string EnvironmentId;
        /// <summary>
        /// The Terraform resource identifier for this environment in the format `environments/&lt;environment_id&gt;`.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Metadata for each environment variable (name, value, and masked flag). Use this when you need the full structure; use `Variables` for a simple name-to-value map.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetEnvironmentMetadataResult> Metadatas;
        /// <summary>
        /// A map of environment variable names to their values. Use this for passing secrets into Terraform resources or for use in `Environment` blocks.
        /// </summary>
        public readonly ImmutableDictionary<string, string> Variables;

        [OutputConstructor]
        private GetEnvironmentResult(
            string environmentId,

            string id,

            ImmutableArray<Outputs.GetEnvironmentMetadataResult> metadatas,

            ImmutableDictionary<string, string> variables)
        {
            EnvironmentId = environmentId;
            Id = id;
            Metadatas = metadatas;
            Variables = variables;
        }
    }
}
