// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/1Password/pulumi-onepassword/sdk/go/onepassword/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// A valid account name or ID to use desktop app authentication. Can also be sourced from `OP_ACCOUNT` environment variable.
func GetAccount(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "onepassword:account")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault(nil, nil, "OP_ACCOUNT"); d != nil {
		value = d.(string)
	}
	return value
}

// A valid token for your 1Password Connect server. Can also be sourced from `OP_CONNECT_TOKEN` environment variable. Provider will use 1Password Connect server if set.
func GetConnectToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "onepassword:connectToken")
}

// The HTTP(S) URL where your 1Password Connect server can be found. Can also be sourced `OP_CONNECT_HOST` environment variable. Provider will use 1Password Connect server if set.
func GetConnectUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "onepassword:connectUrl")
}

// A valid 1Password service account token. Can also be sourced from `OP_SERVICE_ACCOUNT_TOKEN` environment variable.
func GetServiceAccountToken(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "onepassword:serviceAccountToken")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault(nil, nil, "OP_SERVICE_ACCOUNT_TOKEN"); d != nil {
		value = d.(string)
	}
	return value
}

// A valid token for your 1Password Connect server. Can also be sourced from `OP_CONNECT_TOKEN` environment variable. Provider will use 1Password Connect server if set. Deprecated: Use `connectToken` instead.
//
// Deprecated: The "token" field is deprecated and will be removed in a future version. Use "connectToken" instead.
func GetToken(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "onepassword:token")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault(nil, nil, "OP_CONNECT_TOKEN"); d != nil {
		value = d.(string)
	}
	return value
}

// The HTTP(S) URL where your 1Password Connect server can be found. Can also be sourced `OP_CONNECT_HOST` environment variable. Provider will use 1Password Connect server if set. Deprecated: Use `connectUrl` instead.
//
// Deprecated: The "url" field is deprecated and will be removed in a future version. Use "connectUrl" instead.
func GetUrl(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "onepassword:url")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault(nil, nil, "OP_CONNECT_HOST"); d != nil {
		value = d.(string)
	}
	return value
}
