// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("onepassword");

/**
 * A valid account name or ID to use desktop app authentication. Can also be sourced from `OP_ACCOUNT` environment variable.
 */
export declare const account: string | undefined;
Object.defineProperty(exports, "account", {
    get() {
        return __config.get("account") ?? utilities.getEnv("OP_ACCOUNT");
    },
    enumerable: true,
});

/**
 * A valid token for your 1Password Connect server. Can also be sourced from `OP_CONNECT_TOKEN` environment variable. Provider will use 1Password Connect server if set.
 */
export declare const connectToken: string | undefined;
Object.defineProperty(exports, "connectToken", {
    get() {
        return __config.get("connectToken");
    },
    enumerable: true,
});

/**
 * The HTTP(S) URL where your 1Password Connect server can be found. Can also be sourced `OP_CONNECT_HOST` environment variable. Provider will use 1Password Connect server if set.
 */
export declare const connectUrl: string | undefined;
Object.defineProperty(exports, "connectUrl", {
    get() {
        return __config.get("connectUrl");
    },
    enumerable: true,
});

/**
 * A valid 1Password service account token. Can also be sourced from `OP_SERVICE_ACCOUNT_TOKEN` environment variable.
 */
export declare const serviceAccountToken: string | undefined;
Object.defineProperty(exports, "serviceAccountToken", {
    get() {
        return __config.get("serviceAccountToken") ?? utilities.getEnv("OP_SERVICE_ACCOUNT_TOKEN");
    },
    enumerable: true,
});

/**
 * A valid token for your 1Password Connect server. Can also be sourced from `OP_CONNECT_TOKEN` environment variable. Provider will use 1Password Connect server if set. Deprecated: Use `connectToken` instead.
 */
export declare const token: string | undefined;
Object.defineProperty(exports, "token", {
    get() {
        return __config.get("token") ?? utilities.getEnv("OP_CONNECT_TOKEN");
    },
    enumerable: true,
});

/**
 * The HTTP(S) URL where your 1Password Connect server can be found. Can also be sourced `OP_CONNECT_HOST` environment variable. Provider will use 1Password Connect server if set. Deprecated: Use `connectUrl` instead.
 */
export declare const url: string | undefined;
Object.defineProperty(exports, "url", {
    get() {
        return __config.get("url") ?? utilities.getEnv("OP_CONNECT_HOST");
    },
    enumerable: true,
});

