// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Onepassword.Outputs
{

    [OutputType]
    public sealed class GetEnvironmentMetadataResult
    {
        /// <summary>
        /// Whether the value is hidden by default in the 1Password app.
        /// </summary>
        public readonly bool Masked;
        /// <summary>
        /// The environment variable name.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The environment variable value.
        /// </summary>
        public readonly string Value;

        [OutputConstructor]
        private GetEnvironmentMetadataResult(
            bool masked,

            string name,

            string value)
        {
            Masked = masked;
            Name = name;
            Value = value;
        }
    }
}
