// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Onepassword.Outputs
{

    [OutputType]
    public sealed class GetItemSectionMapResult
    {
        /// <summary>
        /// A map of custom fields in the section, keyed by field label.
        /// </summary>
        public readonly ImmutableDictionary<string, Outputs.GetItemSectionMapFieldMapResult> FieldMap;
        /// <summary>
        /// A map of files attached to the section, keyed by file label.
        /// </summary>
        public readonly ImmutableDictionary<string, Outputs.GetItemSectionMapFileMapResult> FileMap;
        /// <summary>
        /// A unique identifier for the section.
        /// </summary>
        public readonly string Id;

        [OutputConstructor]
        private GetItemSectionMapResult(
            ImmutableDictionary<string, Outputs.GetItemSectionMapFieldMapResult> fieldMap,

            ImmutableDictionary<string, Outputs.GetItemSectionMapFileMapResult> fileMap,

            string id)
        {
            FieldMap = fieldMap;
            FileMap = fileMap;
            Id = id;
        }
    }
}
