// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Onepassword.Outputs
{

    [OutputType]
    public sealed class GetItemSectionMapFieldMapResult
    {
        /// <summary>
        /// A unique identifier for the field.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The type of value stored in the field. One of ["STRING" "CONCEALED" "EMAIL" "URL" "OTP" "DATE" "MONTH_YEAR" "MENU"]
        /// </summary>
        public readonly string Type;
        /// <summary>
        /// The value of the field.
        /// </summary>
        public readonly string Value;

        [OutputConstructor]
        private GetItemSectionMapFieldMapResult(
            string id,

            string type,

            string value)
        {
            Id = id;
            Type = type;
            Value = value;
        }
    }
}
