// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Onepassword.Outputs
{

    [OutputType]
    public sealed class ItemSectionMapFieldMap
    {
        /// <summary>
        /// A unique identifier for the field.
        /// </summary>
        public readonly string? Id;
        /// <summary>
        /// The recipe used to generate a new value for a password.
        /// </summary>
        public readonly Outputs.ItemSectionMapFieldMapPasswordRecipe? PasswordRecipe;
        /// <summary>
        /// The type of value stored in the field. One of ["STRING" "CONCEALED" "EMAIL" "URL" "OTP" "DATE" "MONTH_YEAR" "MENU"]
        /// </summary>
        public readonly string? Type;
        /// <summary>
        /// The value of the field.
        /// </summary>
        public readonly string? Value;

        [OutputConstructor]
        private ItemSectionMapFieldMap(
            string? id,

            Outputs.ItemSectionMapFieldMapPasswordRecipe? passwordRecipe,

            string? type,

            string? value)
        {
            Id = id;
            PasswordRecipe = passwordRecipe;
            Type = type;
            Value = value;
        }
    }
}
