// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Onepassword.Outputs
{

    [OutputType]
    public sealed class ItemSectionMap
    {
        /// <summary>
        /// A map of custom fields in the section, keyed by field label.
        /// </summary>
        public readonly ImmutableDictionary<string, Outputs.ItemSectionMapFieldMap>? FieldMap;
        /// <summary>
        /// A unique identifier for the section.
        /// </summary>
        public readonly string? Id;

        [OutputConstructor]
        private ItemSectionMap(
            ImmutableDictionary<string, Outputs.ItemSectionMapFieldMap>? fieldMap,

            string? id)
        {
            FieldMap = fieldMap;
            Id = id;
        }
    }
}
