# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'ItemPasswordRecipeArgs',
    'ItemPasswordRecipeArgsDict',
    'ItemSectionArgs',
    'ItemSectionArgsDict',
    'ItemSectionFieldArgs',
    'ItemSectionFieldArgsDict',
    'ItemSectionFieldPasswordRecipeArgs',
    'ItemSectionFieldPasswordRecipeArgsDict',
    'ItemSectionMapArgs',
    'ItemSectionMapArgsDict',
    'ItemSectionMapFieldMapArgs',
    'ItemSectionMapFieldMapArgsDict',
    'ItemSectionMapFieldMapPasswordRecipeArgs',
    'ItemSectionMapFieldMapPasswordRecipeArgsDict',
    'GetEnvironmentMetadataArgs',
    'GetEnvironmentMetadataArgsDict',
    'GetItemFileArgs',
    'GetItemFileArgsDict',
    'GetItemSectionArgs',
    'GetItemSectionArgsDict',
    'GetItemSectionFieldArgs',
    'GetItemSectionFieldArgsDict',
    'GetItemSectionFileArgs',
    'GetItemSectionFileArgsDict',
    'GetItemSectionMapArgs',
    'GetItemSectionMapArgsDict',
    'GetItemSectionMapFieldMapArgs',
    'GetItemSectionMapFieldMapArgsDict',
    'GetItemSectionMapFileMapArgs',
    'GetItemSectionMapFileMapArgsDict',
]

class ItemPasswordRecipeArgsDict(TypedDict):
    digits: NotRequired[pulumi.Input[_builtins.bool]]
    """
    Use digits [0-9] when generating the password.
    """
    length: NotRequired[pulumi.Input[_builtins.int]]
    """
    The length of the password to be generated.
    """
    symbols: NotRequired[pulumi.Input[_builtins.bool]]
    """
    Use symbols [!@.-_*] when generating the password.
    """

@pulumi.input_type
class ItemPasswordRecipeArgs:
    def __init__(__self__, *,
                 digits: Optional[pulumi.Input[_builtins.bool]] = None,
                 length: Optional[pulumi.Input[_builtins.int]] = None,
                 symbols: Optional[pulumi.Input[_builtins.bool]] = None):
        """
        :param pulumi.Input[_builtins.bool] digits: Use digits [0-9] when generating the password.
        :param pulumi.Input[_builtins.int] length: The length of the password to be generated.
        :param pulumi.Input[_builtins.bool] symbols: Use symbols [!@.-_*] when generating the password.
        """
        if digits is not None:
            pulumi.set(__self__, "digits", digits)
        if length is not None:
            pulumi.set(__self__, "length", length)
        if symbols is not None:
            pulumi.set(__self__, "symbols", symbols)

    @_builtins.property
    @pulumi.getter
    def digits(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Use digits [0-9] when generating the password.
        """
        return pulumi.get(self, "digits")

    @digits.setter
    def digits(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "digits", value)

    @_builtins.property
    @pulumi.getter
    def length(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        The length of the password to be generated.
        """
        return pulumi.get(self, "length")

    @length.setter
    def length(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "length", value)

    @_builtins.property
    @pulumi.getter
    def symbols(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Use symbols [!@.-_*] when generating the password.
        """
        return pulumi.get(self, "symbols")

    @symbols.setter
    def symbols(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "symbols", value)


class ItemSectionArgsDict(TypedDict):
    label: pulumi.Input[_builtins.str]
    """
    The label for the section.
    """
    fields: NotRequired[pulumi.Input[Sequence[pulumi.Input['ItemSectionFieldArgsDict']]]]
    """
    A list of custom fields in the section
    """
    id: NotRequired[pulumi.Input[_builtins.str]]
    """
    A unique identifier for the section.
    """

@pulumi.input_type
class ItemSectionArgs:
    def __init__(__self__, *,
                 label: pulumi.Input[_builtins.str],
                 fields: Optional[pulumi.Input[Sequence[pulumi.Input['ItemSectionFieldArgs']]]] = None,
                 id: Optional[pulumi.Input[_builtins.str]] = None):
        """
        :param pulumi.Input[_builtins.str] label: The label for the section.
        :param pulumi.Input[Sequence[pulumi.Input['ItemSectionFieldArgs']]] fields: A list of custom fields in the section
        :param pulumi.Input[_builtins.str] id: A unique identifier for the section.
        """
        pulumi.set(__self__, "label", label)
        if fields is not None:
            pulumi.set(__self__, "fields", fields)
        if id is not None:
            pulumi.set(__self__, "id", id)

    @_builtins.property
    @pulumi.getter
    def label(self) -> pulumi.Input[_builtins.str]:
        """
        The label for the section.
        """
        return pulumi.get(self, "label")

    @label.setter
    def label(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "label", value)

    @_builtins.property
    @pulumi.getter
    def fields(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['ItemSectionFieldArgs']]]]:
        """
        A list of custom fields in the section
        """
        return pulumi.get(self, "fields")

    @fields.setter
    def fields(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['ItemSectionFieldArgs']]]]):
        pulumi.set(self, "fields", value)

    @_builtins.property
    @pulumi.getter
    def id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        A unique identifier for the section.
        """
        return pulumi.get(self, "id")

    @id.setter
    def id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "id", value)


class ItemSectionFieldArgsDict(TypedDict):
    label: pulumi.Input[_builtins.str]
    """
    The label for the field.
    """
    id: NotRequired[pulumi.Input[_builtins.str]]
    """
    A unique identifier for the field.
    """
    password_recipe: NotRequired[pulumi.Input['ItemSectionFieldPasswordRecipeArgsDict']]
    """
    The recipe used to generate a new value for a password.
    """
    type: NotRequired[pulumi.Input[_builtins.str]]
    """
    The type of value stored in the field. One of ["STRING" "CONCEALED" "EMAIL" "URL" "OTP" "DATE" "MONTH_YEAR" "MENU"]
    """
    value: NotRequired[pulumi.Input[_builtins.str]]
    """
    The value of the field.
    """

@pulumi.input_type
class ItemSectionFieldArgs:
    def __init__(__self__, *,
                 label: pulumi.Input[_builtins.str],
                 id: Optional[pulumi.Input[_builtins.str]] = None,
                 password_recipe: Optional[pulumi.Input['ItemSectionFieldPasswordRecipeArgs']] = None,
                 type: Optional[pulumi.Input[_builtins.str]] = None,
                 value: Optional[pulumi.Input[_builtins.str]] = None):
        """
        :param pulumi.Input[_builtins.str] label: The label for the field.
        :param pulumi.Input[_builtins.str] id: A unique identifier for the field.
        :param pulumi.Input['ItemSectionFieldPasswordRecipeArgs'] password_recipe: The recipe used to generate a new value for a password.
        :param pulumi.Input[_builtins.str] type: The type of value stored in the field. One of ["STRING" "CONCEALED" "EMAIL" "URL" "OTP" "DATE" "MONTH_YEAR" "MENU"]
        :param pulumi.Input[_builtins.str] value: The value of the field.
        """
        pulumi.set(__self__, "label", label)
        if id is not None:
            pulumi.set(__self__, "id", id)
        if password_recipe is not None:
            pulumi.set(__self__, "password_recipe", password_recipe)
        if type is not None:
            pulumi.set(__self__, "type", type)
        if value is not None:
            pulumi.set(__self__, "value", value)

    @_builtins.property
    @pulumi.getter
    def label(self) -> pulumi.Input[_builtins.str]:
        """
        The label for the field.
        """
        return pulumi.get(self, "label")

    @label.setter
    def label(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "label", value)

    @_builtins.property
    @pulumi.getter
    def id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        A unique identifier for the field.
        """
        return pulumi.get(self, "id")

    @id.setter
    def id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "id", value)

    @_builtins.property
    @pulumi.getter(name="passwordRecipe")
    def password_recipe(self) -> Optional[pulumi.Input['ItemSectionFieldPasswordRecipeArgs']]:
        """
        The recipe used to generate a new value for a password.
        """
        return pulumi.get(self, "password_recipe")

    @password_recipe.setter
    def password_recipe(self, value: Optional[pulumi.Input['ItemSectionFieldPasswordRecipeArgs']]):
        pulumi.set(self, "password_recipe", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The type of value stored in the field. One of ["STRING" "CONCEALED" "EMAIL" "URL" "OTP" "DATE" "MONTH_YEAR" "MENU"]
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "type", value)

    @_builtins.property
    @pulumi.getter
    def value(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The value of the field.
        """
        return pulumi.get(self, "value")

    @value.setter
    def value(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "value", value)


class ItemSectionFieldPasswordRecipeArgsDict(TypedDict):
    digits: NotRequired[pulumi.Input[_builtins.bool]]
    """
    Use digits [0-9] when generating the password.
    """
    length: NotRequired[pulumi.Input[_builtins.int]]
    """
    The length of the password to be generated.
    """
    symbols: NotRequired[pulumi.Input[_builtins.bool]]
    """
    Use symbols [!@.-_*] when generating the password.
    """

@pulumi.input_type
class ItemSectionFieldPasswordRecipeArgs:
    def __init__(__self__, *,
                 digits: Optional[pulumi.Input[_builtins.bool]] = None,
                 length: Optional[pulumi.Input[_builtins.int]] = None,
                 symbols: Optional[pulumi.Input[_builtins.bool]] = None):
        """
        :param pulumi.Input[_builtins.bool] digits: Use digits [0-9] when generating the password.
        :param pulumi.Input[_builtins.int] length: The length of the password to be generated.
        :param pulumi.Input[_builtins.bool] symbols: Use symbols [!@.-_*] when generating the password.
        """
        if digits is not None:
            pulumi.set(__self__, "digits", digits)
        if length is not None:
            pulumi.set(__self__, "length", length)
        if symbols is not None:
            pulumi.set(__self__, "symbols", symbols)

    @_builtins.property
    @pulumi.getter
    def digits(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Use digits [0-9] when generating the password.
        """
        return pulumi.get(self, "digits")

    @digits.setter
    def digits(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "digits", value)

    @_builtins.property
    @pulumi.getter
    def length(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        The length of the password to be generated.
        """
        return pulumi.get(self, "length")

    @length.setter
    def length(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "length", value)

    @_builtins.property
    @pulumi.getter
    def symbols(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Use symbols [!@.-_*] when generating the password.
        """
        return pulumi.get(self, "symbols")

    @symbols.setter
    def symbols(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "symbols", value)


class ItemSectionMapArgsDict(TypedDict):
    field_map: NotRequired[pulumi.Input[Mapping[str, pulumi.Input['ItemSectionMapFieldMapArgsDict']]]]
    """
    A map of custom fields in the section, keyed by field label.
    """
    id: NotRequired[pulumi.Input[_builtins.str]]
    """
    A unique identifier for the section.
    """

@pulumi.input_type
class ItemSectionMapArgs:
    def __init__(__self__, *,
                 field_map: Optional[pulumi.Input[Mapping[str, pulumi.Input['ItemSectionMapFieldMapArgs']]]] = None,
                 id: Optional[pulumi.Input[_builtins.str]] = None):
        """
        :param pulumi.Input[Mapping[str, pulumi.Input['ItemSectionMapFieldMapArgs']]] field_map: A map of custom fields in the section, keyed by field label.
        :param pulumi.Input[_builtins.str] id: A unique identifier for the section.
        """
        if field_map is not None:
            pulumi.set(__self__, "field_map", field_map)
        if id is not None:
            pulumi.set(__self__, "id", id)

    @_builtins.property
    @pulumi.getter(name="fieldMap")
    def field_map(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input['ItemSectionMapFieldMapArgs']]]]:
        """
        A map of custom fields in the section, keyed by field label.
        """
        return pulumi.get(self, "field_map")

    @field_map.setter
    def field_map(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input['ItemSectionMapFieldMapArgs']]]]):
        pulumi.set(self, "field_map", value)

    @_builtins.property
    @pulumi.getter
    def id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        A unique identifier for the section.
        """
        return pulumi.get(self, "id")

    @id.setter
    def id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "id", value)


class ItemSectionMapFieldMapArgsDict(TypedDict):
    id: NotRequired[pulumi.Input[_builtins.str]]
    """
    A unique identifier for the field.
    """
    password_recipe: NotRequired[pulumi.Input['ItemSectionMapFieldMapPasswordRecipeArgsDict']]
    """
    The recipe used to generate a new value for a password.
    """
    type: NotRequired[pulumi.Input[_builtins.str]]
    """
    The type of value stored in the field. One of ["STRING" "CONCEALED" "EMAIL" "URL" "OTP" "DATE" "MONTH_YEAR" "MENU"]
    """
    value: NotRequired[pulumi.Input[_builtins.str]]
    """
    The value of the field.
    """

@pulumi.input_type
class ItemSectionMapFieldMapArgs:
    def __init__(__self__, *,
                 id: Optional[pulumi.Input[_builtins.str]] = None,
                 password_recipe: Optional[pulumi.Input['ItemSectionMapFieldMapPasswordRecipeArgs']] = None,
                 type: Optional[pulumi.Input[_builtins.str]] = None,
                 value: Optional[pulumi.Input[_builtins.str]] = None):
        """
        :param pulumi.Input[_builtins.str] id: A unique identifier for the field.
        :param pulumi.Input['ItemSectionMapFieldMapPasswordRecipeArgs'] password_recipe: The recipe used to generate a new value for a password.
        :param pulumi.Input[_builtins.str] type: The type of value stored in the field. One of ["STRING" "CONCEALED" "EMAIL" "URL" "OTP" "DATE" "MONTH_YEAR" "MENU"]
        :param pulumi.Input[_builtins.str] value: The value of the field.
        """
        if id is not None:
            pulumi.set(__self__, "id", id)
        if password_recipe is not None:
            pulumi.set(__self__, "password_recipe", password_recipe)
        if type is not None:
            pulumi.set(__self__, "type", type)
        if value is not None:
            pulumi.set(__self__, "value", value)

    @_builtins.property
    @pulumi.getter
    def id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        A unique identifier for the field.
        """
        return pulumi.get(self, "id")

    @id.setter
    def id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "id", value)

    @_builtins.property
    @pulumi.getter(name="passwordRecipe")
    def password_recipe(self) -> Optional[pulumi.Input['ItemSectionMapFieldMapPasswordRecipeArgs']]:
        """
        The recipe used to generate a new value for a password.
        """
        return pulumi.get(self, "password_recipe")

    @password_recipe.setter
    def password_recipe(self, value: Optional[pulumi.Input['ItemSectionMapFieldMapPasswordRecipeArgs']]):
        pulumi.set(self, "password_recipe", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The type of value stored in the field. One of ["STRING" "CONCEALED" "EMAIL" "URL" "OTP" "DATE" "MONTH_YEAR" "MENU"]
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "type", value)

    @_builtins.property
    @pulumi.getter
    def value(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The value of the field.
        """
        return pulumi.get(self, "value")

    @value.setter
    def value(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "value", value)


class ItemSectionMapFieldMapPasswordRecipeArgsDict(TypedDict):
    digits: NotRequired[pulumi.Input[_builtins.bool]]
    """
    Use digits [0-9] when generating the password.
    """
    length: NotRequired[pulumi.Input[_builtins.int]]
    """
    The length of the password to be generated.
    """
    symbols: NotRequired[pulumi.Input[_builtins.bool]]
    """
    Use symbols [!@.-_*] when generating the password.
    """

@pulumi.input_type
class ItemSectionMapFieldMapPasswordRecipeArgs:
    def __init__(__self__, *,
                 digits: Optional[pulumi.Input[_builtins.bool]] = None,
                 length: Optional[pulumi.Input[_builtins.int]] = None,
                 symbols: Optional[pulumi.Input[_builtins.bool]] = None):
        """
        :param pulumi.Input[_builtins.bool] digits: Use digits [0-9] when generating the password.
        :param pulumi.Input[_builtins.int] length: The length of the password to be generated.
        :param pulumi.Input[_builtins.bool] symbols: Use symbols [!@.-_*] when generating the password.
        """
        if digits is not None:
            pulumi.set(__self__, "digits", digits)
        if length is not None:
            pulumi.set(__self__, "length", length)
        if symbols is not None:
            pulumi.set(__self__, "symbols", symbols)

    @_builtins.property
    @pulumi.getter
    def digits(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Use digits [0-9] when generating the password.
        """
        return pulumi.get(self, "digits")

    @digits.setter
    def digits(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "digits", value)

    @_builtins.property
    @pulumi.getter
    def length(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        The length of the password to be generated.
        """
        return pulumi.get(self, "length")

    @length.setter
    def length(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "length", value)

    @_builtins.property
    @pulumi.getter
    def symbols(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Use symbols [!@.-_*] when generating the password.
        """
        return pulumi.get(self, "symbols")

    @symbols.setter
    def symbols(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "symbols", value)


class GetEnvironmentMetadataArgsDict(TypedDict):
    masked: _builtins.bool
    """
    Whether the value is hidden by default in the 1Password app.
    """
    name: _builtins.str
    """
    The environment variable name.
    """
    value: _builtins.str
    """
    The environment variable value.
    """

@pulumi.input_type
class GetEnvironmentMetadataArgs:
    def __init__(__self__, *,
                 masked: _builtins.bool,
                 name: _builtins.str,
                 value: _builtins.str):
        """
        :param _builtins.bool masked: Whether the value is hidden by default in the 1Password app.
        :param _builtins.str name: The environment variable name.
        :param _builtins.str value: The environment variable value.
        """
        pulumi.set(__self__, "masked", masked)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "value", value)

    @_builtins.property
    @pulumi.getter
    def masked(self) -> _builtins.bool:
        """
        Whether the value is hidden by default in the 1Password app.
        """
        return pulumi.get(self, "masked")

    @masked.setter
    def masked(self, value: _builtins.bool):
        pulumi.set(self, "masked", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        The environment variable name.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: _builtins.str):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def value(self) -> _builtins.str:
        """
        The environment variable value.
        """
        return pulumi.get(self, "value")

    @value.setter
    def value(self, value: _builtins.str):
        pulumi.set(self, "value", value)


class GetItemFileArgsDict(TypedDict):
    content: _builtins.str
    """
    The content of the file.
    """
    content_base64: _builtins.str
    """
    The content of the file in base64 encoding. (Use this for binary files.)
    """
    id: _builtins.str
    """
    The UUID of the file.
    """
    name: _builtins.str
    """
    The name of the file.
    """

@pulumi.input_type
class GetItemFileArgs:
    def __init__(__self__, *,
                 content: _builtins.str,
                 content_base64: _builtins.str,
                 id: _builtins.str,
                 name: _builtins.str):
        """
        :param _builtins.str content: The content of the file.
        :param _builtins.str content_base64: The content of the file in base64 encoding. (Use this for binary files.)
        :param _builtins.str id: The UUID of the file.
        :param _builtins.str name: The name of the file.
        """
        pulumi.set(__self__, "content", content)
        pulumi.set(__self__, "content_base64", content_base64)
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "name", name)

    @_builtins.property
    @pulumi.getter
    def content(self) -> _builtins.str:
        """
        The content of the file.
        """
        return pulumi.get(self, "content")

    @content.setter
    def content(self, value: _builtins.str):
        pulumi.set(self, "content", value)

    @_builtins.property
    @pulumi.getter(name="contentBase64")
    def content_base64(self) -> _builtins.str:
        """
        The content of the file in base64 encoding. (Use this for binary files.)
        """
        return pulumi.get(self, "content_base64")

    @content_base64.setter
    def content_base64(self, value: _builtins.str):
        pulumi.set(self, "content_base64", value)

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The UUID of the file.
        """
        return pulumi.get(self, "id")

    @id.setter
    def id(self, value: _builtins.str):
        pulumi.set(self, "id", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        The name of the file.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: _builtins.str):
        pulumi.set(self, "name", value)


class GetItemSectionArgsDict(TypedDict):
    id: _builtins.str
    """
    A unique identifier for the section.
    """
    label: _builtins.str
    """
    The label for the section.
    """
    fields: NotRequired[Sequence['GetItemSectionFieldArgsDict']]
    """
    A list of custom fields in the section
    """
    files: NotRequired[Sequence['GetItemSectionFileArgsDict']]
    """
    A list of files attached to the section.
    """

@pulumi.input_type
class GetItemSectionArgs:
    def __init__(__self__, *,
                 id: _builtins.str,
                 label: _builtins.str,
                 fields: Optional[Sequence['GetItemSectionFieldArgs']] = None,
                 files: Optional[Sequence['GetItemSectionFileArgs']] = None):
        """
        :param _builtins.str id: A unique identifier for the section.
        :param _builtins.str label: The label for the section.
        :param Sequence['GetItemSectionFieldArgs'] fields: A list of custom fields in the section
        :param Sequence['GetItemSectionFileArgs'] files: A list of files attached to the section.
        """
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "label", label)
        if fields is not None:
            pulumi.set(__self__, "fields", fields)
        if files is not None:
            pulumi.set(__self__, "files", files)

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        A unique identifier for the section.
        """
        return pulumi.get(self, "id")

    @id.setter
    def id(self, value: _builtins.str):
        pulumi.set(self, "id", value)

    @_builtins.property
    @pulumi.getter
    def label(self) -> _builtins.str:
        """
        The label for the section.
        """
        return pulumi.get(self, "label")

    @label.setter
    def label(self, value: _builtins.str):
        pulumi.set(self, "label", value)

    @_builtins.property
    @pulumi.getter
    def fields(self) -> Optional[Sequence['GetItemSectionFieldArgs']]:
        """
        A list of custom fields in the section
        """
        return pulumi.get(self, "fields")

    @fields.setter
    def fields(self, value: Optional[Sequence['GetItemSectionFieldArgs']]):
        pulumi.set(self, "fields", value)

    @_builtins.property
    @pulumi.getter
    def files(self) -> Optional[Sequence['GetItemSectionFileArgs']]:
        """
        A list of files attached to the section.
        """
        return pulumi.get(self, "files")

    @files.setter
    def files(self, value: Optional[Sequence['GetItemSectionFileArgs']]):
        pulumi.set(self, "files", value)


class GetItemSectionFieldArgsDict(TypedDict):
    id: _builtins.str
    """
    A unique identifier for the field.
    """
    label: _builtins.str
    """
    The label for the field.
    """
    type: _builtins.str
    """
    The type of value stored in the field. One of ["STRING" "CONCEALED" "EMAIL" "URL" "OTP" "DATE" "MONTH_YEAR" "MENU"]
    """
    value: _builtins.str
    """
    The value of the field.
    """

@pulumi.input_type
class GetItemSectionFieldArgs:
    def __init__(__self__, *,
                 id: _builtins.str,
                 label: _builtins.str,
                 type: _builtins.str,
                 value: _builtins.str):
        """
        :param _builtins.str id: A unique identifier for the field.
        :param _builtins.str label: The label for the field.
        :param _builtins.str type: The type of value stored in the field. One of ["STRING" "CONCEALED" "EMAIL" "URL" "OTP" "DATE" "MONTH_YEAR" "MENU"]
        :param _builtins.str value: The value of the field.
        """
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "label", label)
        pulumi.set(__self__, "type", type)
        pulumi.set(__self__, "value", value)

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        A unique identifier for the field.
        """
        return pulumi.get(self, "id")

    @id.setter
    def id(self, value: _builtins.str):
        pulumi.set(self, "id", value)

    @_builtins.property
    @pulumi.getter
    def label(self) -> _builtins.str:
        """
        The label for the field.
        """
        return pulumi.get(self, "label")

    @label.setter
    def label(self, value: _builtins.str):
        pulumi.set(self, "label", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> _builtins.str:
        """
        The type of value stored in the field. One of ["STRING" "CONCEALED" "EMAIL" "URL" "OTP" "DATE" "MONTH_YEAR" "MENU"]
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: _builtins.str):
        pulumi.set(self, "type", value)

    @_builtins.property
    @pulumi.getter
    def value(self) -> _builtins.str:
        """
        The value of the field.
        """
        return pulumi.get(self, "value")

    @value.setter
    def value(self, value: _builtins.str):
        pulumi.set(self, "value", value)


class GetItemSectionFileArgsDict(TypedDict):
    content: _builtins.str
    """
    The content of the file.
    """
    content_base64: _builtins.str
    """
    The content of the file in base64 encoding. (Use this for binary files.)
    """
    id: _builtins.str
    """
    The UUID of the file.
    """
    name: _builtins.str
    """
    The name of the file.
    """

@pulumi.input_type
class GetItemSectionFileArgs:
    def __init__(__self__, *,
                 content: _builtins.str,
                 content_base64: _builtins.str,
                 id: _builtins.str,
                 name: _builtins.str):
        """
        :param _builtins.str content: The content of the file.
        :param _builtins.str content_base64: The content of the file in base64 encoding. (Use this for binary files.)
        :param _builtins.str id: The UUID of the file.
        :param _builtins.str name: The name of the file.
        """
        pulumi.set(__self__, "content", content)
        pulumi.set(__self__, "content_base64", content_base64)
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "name", name)

    @_builtins.property
    @pulumi.getter
    def content(self) -> _builtins.str:
        """
        The content of the file.
        """
        return pulumi.get(self, "content")

    @content.setter
    def content(self, value: _builtins.str):
        pulumi.set(self, "content", value)

    @_builtins.property
    @pulumi.getter(name="contentBase64")
    def content_base64(self) -> _builtins.str:
        """
        The content of the file in base64 encoding. (Use this for binary files.)
        """
        return pulumi.get(self, "content_base64")

    @content_base64.setter
    def content_base64(self, value: _builtins.str):
        pulumi.set(self, "content_base64", value)

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The UUID of the file.
        """
        return pulumi.get(self, "id")

    @id.setter
    def id(self, value: _builtins.str):
        pulumi.set(self, "id", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        The name of the file.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: _builtins.str):
        pulumi.set(self, "name", value)


class GetItemSectionMapArgsDict(TypedDict):
    field_map: Mapping[str, 'GetItemSectionMapFieldMapArgsDict']
    """
    A map of custom fields in the section, keyed by field label.
    """
    file_map: Mapping[str, 'GetItemSectionMapFileMapArgsDict']
    """
    A map of files attached to the section, keyed by file label.
    """
    id: _builtins.str
    """
    A unique identifier for the section.
    """

@pulumi.input_type
class GetItemSectionMapArgs:
    def __init__(__self__, *,
                 field_map: Mapping[str, 'GetItemSectionMapFieldMapArgs'],
                 file_map: Mapping[str, 'GetItemSectionMapFileMapArgs'],
                 id: _builtins.str):
        """
        :param Mapping[str, 'GetItemSectionMapFieldMapArgs'] field_map: A map of custom fields in the section, keyed by field label.
        :param Mapping[str, 'GetItemSectionMapFileMapArgs'] file_map: A map of files attached to the section, keyed by file label.
        :param _builtins.str id: A unique identifier for the section.
        """
        pulumi.set(__self__, "field_map", field_map)
        pulumi.set(__self__, "file_map", file_map)
        pulumi.set(__self__, "id", id)

    @_builtins.property
    @pulumi.getter(name="fieldMap")
    def field_map(self) -> Mapping[str, 'GetItemSectionMapFieldMapArgs']:
        """
        A map of custom fields in the section, keyed by field label.
        """
        return pulumi.get(self, "field_map")

    @field_map.setter
    def field_map(self, value: Mapping[str, 'GetItemSectionMapFieldMapArgs']):
        pulumi.set(self, "field_map", value)

    @_builtins.property
    @pulumi.getter(name="fileMap")
    def file_map(self) -> Mapping[str, 'GetItemSectionMapFileMapArgs']:
        """
        A map of files attached to the section, keyed by file label.
        """
        return pulumi.get(self, "file_map")

    @file_map.setter
    def file_map(self, value: Mapping[str, 'GetItemSectionMapFileMapArgs']):
        pulumi.set(self, "file_map", value)

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        A unique identifier for the section.
        """
        return pulumi.get(self, "id")

    @id.setter
    def id(self, value: _builtins.str):
        pulumi.set(self, "id", value)


class GetItemSectionMapFieldMapArgsDict(TypedDict):
    id: _builtins.str
    """
    A unique identifier for the field.
    """
    type: _builtins.str
    """
    The type of value stored in the field. One of ["STRING" "CONCEALED" "EMAIL" "URL" "OTP" "DATE" "MONTH_YEAR" "MENU"]
    """
    value: _builtins.str
    """
    The value of the field.
    """

@pulumi.input_type
class GetItemSectionMapFieldMapArgs:
    def __init__(__self__, *,
                 id: _builtins.str,
                 type: _builtins.str,
                 value: _builtins.str):
        """
        :param _builtins.str id: A unique identifier for the field.
        :param _builtins.str type: The type of value stored in the field. One of ["STRING" "CONCEALED" "EMAIL" "URL" "OTP" "DATE" "MONTH_YEAR" "MENU"]
        :param _builtins.str value: The value of the field.
        """
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "type", type)
        pulumi.set(__self__, "value", value)

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        A unique identifier for the field.
        """
        return pulumi.get(self, "id")

    @id.setter
    def id(self, value: _builtins.str):
        pulumi.set(self, "id", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> _builtins.str:
        """
        The type of value stored in the field. One of ["STRING" "CONCEALED" "EMAIL" "URL" "OTP" "DATE" "MONTH_YEAR" "MENU"]
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: _builtins.str):
        pulumi.set(self, "type", value)

    @_builtins.property
    @pulumi.getter
    def value(self) -> _builtins.str:
        """
        The value of the field.
        """
        return pulumi.get(self, "value")

    @value.setter
    def value(self, value: _builtins.str):
        pulumi.set(self, "value", value)


class GetItemSectionMapFileMapArgsDict(TypedDict):
    content: _builtins.str
    """
    The content of the file.
    """
    content_base64: _builtins.str
    """
    The content of the file in base64 encoding. (Use this for binary files.)
    """
    id: _builtins.str
    """
    The UUID of the file.
    """

@pulumi.input_type
class GetItemSectionMapFileMapArgs:
    def __init__(__self__, *,
                 content: _builtins.str,
                 content_base64: _builtins.str,
                 id: _builtins.str):
        """
        :param _builtins.str content: The content of the file.
        :param _builtins.str content_base64: The content of the file in base64 encoding. (Use this for binary files.)
        :param _builtins.str id: The UUID of the file.
        """
        pulumi.set(__self__, "content", content)
        pulumi.set(__self__, "content_base64", content_base64)
        pulumi.set(__self__, "id", id)

    @_builtins.property
    @pulumi.getter
    def content(self) -> _builtins.str:
        """
        The content of the file.
        """
        return pulumi.get(self, "content")

    @content.setter
    def content(self, value: _builtins.str):
        pulumi.set(self, "content", value)

    @_builtins.property
    @pulumi.getter(name="contentBase64")
    def content_base64(self) -> _builtins.str:
        """
        The content of the file in base64 encoding. (Use this for binary files.)
        """
        return pulumi.get(self, "content_base64")

    @content_base64.setter
    def content_base64(self, value: _builtins.str):
        pulumi.set(self, "content_base64", value)

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The UUID of the file.
        """
        return pulumi.get(self, "id")

    @id.setter
    def id(self, value: _builtins.str):
        pulumi.set(self, "id", value)


