# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = [
    'GetEnvironmentResult',
    'AwaitableGetEnvironmentResult',
    'get_environment',
    'get_environment_output',
]

@pulumi.output_type
class GetEnvironmentResult:
    """
    A collection of values returned by getEnvironment.
    """
    def __init__(__self__, environment_id=None, id=None, metadatas=None, variables=None):
        if environment_id and not isinstance(environment_id, str):
            raise TypeError("Expected argument 'environment_id' to be a str")
        pulumi.set(__self__, "environment_id", environment_id)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if metadatas and not isinstance(metadatas, list):
            raise TypeError("Expected argument 'metadatas' to be a list")
        pulumi.set(__self__, "metadatas", metadatas)
        if variables and not isinstance(variables, dict):
            raise TypeError("Expected argument 'variables' to be a dict")
        pulumi.set(__self__, "variables", variables)

    @_builtins.property
    @pulumi.getter(name="environmentId")
    def environment_id(self) -> _builtins.str:
        """
        The unique identifier of the 1Password Environment. You can find this in the 1Password desktop app under Developer > View Environments > Manage environment > Copy environment ID.
        """
        return pulumi.get(self, "environment_id")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The Terraform resource identifier for this environment in the format `environments/<environment_id>`.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def metadatas(self) -> Optional[Sequence['outputs.GetEnvironmentMetadataResult']]:
        """
        Metadata for each environment variable (name, value, and masked flag). Use this when you need the full structure; use `variables` for a simple name-to-value map.
        """
        return pulumi.get(self, "metadatas")

    @_builtins.property
    @pulumi.getter
    def variables(self) -> Mapping[str, _builtins.str]:
        """
        A map of environment variable names to their values. Use this for passing secrets into Terraform resources or for use in `environment` blocks.
        """
        return pulumi.get(self, "variables")


class AwaitableGetEnvironmentResult(GetEnvironmentResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetEnvironmentResult(
            environment_id=self.environment_id,
            id=self.id,
            metadatas=self.metadatas,
            variables=self.variables)


def get_environment(environment_id: Optional[_builtins.str] = None,
                    metadatas: Optional[Sequence[Union['GetEnvironmentMetadataArgs', 'GetEnvironmentMetadataArgsDict']]] = None,
                    opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetEnvironmentResult:
    """
    Use this data source to read environment variables from a [1Password Environment](https://developer.1password.com/docs/environments/). 1Password Environments allow you to organize and manage project secrets as environment variables. This data source is only supported when using **service account** or **desktop app** authentication; it is not available with 1Password Connect.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_onepassword as onepassword

    # Read environment variables from a 1Password Environment.
    # Requires service account or desktop app authentication (not 1Password Connect).
    example = onepassword.get_environment(environment_id="your-environment-id")
    pulumi.export("envVariables", example.variables)
    ```


    :param _builtins.str environment_id: The unique identifier of the 1Password Environment. You can find this in the 1Password desktop app under Developer > View Environments > Manage environment > Copy environment ID.
    :param Sequence[Union['GetEnvironmentMetadataArgs', 'GetEnvironmentMetadataArgsDict']] metadatas: Metadata for each environment variable (name, value, and masked flag). Use this when you need the full structure; use `variables` for a simple name-to-value map.
    """
    __args__ = dict()
    __args__['environmentId'] = environment_id
    __args__['metadatas'] = metadatas
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('onepassword:index/getEnvironment:getEnvironment', __args__, opts=opts, typ=GetEnvironmentResult).value

    return AwaitableGetEnvironmentResult(
        environment_id=pulumi.get(__ret__, 'environment_id'),
        id=pulumi.get(__ret__, 'id'),
        metadatas=pulumi.get(__ret__, 'metadatas'),
        variables=pulumi.get(__ret__, 'variables'))
def get_environment_output(environment_id: Optional[pulumi.Input[_builtins.str]] = None,
                           metadatas: Optional[pulumi.Input[Optional[Sequence[Union['GetEnvironmentMetadataArgs', 'GetEnvironmentMetadataArgsDict']]]]] = None,
                           opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetEnvironmentResult]:
    """
    Use this data source to read environment variables from a [1Password Environment](https://developer.1password.com/docs/environments/). 1Password Environments allow you to organize and manage project secrets as environment variables. This data source is only supported when using **service account** or **desktop app** authentication; it is not available with 1Password Connect.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_onepassword as onepassword

    # Read environment variables from a 1Password Environment.
    # Requires service account or desktop app authentication (not 1Password Connect).
    example = onepassword.get_environment(environment_id="your-environment-id")
    pulumi.export("envVariables", example.variables)
    ```


    :param _builtins.str environment_id: The unique identifier of the 1Password Environment. You can find this in the 1Password desktop app under Developer > View Environments > Manage environment > Copy environment ID.
    :param Sequence[Union['GetEnvironmentMetadataArgs', 'GetEnvironmentMetadataArgsDict']] metadatas: Metadata for each environment variable (name, value, and masked flag). Use this when you need the full structure; use `variables` for a simple name-to-value map.
    """
    __args__ = dict()
    __args__['environmentId'] = environment_id
    __args__['metadatas'] = metadatas
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('onepassword:index/getEnvironment:getEnvironment', __args__, opts=opts, typ=GetEnvironmentResult)
    return __ret__.apply(lambda __response__: GetEnvironmentResult(
        environment_id=pulumi.get(__response__, 'environment_id'),
        id=pulumi.get(__response__, 'id'),
        metadatas=pulumi.get(__response__, 'metadatas'),
        variables=pulumi.get(__response__, 'variables')))
