# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = [
    'GetItemResult',
    'AwaitableGetItemResult',
    'get_item',
    'get_item_output',
]

@pulumi.output_type
class GetItemResult:
    """
    A collection of values returned by getItem.
    """
    def __init__(__self__, category=None, credential=None, database=None, filename=None, files=None, hostname=None, id=None, note_value=None, password=None, port=None, private_key=None, private_key_openssh=None, public_key=None, section_map=None, sections=None, tags=None, title=None, type=None, url=None, username=None, uuid=None, valid_from=None, vault=None):
        if category and not isinstance(category, str):
            raise TypeError("Expected argument 'category' to be a str")
        pulumi.set(__self__, "category", category)
        if credential and not isinstance(credential, str):
            raise TypeError("Expected argument 'credential' to be a str")
        pulumi.set(__self__, "credential", credential)
        if database and not isinstance(database, str):
            raise TypeError("Expected argument 'database' to be a str")
        pulumi.set(__self__, "database", database)
        if filename and not isinstance(filename, str):
            raise TypeError("Expected argument 'filename' to be a str")
        pulumi.set(__self__, "filename", filename)
        if files and not isinstance(files, list):
            raise TypeError("Expected argument 'files' to be a list")
        pulumi.set(__self__, "files", files)
        if hostname and not isinstance(hostname, str):
            raise TypeError("Expected argument 'hostname' to be a str")
        pulumi.set(__self__, "hostname", hostname)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if note_value and not isinstance(note_value, str):
            raise TypeError("Expected argument 'note_value' to be a str")
        pulumi.set(__self__, "note_value", note_value)
        if password and not isinstance(password, str):
            raise TypeError("Expected argument 'password' to be a str")
        pulumi.set(__self__, "password", password)
        if port and not isinstance(port, str):
            raise TypeError("Expected argument 'port' to be a str")
        pulumi.set(__self__, "port", port)
        if private_key and not isinstance(private_key, str):
            raise TypeError("Expected argument 'private_key' to be a str")
        pulumi.set(__self__, "private_key", private_key)
        if private_key_openssh and not isinstance(private_key_openssh, str):
            raise TypeError("Expected argument 'private_key_openssh' to be a str")
        pulumi.set(__self__, "private_key_openssh", private_key_openssh)
        if public_key and not isinstance(public_key, str):
            raise TypeError("Expected argument 'public_key' to be a str")
        pulumi.set(__self__, "public_key", public_key)
        if section_map and not isinstance(section_map, dict):
            raise TypeError("Expected argument 'section_map' to be a dict")
        pulumi.set(__self__, "section_map", section_map)
        if sections and not isinstance(sections, list):
            raise TypeError("Expected argument 'sections' to be a list")
        pulumi.set(__self__, "sections", sections)
        if tags and not isinstance(tags, list):
            raise TypeError("Expected argument 'tags' to be a list")
        pulumi.set(__self__, "tags", tags)
        if title and not isinstance(title, str):
            raise TypeError("Expected argument 'title' to be a str")
        pulumi.set(__self__, "title", title)
        if type and not isinstance(type, str):
            raise TypeError("Expected argument 'type' to be a str")
        pulumi.set(__self__, "type", type)
        if url and not isinstance(url, str):
            raise TypeError("Expected argument 'url' to be a str")
        pulumi.set(__self__, "url", url)
        if username and not isinstance(username, str):
            raise TypeError("Expected argument 'username' to be a str")
        pulumi.set(__self__, "username", username)
        if uuid and not isinstance(uuid, str):
            raise TypeError("Expected argument 'uuid' to be a str")
        pulumi.set(__self__, "uuid", uuid)
        if valid_from and not isinstance(valid_from, str):
            raise TypeError("Expected argument 'valid_from' to be a str")
        pulumi.set(__self__, "valid_from", valid_from)
        if vault and not isinstance(vault, str):
            raise TypeError("Expected argument 'vault' to be a str")
        pulumi.set(__self__, "vault", vault)

    @_builtins.property
    @pulumi.getter
    def category(self) -> _builtins.str:
        """
        The category of the item. One of ["login" "password" "database" "secure*note" "document" "ssh*key" "api_credential"]
        """
        return pulumi.get(self, "category")

    @_builtins.property
    @pulumi.getter
    def credential(self) -> _builtins.str:
        """
        (Only applies to the API credential category) API credential for this item.
        """
        return pulumi.get(self, "credential")

    @_builtins.property
    @pulumi.getter
    def database(self) -> _builtins.str:
        """
        (Only applies to the database category) The name of the database.
        """
        return pulumi.get(self, "database")

    @_builtins.property
    @pulumi.getter
    def filename(self) -> _builtins.str:
        """
        (Only applies to the API credential category) The filename associated with the API credential.
        """
        return pulumi.get(self, "filename")

    @_builtins.property
    @pulumi.getter
    def files(self) -> Optional[Sequence['outputs.GetItemFileResult']]:
        """
        A list of files attached to the document item.
        """
        return pulumi.get(self, "files")

    @_builtins.property
    @pulumi.getter
    def hostname(self) -> _builtins.str:
        """
        (Only applies to the database category) The address where the database can be found
        """
        return pulumi.get(self, "hostname")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The Terraform resource identifier for this item in the format `vaults/<vault_id>/items/<item_id>`.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="noteValue")
    def note_value(self) -> _builtins.str:
        """
        Secure Note value.
        """
        return pulumi.get(self, "note_value")

    @_builtins.property
    @pulumi.getter
    def password(self) -> _builtins.str:
        """
        Password for this item.
        """
        return pulumi.get(self, "password")

    @_builtins.property
    @pulumi.getter
    def port(self) -> _builtins.str:
        """
        (Only applies to the database category) The port the database is listening on.
        """
        return pulumi.get(self, "port")

    @_builtins.property
    @pulumi.getter(name="privateKey")
    def private_key(self) -> _builtins.str:
        """
        SSH Private Key in PKCS#8 for this item.
        """
        return pulumi.get(self, "private_key")

    @_builtins.property
    @pulumi.getter(name="privateKeyOpenssh")
    def private_key_openssh(self) -> _builtins.str:
        """
        SSH Private key in OpenSSH format.
        """
        return pulumi.get(self, "private_key_openssh")

    @_builtins.property
    @pulumi.getter(name="publicKey")
    def public_key(self) -> _builtins.str:
        """
        SSH Public Key for this item.
        """
        return pulumi.get(self, "public_key")

    @_builtins.property
    @pulumi.getter(name="sectionMap")
    def section_map(self) -> Mapping[str, 'outputs.GetItemSectionMapResult']:
        """
        A map of custom sections in an item, keyed by section label. This allows direct lookup of sections and their fields by label. Cannot be used together with `section`. Use either `section` (list) or `section_map` (map), but not both.
        """
        return pulumi.get(self, "section_map")

    @_builtins.property
    @pulumi.getter
    def sections(self) -> Optional[Sequence['outputs.GetItemSectionResult']]:
        """
        A list of custom sections in an item. Cannot be used together with `section_map`. Use either `section` (list) or `section_map` (map), but not both.
        """
        return pulumi.get(self, "sections")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Sequence[_builtins.str]:
        """
        An array of strings of the tags assigned to the item.
        """
        return pulumi.get(self, "tags")

    @_builtins.property
    @pulumi.getter
    def title(self) -> _builtins.str:
        """
        The title of the item to retrieve. This field will be populated with the title of the item if the item it looked up by its UUID.
        """
        return pulumi.get(self, "title")

    @_builtins.property
    @pulumi.getter
    def type(self) -> _builtins.str:
        """
        (Only applies to database and API credential categories) The type of database or API Credential.
        """
        return pulumi.get(self, "type")

    @_builtins.property
    @pulumi.getter
    def url(self) -> _builtins.str:
        """
        The primary URL for the item.
        """
        return pulumi.get(self, "url")

    @_builtins.property
    @pulumi.getter
    def username(self) -> _builtins.str:
        """
        Username for this item.
        """
        return pulumi.get(self, "username")

    @_builtins.property
    @pulumi.getter
    def uuid(self) -> _builtins.str:
        """
        The UUID of the item to retrieve. This field will be populated with the UUID of the item if the item it looked up by its title.
        """
        return pulumi.get(self, "uuid")

    @_builtins.property
    @pulumi.getter(name="validFrom")
    def valid_from(self) -> _builtins.str:
        """
        (Only applies to the API credential category) The timestamp from which the API credential is valid.
        """
        return pulumi.get(self, "valid_from")

    @_builtins.property
    @pulumi.getter
    def vault(self) -> _builtins.str:
        """
        The UUID of the vault the item is in.
        """
        return pulumi.get(self, "vault")


class AwaitableGetItemResult(GetItemResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetItemResult(
            category=self.category,
            credential=self.credential,
            database=self.database,
            filename=self.filename,
            files=self.files,
            hostname=self.hostname,
            id=self.id,
            note_value=self.note_value,
            password=self.password,
            port=self.port,
            private_key=self.private_key,
            private_key_openssh=self.private_key_openssh,
            public_key=self.public_key,
            section_map=self.section_map,
            sections=self.sections,
            tags=self.tags,
            title=self.title,
            type=self.type,
            url=self.url,
            username=self.username,
            uuid=self.uuid,
            valid_from=self.valid_from,
            vault=self.vault)


def get_item(files: Optional[Sequence[Union['GetItemFileArgs', 'GetItemFileArgsDict']]] = None,
             note_value: Optional[_builtins.str] = None,
             section_map: Optional[Mapping[str, Union['GetItemSectionMapArgs', 'GetItemSectionMapArgsDict']]] = None,
             sections: Optional[Sequence[Union['GetItemSectionArgs', 'GetItemSectionArgsDict']]] = None,
             title: Optional[_builtins.str] = None,
             uuid: Optional[_builtins.str] = None,
             vault: Optional[_builtins.str] = None,
             opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetItemResult:
    """
    Use this to get details of an item by its vault uuid and either the title or the uuid of the item.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_onepassword as onepassword

    example = onepassword.get_item(vault="your-vault-id",
        title="your-item-title")
    ```


    :param Sequence[Union['GetItemFileArgs', 'GetItemFileArgsDict']] files: A list of files attached to the document item.
    :param _builtins.str note_value: Secure Note value.
    :param Mapping[str, Union['GetItemSectionMapArgs', 'GetItemSectionMapArgsDict']] section_map: A map of custom sections in an item, keyed by section label. This allows direct lookup of sections and their fields by label. Cannot be used together with `section`. Use either `section` (list) or `section_map` (map), but not both.
    :param Sequence[Union['GetItemSectionArgs', 'GetItemSectionArgsDict']] sections: A list of custom sections in an item. Cannot be used together with `section_map`. Use either `section` (list) or `section_map` (map), but not both.
    :param _builtins.str title: The title of the item to retrieve. This field will be populated with the title of the item if the item it looked up by its UUID.
    :param _builtins.str uuid: The UUID of the item to retrieve. This field will be populated with the UUID of the item if the item it looked up by its title.
    :param _builtins.str vault: The UUID of the vault the item is in.
    """
    __args__ = dict()
    __args__['files'] = files
    __args__['noteValue'] = note_value
    __args__['sectionMap'] = section_map
    __args__['sections'] = sections
    __args__['title'] = title
    __args__['uuid'] = uuid
    __args__['vault'] = vault
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('onepassword:index/getItem:getItem', __args__, opts=opts, typ=GetItemResult).value

    return AwaitableGetItemResult(
        category=pulumi.get(__ret__, 'category'),
        credential=pulumi.get(__ret__, 'credential'),
        database=pulumi.get(__ret__, 'database'),
        filename=pulumi.get(__ret__, 'filename'),
        files=pulumi.get(__ret__, 'files'),
        hostname=pulumi.get(__ret__, 'hostname'),
        id=pulumi.get(__ret__, 'id'),
        note_value=pulumi.get(__ret__, 'note_value'),
        password=pulumi.get(__ret__, 'password'),
        port=pulumi.get(__ret__, 'port'),
        private_key=pulumi.get(__ret__, 'private_key'),
        private_key_openssh=pulumi.get(__ret__, 'private_key_openssh'),
        public_key=pulumi.get(__ret__, 'public_key'),
        section_map=pulumi.get(__ret__, 'section_map'),
        sections=pulumi.get(__ret__, 'sections'),
        tags=pulumi.get(__ret__, 'tags'),
        title=pulumi.get(__ret__, 'title'),
        type=pulumi.get(__ret__, 'type'),
        url=pulumi.get(__ret__, 'url'),
        username=pulumi.get(__ret__, 'username'),
        uuid=pulumi.get(__ret__, 'uuid'),
        valid_from=pulumi.get(__ret__, 'valid_from'),
        vault=pulumi.get(__ret__, 'vault'))
def get_item_output(files: Optional[pulumi.Input[Optional[Sequence[Union['GetItemFileArgs', 'GetItemFileArgsDict']]]]] = None,
                    note_value: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                    section_map: Optional[pulumi.Input[Optional[Mapping[str, Union['GetItemSectionMapArgs', 'GetItemSectionMapArgsDict']]]]] = None,
                    sections: Optional[pulumi.Input[Optional[Sequence[Union['GetItemSectionArgs', 'GetItemSectionArgsDict']]]]] = None,
                    title: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                    uuid: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                    vault: Optional[pulumi.Input[_builtins.str]] = None,
                    opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetItemResult]:
    """
    Use this to get details of an item by its vault uuid and either the title or the uuid of the item.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_onepassword as onepassword

    example = onepassword.get_item(vault="your-vault-id",
        title="your-item-title")
    ```


    :param Sequence[Union['GetItemFileArgs', 'GetItemFileArgsDict']] files: A list of files attached to the document item.
    :param _builtins.str note_value: Secure Note value.
    :param Mapping[str, Union['GetItemSectionMapArgs', 'GetItemSectionMapArgsDict']] section_map: A map of custom sections in an item, keyed by section label. This allows direct lookup of sections and their fields by label. Cannot be used together with `section`. Use either `section` (list) or `section_map` (map), but not both.
    :param Sequence[Union['GetItemSectionArgs', 'GetItemSectionArgsDict']] sections: A list of custom sections in an item. Cannot be used together with `section_map`. Use either `section` (list) or `section_map` (map), but not both.
    :param _builtins.str title: The title of the item to retrieve. This field will be populated with the title of the item if the item it looked up by its UUID.
    :param _builtins.str uuid: The UUID of the item to retrieve. This field will be populated with the UUID of the item if the item it looked up by its title.
    :param _builtins.str vault: The UUID of the vault the item is in.
    """
    __args__ = dict()
    __args__['files'] = files
    __args__['noteValue'] = note_value
    __args__['sectionMap'] = section_map
    __args__['sections'] = sections
    __args__['title'] = title
    __args__['uuid'] = uuid
    __args__['vault'] = vault
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('onepassword:index/getItem:getItem', __args__, opts=opts, typ=GetItemResult)
    return __ret__.apply(lambda __response__: GetItemResult(
        category=pulumi.get(__response__, 'category'),
        credential=pulumi.get(__response__, 'credential'),
        database=pulumi.get(__response__, 'database'),
        filename=pulumi.get(__response__, 'filename'),
        files=pulumi.get(__response__, 'files'),
        hostname=pulumi.get(__response__, 'hostname'),
        id=pulumi.get(__response__, 'id'),
        note_value=pulumi.get(__response__, 'note_value'),
        password=pulumi.get(__response__, 'password'),
        port=pulumi.get(__response__, 'port'),
        private_key=pulumi.get(__response__, 'private_key'),
        private_key_openssh=pulumi.get(__response__, 'private_key_openssh'),
        public_key=pulumi.get(__response__, 'public_key'),
        section_map=pulumi.get(__response__, 'section_map'),
        sections=pulumi.get(__response__, 'sections'),
        tags=pulumi.get(__response__, 'tags'),
        title=pulumi.get(__response__, 'title'),
        type=pulumi.get(__response__, 'type'),
        url=pulumi.get(__response__, 'url'),
        username=pulumi.get(__response__, 'username'),
        uuid=pulumi.get(__response__, 'uuid'),
        valid_from=pulumi.get(__response__, 'valid_from'),
        vault=pulumi.get(__response__, 'vault')))
