# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['ItemArgs', 'Item']

@pulumi.input_type
class ItemArgs:
    def __init__(__self__, *,
                 vault: pulumi.Input[_builtins.str],
                 category: Optional[pulumi.Input[_builtins.str]] = None,
                 database: Optional[pulumi.Input[_builtins.str]] = None,
                 hostname: Optional[pulumi.Input[_builtins.str]] = None,
                 note_value: Optional[pulumi.Input[_builtins.str]] = None,
                 note_value_wo: Optional[pulumi.Input[_builtins.str]] = None,
                 note_value_wo_version: Optional[pulumi.Input[_builtins.int]] = None,
                 password: Optional[pulumi.Input[_builtins.str]] = None,
                 password_recipe: Optional[pulumi.Input['ItemPasswordRecipeArgs']] = None,
                 password_wo: Optional[pulumi.Input[_builtins.str]] = None,
                 password_wo_version: Optional[pulumi.Input[_builtins.int]] = None,
                 port: Optional[pulumi.Input[_builtins.str]] = None,
                 section_map: Optional[pulumi.Input[Mapping[str, pulumi.Input['ItemSectionMapArgs']]]] = None,
                 sections: Optional[pulumi.Input[Sequence[pulumi.Input['ItemSectionArgs']]]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 title: Optional[pulumi.Input[_builtins.str]] = None,
                 type: Optional[pulumi.Input[_builtins.str]] = None,
                 url: Optional[pulumi.Input[_builtins.str]] = None,
                 username: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a Item resource.

        :param pulumi.Input[_builtins.str] vault: The UUID of the vault the item is in.
        :param pulumi.Input[_builtins.str] category: The category of the item. One of ["login" "password" "database" "secure_note"]
        :param pulumi.Input[_builtins.str] database: (Only applies to the database category) The name of the database.
        :param pulumi.Input[_builtins.str] hostname: (Only applies to the database category) The address where the database can be found
        :param pulumi.Input[_builtins.str] note_value: Secure Note value.
        :param pulumi.Input[_builtins.str] note_value_wo: **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
               A write-only secure note value for this item. This value is not stored in the state and is intended for use with ephemeral values. **Note**: Write-only arguments require Terraform 1.11 or later.
        :param pulumi.Input[_builtins.int] note_value_wo_version: An integer that must be incremented to trigger an update to the 'note_value_wo' field.
        :param pulumi.Input[_builtins.str] password: Password for this item.
        :param pulumi.Input['ItemPasswordRecipeArgs'] password_recipe: The recipe used to generate a new value for a password.
        :param pulumi.Input[_builtins.str] password_wo: **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
               A write-only password for this item. This value is not stored in the state and is intended for use with ephemeral values. **Note**: Write-only arguments require Terraform 1.11 or later.
        :param pulumi.Input[_builtins.int] password_wo_version: An integer that must be incremented to trigger an update to the 'password_wo' field.
        :param pulumi.Input[_builtins.str] port: (Only applies to the database category) The port the database is listening on.
        :param pulumi.Input[Mapping[str, pulumi.Input['ItemSectionMapArgs']]] section_map: A map of custom sections in an item, keyed by section label. This allows direct lookup of sections and their fields by label. Cannot be used together with `section`. Use either `section` (list) or `section_map` (map), but not both.
        :param pulumi.Input[Sequence[pulumi.Input['ItemSectionArgs']]] sections: A list of custom sections in an item. Cannot be used together with `section_map`. Use either `section` (list) or `section_map` (map), but not both.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tags: An array of strings of the tags assigned to the item.
        :param pulumi.Input[_builtins.str] title: The title of the item.
        :param pulumi.Input[_builtins.str] type: (Only applies to the database category) The type of database. One of ["db2" "filemaker" "msaccess" "mssql" "mysql" "oracle" "postgresql" "sqlite" "other"]
        :param pulumi.Input[_builtins.str] url: The primary URL for the item.
        :param pulumi.Input[_builtins.str] username: Username for this item.
        """
        pulumi.set(__self__, "vault", vault)
        if category is not None:
            pulumi.set(__self__, "category", category)
        if database is not None:
            pulumi.set(__self__, "database", database)
        if hostname is not None:
            pulumi.set(__self__, "hostname", hostname)
        if note_value is not None:
            pulumi.set(__self__, "note_value", note_value)
        if note_value_wo is not None:
            pulumi.set(__self__, "note_value_wo", note_value_wo)
        if note_value_wo_version is not None:
            pulumi.set(__self__, "note_value_wo_version", note_value_wo_version)
        if password is not None:
            pulumi.set(__self__, "password", password)
        if password_recipe is not None:
            pulumi.set(__self__, "password_recipe", password_recipe)
        if password_wo is not None:
            pulumi.set(__self__, "password_wo", password_wo)
        if password_wo_version is not None:
            pulumi.set(__self__, "password_wo_version", password_wo_version)
        if port is not None:
            pulumi.set(__self__, "port", port)
        if section_map is not None:
            pulumi.set(__self__, "section_map", section_map)
        if sections is not None:
            pulumi.set(__self__, "sections", sections)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if title is not None:
            pulumi.set(__self__, "title", title)
        if type is not None:
            pulumi.set(__self__, "type", type)
        if url is not None:
            pulumi.set(__self__, "url", url)
        if username is not None:
            pulumi.set(__self__, "username", username)

    @_builtins.property
    @pulumi.getter
    def vault(self) -> pulumi.Input[_builtins.str]:
        """
        The UUID of the vault the item is in.
        """
        return pulumi.get(self, "vault")

    @vault.setter
    def vault(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "vault", value)

    @_builtins.property
    @pulumi.getter
    def category(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The category of the item. One of ["login" "password" "database" "secure_note"]
        """
        return pulumi.get(self, "category")

    @category.setter
    def category(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "category", value)

    @_builtins.property
    @pulumi.getter
    def database(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        (Only applies to the database category) The name of the database.
        """
        return pulumi.get(self, "database")

    @database.setter
    def database(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "database", value)

    @_builtins.property
    @pulumi.getter
    def hostname(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        (Only applies to the database category) The address where the database can be found
        """
        return pulumi.get(self, "hostname")

    @hostname.setter
    def hostname(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "hostname", value)

    @_builtins.property
    @pulumi.getter(name="noteValue")
    def note_value(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Secure Note value.
        """
        return pulumi.get(self, "note_value")

    @note_value.setter
    def note_value(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "note_value", value)

    @_builtins.property
    @pulumi.getter(name="noteValueWo")
    def note_value_wo(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        A write-only secure note value for this item. This value is not stored in the state and is intended for use with ephemeral values. **Note**: Write-only arguments require Terraform 1.11 or later.
        """
        return pulumi.get(self, "note_value_wo")

    @note_value_wo.setter
    def note_value_wo(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "note_value_wo", value)

    @_builtins.property
    @pulumi.getter(name="noteValueWoVersion")
    def note_value_wo_version(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        An integer that must be incremented to trigger an update to the 'note_value_wo' field.
        """
        return pulumi.get(self, "note_value_wo_version")

    @note_value_wo_version.setter
    def note_value_wo_version(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "note_value_wo_version", value)

    @_builtins.property
    @pulumi.getter
    def password(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Password for this item.
        """
        return pulumi.get(self, "password")

    @password.setter
    def password(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "password", value)

    @_builtins.property
    @pulumi.getter(name="passwordRecipe")
    def password_recipe(self) -> Optional[pulumi.Input['ItemPasswordRecipeArgs']]:
        """
        The recipe used to generate a new value for a password.
        """
        return pulumi.get(self, "password_recipe")

    @password_recipe.setter
    def password_recipe(self, value: Optional[pulumi.Input['ItemPasswordRecipeArgs']]):
        pulumi.set(self, "password_recipe", value)

    @_builtins.property
    @pulumi.getter(name="passwordWo")
    def password_wo(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        A write-only password for this item. This value is not stored in the state and is intended for use with ephemeral values. **Note**: Write-only arguments require Terraform 1.11 or later.
        """
        return pulumi.get(self, "password_wo")

    @password_wo.setter
    def password_wo(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "password_wo", value)

    @_builtins.property
    @pulumi.getter(name="passwordWoVersion")
    def password_wo_version(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        An integer that must be incremented to trigger an update to the 'password_wo' field.
        """
        return pulumi.get(self, "password_wo_version")

    @password_wo_version.setter
    def password_wo_version(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "password_wo_version", value)

    @_builtins.property
    @pulumi.getter
    def port(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        (Only applies to the database category) The port the database is listening on.
        """
        return pulumi.get(self, "port")

    @port.setter
    def port(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "port", value)

    @_builtins.property
    @pulumi.getter(name="sectionMap")
    def section_map(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input['ItemSectionMapArgs']]]]:
        """
        A map of custom sections in an item, keyed by section label. This allows direct lookup of sections and their fields by label. Cannot be used together with `section`. Use either `section` (list) or `section_map` (map), but not both.
        """
        return pulumi.get(self, "section_map")

    @section_map.setter
    def section_map(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input['ItemSectionMapArgs']]]]):
        pulumi.set(self, "section_map", value)

    @_builtins.property
    @pulumi.getter
    def sections(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['ItemSectionArgs']]]]:
        """
        A list of custom sections in an item. Cannot be used together with `section_map`. Use either `section` (list) or `section_map` (map), but not both.
        """
        return pulumi.get(self, "sections")

    @sections.setter
    def sections(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['ItemSectionArgs']]]]):
        pulumi.set(self, "sections", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        An array of strings of the tags assigned to the item.
        """
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter
    def title(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The title of the item.
        """
        return pulumi.get(self, "title")

    @title.setter
    def title(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "title", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        (Only applies to the database category) The type of database. One of ["db2" "filemaker" "msaccess" "mssql" "mysql" "oracle" "postgresql" "sqlite" "other"]
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "type", value)

    @_builtins.property
    @pulumi.getter
    def url(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The primary URL for the item.
        """
        return pulumi.get(self, "url")

    @url.setter
    def url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "url", value)

    @_builtins.property
    @pulumi.getter
    def username(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Username for this item.
        """
        return pulumi.get(self, "username")

    @username.setter
    def username(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "username", value)


@pulumi.input_type
class _ItemState:
    def __init__(__self__, *,
                 category: Optional[pulumi.Input[_builtins.str]] = None,
                 database: Optional[pulumi.Input[_builtins.str]] = None,
                 hostname: Optional[pulumi.Input[_builtins.str]] = None,
                 note_value: Optional[pulumi.Input[_builtins.str]] = None,
                 note_value_wo: Optional[pulumi.Input[_builtins.str]] = None,
                 note_value_wo_version: Optional[pulumi.Input[_builtins.int]] = None,
                 password: Optional[pulumi.Input[_builtins.str]] = None,
                 password_recipe: Optional[pulumi.Input['ItemPasswordRecipeArgs']] = None,
                 password_wo: Optional[pulumi.Input[_builtins.str]] = None,
                 password_wo_version: Optional[pulumi.Input[_builtins.int]] = None,
                 port: Optional[pulumi.Input[_builtins.str]] = None,
                 section_map: Optional[pulumi.Input[Mapping[str, pulumi.Input['ItemSectionMapArgs']]]] = None,
                 sections: Optional[pulumi.Input[Sequence[pulumi.Input['ItemSectionArgs']]]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 title: Optional[pulumi.Input[_builtins.str]] = None,
                 type: Optional[pulumi.Input[_builtins.str]] = None,
                 url: Optional[pulumi.Input[_builtins.str]] = None,
                 username: Optional[pulumi.Input[_builtins.str]] = None,
                 uuid: Optional[pulumi.Input[_builtins.str]] = None,
                 vault: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering Item resources.

        :param pulumi.Input[_builtins.str] category: The category of the item. One of ["login" "password" "database" "secure_note"]
        :param pulumi.Input[_builtins.str] database: (Only applies to the database category) The name of the database.
        :param pulumi.Input[_builtins.str] hostname: (Only applies to the database category) The address where the database can be found
        :param pulumi.Input[_builtins.str] note_value: Secure Note value.
        :param pulumi.Input[_builtins.str] note_value_wo: **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
               A write-only secure note value for this item. This value is not stored in the state and is intended for use with ephemeral values. **Note**: Write-only arguments require Terraform 1.11 or later.
        :param pulumi.Input[_builtins.int] note_value_wo_version: An integer that must be incremented to trigger an update to the 'note_value_wo' field.
        :param pulumi.Input[_builtins.str] password: Password for this item.
        :param pulumi.Input['ItemPasswordRecipeArgs'] password_recipe: The recipe used to generate a new value for a password.
        :param pulumi.Input[_builtins.str] password_wo: **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
               A write-only password for this item. This value is not stored in the state and is intended for use with ephemeral values. **Note**: Write-only arguments require Terraform 1.11 or later.
        :param pulumi.Input[_builtins.int] password_wo_version: An integer that must be incremented to trigger an update to the 'password_wo' field.
        :param pulumi.Input[_builtins.str] port: (Only applies to the database category) The port the database is listening on.
        :param pulumi.Input[Mapping[str, pulumi.Input['ItemSectionMapArgs']]] section_map: A map of custom sections in an item, keyed by section label. This allows direct lookup of sections and their fields by label. Cannot be used together with `section`. Use either `section` (list) or `section_map` (map), but not both.
        :param pulumi.Input[Sequence[pulumi.Input['ItemSectionArgs']]] sections: A list of custom sections in an item. Cannot be used together with `section_map`. Use either `section` (list) or `section_map` (map), but not both.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tags: An array of strings of the tags assigned to the item.
        :param pulumi.Input[_builtins.str] title: The title of the item.
        :param pulumi.Input[_builtins.str] type: (Only applies to the database category) The type of database. One of ["db2" "filemaker" "msaccess" "mssql" "mysql" "oracle" "postgresql" "sqlite" "other"]
        :param pulumi.Input[_builtins.str] url: The primary URL for the item.
        :param pulumi.Input[_builtins.str] username: Username for this item.
        :param pulumi.Input[_builtins.str] uuid: The UUID of the item. Item identifiers are unique within a specific vault.
        :param pulumi.Input[_builtins.str] vault: The UUID of the vault the item is in.
        """
        if category is not None:
            pulumi.set(__self__, "category", category)
        if database is not None:
            pulumi.set(__self__, "database", database)
        if hostname is not None:
            pulumi.set(__self__, "hostname", hostname)
        if note_value is not None:
            pulumi.set(__self__, "note_value", note_value)
        if note_value_wo is not None:
            pulumi.set(__self__, "note_value_wo", note_value_wo)
        if note_value_wo_version is not None:
            pulumi.set(__self__, "note_value_wo_version", note_value_wo_version)
        if password is not None:
            pulumi.set(__self__, "password", password)
        if password_recipe is not None:
            pulumi.set(__self__, "password_recipe", password_recipe)
        if password_wo is not None:
            pulumi.set(__self__, "password_wo", password_wo)
        if password_wo_version is not None:
            pulumi.set(__self__, "password_wo_version", password_wo_version)
        if port is not None:
            pulumi.set(__self__, "port", port)
        if section_map is not None:
            pulumi.set(__self__, "section_map", section_map)
        if sections is not None:
            pulumi.set(__self__, "sections", sections)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if title is not None:
            pulumi.set(__self__, "title", title)
        if type is not None:
            pulumi.set(__self__, "type", type)
        if url is not None:
            pulumi.set(__self__, "url", url)
        if username is not None:
            pulumi.set(__self__, "username", username)
        if uuid is not None:
            pulumi.set(__self__, "uuid", uuid)
        if vault is not None:
            pulumi.set(__self__, "vault", vault)

    @_builtins.property
    @pulumi.getter
    def category(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The category of the item. One of ["login" "password" "database" "secure_note"]
        """
        return pulumi.get(self, "category")

    @category.setter
    def category(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "category", value)

    @_builtins.property
    @pulumi.getter
    def database(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        (Only applies to the database category) The name of the database.
        """
        return pulumi.get(self, "database")

    @database.setter
    def database(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "database", value)

    @_builtins.property
    @pulumi.getter
    def hostname(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        (Only applies to the database category) The address where the database can be found
        """
        return pulumi.get(self, "hostname")

    @hostname.setter
    def hostname(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "hostname", value)

    @_builtins.property
    @pulumi.getter(name="noteValue")
    def note_value(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Secure Note value.
        """
        return pulumi.get(self, "note_value")

    @note_value.setter
    def note_value(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "note_value", value)

    @_builtins.property
    @pulumi.getter(name="noteValueWo")
    def note_value_wo(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        A write-only secure note value for this item. This value is not stored in the state and is intended for use with ephemeral values. **Note**: Write-only arguments require Terraform 1.11 or later.
        """
        return pulumi.get(self, "note_value_wo")

    @note_value_wo.setter
    def note_value_wo(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "note_value_wo", value)

    @_builtins.property
    @pulumi.getter(name="noteValueWoVersion")
    def note_value_wo_version(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        An integer that must be incremented to trigger an update to the 'note_value_wo' field.
        """
        return pulumi.get(self, "note_value_wo_version")

    @note_value_wo_version.setter
    def note_value_wo_version(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "note_value_wo_version", value)

    @_builtins.property
    @pulumi.getter
    def password(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Password for this item.
        """
        return pulumi.get(self, "password")

    @password.setter
    def password(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "password", value)

    @_builtins.property
    @pulumi.getter(name="passwordRecipe")
    def password_recipe(self) -> Optional[pulumi.Input['ItemPasswordRecipeArgs']]:
        """
        The recipe used to generate a new value for a password.
        """
        return pulumi.get(self, "password_recipe")

    @password_recipe.setter
    def password_recipe(self, value: Optional[pulumi.Input['ItemPasswordRecipeArgs']]):
        pulumi.set(self, "password_recipe", value)

    @_builtins.property
    @pulumi.getter(name="passwordWo")
    def password_wo(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        A write-only password for this item. This value is not stored in the state and is intended for use with ephemeral values. **Note**: Write-only arguments require Terraform 1.11 or later.
        """
        return pulumi.get(self, "password_wo")

    @password_wo.setter
    def password_wo(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "password_wo", value)

    @_builtins.property
    @pulumi.getter(name="passwordWoVersion")
    def password_wo_version(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        An integer that must be incremented to trigger an update to the 'password_wo' field.
        """
        return pulumi.get(self, "password_wo_version")

    @password_wo_version.setter
    def password_wo_version(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "password_wo_version", value)

    @_builtins.property
    @pulumi.getter
    def port(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        (Only applies to the database category) The port the database is listening on.
        """
        return pulumi.get(self, "port")

    @port.setter
    def port(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "port", value)

    @_builtins.property
    @pulumi.getter(name="sectionMap")
    def section_map(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input['ItemSectionMapArgs']]]]:
        """
        A map of custom sections in an item, keyed by section label. This allows direct lookup of sections and their fields by label. Cannot be used together with `section`. Use either `section` (list) or `section_map` (map), but not both.
        """
        return pulumi.get(self, "section_map")

    @section_map.setter
    def section_map(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input['ItemSectionMapArgs']]]]):
        pulumi.set(self, "section_map", value)

    @_builtins.property
    @pulumi.getter
    def sections(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['ItemSectionArgs']]]]:
        """
        A list of custom sections in an item. Cannot be used together with `section_map`. Use either `section` (list) or `section_map` (map), but not both.
        """
        return pulumi.get(self, "sections")

    @sections.setter
    def sections(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['ItemSectionArgs']]]]):
        pulumi.set(self, "sections", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        An array of strings of the tags assigned to the item.
        """
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter
    def title(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The title of the item.
        """
        return pulumi.get(self, "title")

    @title.setter
    def title(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "title", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        (Only applies to the database category) The type of database. One of ["db2" "filemaker" "msaccess" "mssql" "mysql" "oracle" "postgresql" "sqlite" "other"]
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "type", value)

    @_builtins.property
    @pulumi.getter
    def url(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The primary URL for the item.
        """
        return pulumi.get(self, "url")

    @url.setter
    def url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "url", value)

    @_builtins.property
    @pulumi.getter
    def username(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Username for this item.
        """
        return pulumi.get(self, "username")

    @username.setter
    def username(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "username", value)

    @_builtins.property
    @pulumi.getter
    def uuid(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The UUID of the item. Item identifiers are unique within a specific vault.
        """
        return pulumi.get(self, "uuid")

    @uuid.setter
    def uuid(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "uuid", value)

    @_builtins.property
    @pulumi.getter
    def vault(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The UUID of the vault the item is in.
        """
        return pulumi.get(self, "vault")

    @vault.setter
    def vault(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "vault", value)


@pulumi.type_token("onepassword:index/item:Item")
class Item(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 category: Optional[pulumi.Input[_builtins.str]] = None,
                 database: Optional[pulumi.Input[_builtins.str]] = None,
                 hostname: Optional[pulumi.Input[_builtins.str]] = None,
                 note_value: Optional[pulumi.Input[_builtins.str]] = None,
                 note_value_wo: Optional[pulumi.Input[_builtins.str]] = None,
                 note_value_wo_version: Optional[pulumi.Input[_builtins.int]] = None,
                 password: Optional[pulumi.Input[_builtins.str]] = None,
                 password_recipe: Optional[pulumi.Input[Union['ItemPasswordRecipeArgs', 'ItemPasswordRecipeArgsDict']]] = None,
                 password_wo: Optional[pulumi.Input[_builtins.str]] = None,
                 password_wo_version: Optional[pulumi.Input[_builtins.int]] = None,
                 port: Optional[pulumi.Input[_builtins.str]] = None,
                 section_map: Optional[pulumi.Input[Mapping[str, pulumi.Input[Union['ItemSectionMapArgs', 'ItemSectionMapArgsDict']]]]] = None,
                 sections: Optional[pulumi.Input[Sequence[pulumi.Input[Union['ItemSectionArgs', 'ItemSectionArgsDict']]]]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 title: Optional[pulumi.Input[_builtins.str]] = None,
                 type: Optional[pulumi.Input[_builtins.str]] = None,
                 url: Optional[pulumi.Input[_builtins.str]] = None,
                 username: Optional[pulumi.Input[_builtins.str]] = None,
                 vault: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        A 1Password Item.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_onepassword as onepassword

        # Example using section_map (map-based sections for direct field access)
        example_with_map = onepassword.Item("example_with_map",
            vault="your-vault-id",
            title="Example Item with Section Map",
            category="login",
            section_map={
                "credentials": {
                    "field_map": {
                        "api_key": {
                            "type": "CONCEALED",
                            "value": "my-secret-api-key",
                        },
                        "api_endpoint": {
                            "type": "URL",
                            "value": "https://api.example.com",
                        },
                    },
                },
                "metadata": {
                    "field_map": {
                        "environment": {
                            "type": "STRING",
                            "value": "production",
                        },
                        "created_by": {
                            "type": "STRING",
                            "value": "terraform",
                        },
                    },
                },
            })
        # Example using section (list-based sections)
        example_with_list = onepassword.Item("example_with_list",
            vault="your-vault-id",
            title="Example Item with Section List",
            category="login",
            password_recipe={
                "length": 40,
                "symbols": False,
            },
            sections=[{
                "label": "Example section",
                "fields": [{
                    "label": "Example field",
                    "type": "DATE",
                    "value": "2024-01-31",
                }],
            }])
        ```

        ## Import

        The `pulumi import` command can be used, for example:

        ```sh
        # import an existing 1Password item
        terraform import onepassword_item.myitem vaults/<vault uuid>/items/<item uuid>
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] category: The category of the item. One of ["login" "password" "database" "secure_note"]
        :param pulumi.Input[_builtins.str] database: (Only applies to the database category) The name of the database.
        :param pulumi.Input[_builtins.str] hostname: (Only applies to the database category) The address where the database can be found
        :param pulumi.Input[_builtins.str] note_value: Secure Note value.
        :param pulumi.Input[_builtins.str] note_value_wo: **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
               A write-only secure note value for this item. This value is not stored in the state and is intended for use with ephemeral values. **Note**: Write-only arguments require Terraform 1.11 or later.
        :param pulumi.Input[_builtins.int] note_value_wo_version: An integer that must be incremented to trigger an update to the 'note_value_wo' field.
        :param pulumi.Input[_builtins.str] password: Password for this item.
        :param pulumi.Input[Union['ItemPasswordRecipeArgs', 'ItemPasswordRecipeArgsDict']] password_recipe: The recipe used to generate a new value for a password.
        :param pulumi.Input[_builtins.str] password_wo: **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
               A write-only password for this item. This value is not stored in the state and is intended for use with ephemeral values. **Note**: Write-only arguments require Terraform 1.11 or later.
        :param pulumi.Input[_builtins.int] password_wo_version: An integer that must be incremented to trigger an update to the 'password_wo' field.
        :param pulumi.Input[_builtins.str] port: (Only applies to the database category) The port the database is listening on.
        :param pulumi.Input[Mapping[str, pulumi.Input[Union['ItemSectionMapArgs', 'ItemSectionMapArgsDict']]]] section_map: A map of custom sections in an item, keyed by section label. This allows direct lookup of sections and their fields by label. Cannot be used together with `section`. Use either `section` (list) or `section_map` (map), but not both.
        :param pulumi.Input[Sequence[pulumi.Input[Union['ItemSectionArgs', 'ItemSectionArgsDict']]]] sections: A list of custom sections in an item. Cannot be used together with `section_map`. Use either `section` (list) or `section_map` (map), but not both.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tags: An array of strings of the tags assigned to the item.
        :param pulumi.Input[_builtins.str] title: The title of the item.
        :param pulumi.Input[_builtins.str] type: (Only applies to the database category) The type of database. One of ["db2" "filemaker" "msaccess" "mssql" "mysql" "oracle" "postgresql" "sqlite" "other"]
        :param pulumi.Input[_builtins.str] url: The primary URL for the item.
        :param pulumi.Input[_builtins.str] username: Username for this item.
        :param pulumi.Input[_builtins.str] vault: The UUID of the vault the item is in.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ItemArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        A 1Password Item.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_onepassword as onepassword

        # Example using section_map (map-based sections for direct field access)
        example_with_map = onepassword.Item("example_with_map",
            vault="your-vault-id",
            title="Example Item with Section Map",
            category="login",
            section_map={
                "credentials": {
                    "field_map": {
                        "api_key": {
                            "type": "CONCEALED",
                            "value": "my-secret-api-key",
                        },
                        "api_endpoint": {
                            "type": "URL",
                            "value": "https://api.example.com",
                        },
                    },
                },
                "metadata": {
                    "field_map": {
                        "environment": {
                            "type": "STRING",
                            "value": "production",
                        },
                        "created_by": {
                            "type": "STRING",
                            "value": "terraform",
                        },
                    },
                },
            })
        # Example using section (list-based sections)
        example_with_list = onepassword.Item("example_with_list",
            vault="your-vault-id",
            title="Example Item with Section List",
            category="login",
            password_recipe={
                "length": 40,
                "symbols": False,
            },
            sections=[{
                "label": "Example section",
                "fields": [{
                    "label": "Example field",
                    "type": "DATE",
                    "value": "2024-01-31",
                }],
            }])
        ```

        ## Import

        The `pulumi import` command can be used, for example:

        ```sh
        # import an existing 1Password item
        terraform import onepassword_item.myitem vaults/<vault uuid>/items/<item uuid>
        ```


        :param str resource_name: The name of the resource.
        :param ItemArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ItemArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 category: Optional[pulumi.Input[_builtins.str]] = None,
                 database: Optional[pulumi.Input[_builtins.str]] = None,
                 hostname: Optional[pulumi.Input[_builtins.str]] = None,
                 note_value: Optional[pulumi.Input[_builtins.str]] = None,
                 note_value_wo: Optional[pulumi.Input[_builtins.str]] = None,
                 note_value_wo_version: Optional[pulumi.Input[_builtins.int]] = None,
                 password: Optional[pulumi.Input[_builtins.str]] = None,
                 password_recipe: Optional[pulumi.Input[Union['ItemPasswordRecipeArgs', 'ItemPasswordRecipeArgsDict']]] = None,
                 password_wo: Optional[pulumi.Input[_builtins.str]] = None,
                 password_wo_version: Optional[pulumi.Input[_builtins.int]] = None,
                 port: Optional[pulumi.Input[_builtins.str]] = None,
                 section_map: Optional[pulumi.Input[Mapping[str, pulumi.Input[Union['ItemSectionMapArgs', 'ItemSectionMapArgsDict']]]]] = None,
                 sections: Optional[pulumi.Input[Sequence[pulumi.Input[Union['ItemSectionArgs', 'ItemSectionArgsDict']]]]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 title: Optional[pulumi.Input[_builtins.str]] = None,
                 type: Optional[pulumi.Input[_builtins.str]] = None,
                 url: Optional[pulumi.Input[_builtins.str]] = None,
                 username: Optional[pulumi.Input[_builtins.str]] = None,
                 vault: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ItemArgs.__new__(ItemArgs)

            __props__.__dict__["category"] = category
            __props__.__dict__["database"] = database
            __props__.__dict__["hostname"] = hostname
            __props__.__dict__["note_value"] = None if note_value is None else pulumi.Output.secret(note_value)
            __props__.__dict__["note_value_wo"] = None if note_value_wo is None else pulumi.Output.secret(note_value_wo)
            __props__.__dict__["note_value_wo_version"] = note_value_wo_version
            __props__.__dict__["password"] = None if password is None else pulumi.Output.secret(password)
            __props__.__dict__["password_recipe"] = password_recipe
            __props__.__dict__["password_wo"] = None if password_wo is None else pulumi.Output.secret(password_wo)
            __props__.__dict__["password_wo_version"] = password_wo_version
            __props__.__dict__["port"] = port
            __props__.__dict__["section_map"] = section_map
            __props__.__dict__["sections"] = sections
            __props__.__dict__["tags"] = tags
            __props__.__dict__["title"] = title
            __props__.__dict__["type"] = type
            __props__.__dict__["url"] = url
            __props__.__dict__["username"] = username
            if vault is None and not opts.urn:
                raise TypeError("Missing required property 'vault'")
            __props__.__dict__["vault"] = vault
            __props__.__dict__["uuid"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["noteValue", "noteValueWo", "password", "passwordWo"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(Item, __self__).__init__(
            'onepassword:index/item:Item',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            category: Optional[pulumi.Input[_builtins.str]] = None,
            database: Optional[pulumi.Input[_builtins.str]] = None,
            hostname: Optional[pulumi.Input[_builtins.str]] = None,
            note_value: Optional[pulumi.Input[_builtins.str]] = None,
            note_value_wo: Optional[pulumi.Input[_builtins.str]] = None,
            note_value_wo_version: Optional[pulumi.Input[_builtins.int]] = None,
            password: Optional[pulumi.Input[_builtins.str]] = None,
            password_recipe: Optional[pulumi.Input[Union['ItemPasswordRecipeArgs', 'ItemPasswordRecipeArgsDict']]] = None,
            password_wo: Optional[pulumi.Input[_builtins.str]] = None,
            password_wo_version: Optional[pulumi.Input[_builtins.int]] = None,
            port: Optional[pulumi.Input[_builtins.str]] = None,
            section_map: Optional[pulumi.Input[Mapping[str, pulumi.Input[Union['ItemSectionMapArgs', 'ItemSectionMapArgsDict']]]]] = None,
            sections: Optional[pulumi.Input[Sequence[pulumi.Input[Union['ItemSectionArgs', 'ItemSectionArgsDict']]]]] = None,
            tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            title: Optional[pulumi.Input[_builtins.str]] = None,
            type: Optional[pulumi.Input[_builtins.str]] = None,
            url: Optional[pulumi.Input[_builtins.str]] = None,
            username: Optional[pulumi.Input[_builtins.str]] = None,
            uuid: Optional[pulumi.Input[_builtins.str]] = None,
            vault: Optional[pulumi.Input[_builtins.str]] = None) -> 'Item':
        """
        Get an existing Item resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] category: The category of the item. One of ["login" "password" "database" "secure_note"]
        :param pulumi.Input[_builtins.str] database: (Only applies to the database category) The name of the database.
        :param pulumi.Input[_builtins.str] hostname: (Only applies to the database category) The address where the database can be found
        :param pulumi.Input[_builtins.str] note_value: Secure Note value.
        :param pulumi.Input[_builtins.str] note_value_wo: **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
               A write-only secure note value for this item. This value is not stored in the state and is intended for use with ephemeral values. **Note**: Write-only arguments require Terraform 1.11 or later.
        :param pulumi.Input[_builtins.int] note_value_wo_version: An integer that must be incremented to trigger an update to the 'note_value_wo' field.
        :param pulumi.Input[_builtins.str] password: Password for this item.
        :param pulumi.Input[Union['ItemPasswordRecipeArgs', 'ItemPasswordRecipeArgsDict']] password_recipe: The recipe used to generate a new value for a password.
        :param pulumi.Input[_builtins.str] password_wo: **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
               A write-only password for this item. This value is not stored in the state and is intended for use with ephemeral values. **Note**: Write-only arguments require Terraform 1.11 or later.
        :param pulumi.Input[_builtins.int] password_wo_version: An integer that must be incremented to trigger an update to the 'password_wo' field.
        :param pulumi.Input[_builtins.str] port: (Only applies to the database category) The port the database is listening on.
        :param pulumi.Input[Mapping[str, pulumi.Input[Union['ItemSectionMapArgs', 'ItemSectionMapArgsDict']]]] section_map: A map of custom sections in an item, keyed by section label. This allows direct lookup of sections and their fields by label. Cannot be used together with `section`. Use either `section` (list) or `section_map` (map), but not both.
        :param pulumi.Input[Sequence[pulumi.Input[Union['ItemSectionArgs', 'ItemSectionArgsDict']]]] sections: A list of custom sections in an item. Cannot be used together with `section_map`. Use either `section` (list) or `section_map` (map), but not both.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tags: An array of strings of the tags assigned to the item.
        :param pulumi.Input[_builtins.str] title: The title of the item.
        :param pulumi.Input[_builtins.str] type: (Only applies to the database category) The type of database. One of ["db2" "filemaker" "msaccess" "mssql" "mysql" "oracle" "postgresql" "sqlite" "other"]
        :param pulumi.Input[_builtins.str] url: The primary URL for the item.
        :param pulumi.Input[_builtins.str] username: Username for this item.
        :param pulumi.Input[_builtins.str] uuid: The UUID of the item. Item identifiers are unique within a specific vault.
        :param pulumi.Input[_builtins.str] vault: The UUID of the vault the item is in.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ItemState.__new__(_ItemState)

        __props__.__dict__["category"] = category
        __props__.__dict__["database"] = database
        __props__.__dict__["hostname"] = hostname
        __props__.__dict__["note_value"] = note_value
        __props__.__dict__["note_value_wo"] = note_value_wo
        __props__.__dict__["note_value_wo_version"] = note_value_wo_version
        __props__.__dict__["password"] = password
        __props__.__dict__["password_recipe"] = password_recipe
        __props__.__dict__["password_wo"] = password_wo
        __props__.__dict__["password_wo_version"] = password_wo_version
        __props__.__dict__["port"] = port
        __props__.__dict__["section_map"] = section_map
        __props__.__dict__["sections"] = sections
        __props__.__dict__["tags"] = tags
        __props__.__dict__["title"] = title
        __props__.__dict__["type"] = type
        __props__.__dict__["url"] = url
        __props__.__dict__["username"] = username
        __props__.__dict__["uuid"] = uuid
        __props__.__dict__["vault"] = vault
        return Item(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def category(self) -> pulumi.Output[_builtins.str]:
        """
        The category of the item. One of ["login" "password" "database" "secure_note"]
        """
        return pulumi.get(self, "category")

    @_builtins.property
    @pulumi.getter
    def database(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        (Only applies to the database category) The name of the database.
        """
        return pulumi.get(self, "database")

    @_builtins.property
    @pulumi.getter
    def hostname(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        (Only applies to the database category) The address where the database can be found
        """
        return pulumi.get(self, "hostname")

    @_builtins.property
    @pulumi.getter(name="noteValue")
    def note_value(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Secure Note value.
        """
        return pulumi.get(self, "note_value")

    @_builtins.property
    @pulumi.getter(name="noteValueWo")
    def note_value_wo(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        A write-only secure note value for this item. This value is not stored in the state and is intended for use with ephemeral values. **Note**: Write-only arguments require Terraform 1.11 or later.
        """
        return pulumi.get(self, "note_value_wo")

    @_builtins.property
    @pulumi.getter(name="noteValueWoVersion")
    def note_value_wo_version(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        An integer that must be incremented to trigger an update to the 'note_value_wo' field.
        """
        return pulumi.get(self, "note_value_wo_version")

    @_builtins.property
    @pulumi.getter
    def password(self) -> pulumi.Output[_builtins.str]:
        """
        Password for this item.
        """
        return pulumi.get(self, "password")

    @_builtins.property
    @pulumi.getter(name="passwordRecipe")
    def password_recipe(self) -> pulumi.Output[Optional['outputs.ItemPasswordRecipe']]:
        """
        The recipe used to generate a new value for a password.
        """
        return pulumi.get(self, "password_recipe")

    @_builtins.property
    @pulumi.getter(name="passwordWo")
    def password_wo(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        A write-only password for this item. This value is not stored in the state and is intended for use with ephemeral values. **Note**: Write-only arguments require Terraform 1.11 or later.
        """
        return pulumi.get(self, "password_wo")

    @_builtins.property
    @pulumi.getter(name="passwordWoVersion")
    def password_wo_version(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        An integer that must be incremented to trigger an update to the 'password_wo' field.
        """
        return pulumi.get(self, "password_wo_version")

    @_builtins.property
    @pulumi.getter
    def port(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        (Only applies to the database category) The port the database is listening on.
        """
        return pulumi.get(self, "port")

    @_builtins.property
    @pulumi.getter(name="sectionMap")
    def section_map(self) -> pulumi.Output[Optional[Mapping[str, 'outputs.ItemSectionMap']]]:
        """
        A map of custom sections in an item, keyed by section label. This allows direct lookup of sections and their fields by label. Cannot be used together with `section`. Use either `section` (list) or `section_map` (map), but not both.
        """
        return pulumi.get(self, "section_map")

    @_builtins.property
    @pulumi.getter
    def sections(self) -> pulumi.Output[Optional[Sequence['outputs.ItemSection']]]:
        """
        A list of custom sections in an item. Cannot be used together with `section_map`. Use either `section` (list) or `section_map` (map), but not both.
        """
        return pulumi.get(self, "sections")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        An array of strings of the tags assigned to the item.
        """
        return pulumi.get(self, "tags")

    @_builtins.property
    @pulumi.getter
    def title(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The title of the item.
        """
        return pulumi.get(self, "title")

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        (Only applies to the database category) The type of database. One of ["db2" "filemaker" "msaccess" "mssql" "mysql" "oracle" "postgresql" "sqlite" "other"]
        """
        return pulumi.get(self, "type")

    @_builtins.property
    @pulumi.getter
    def url(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The primary URL for the item.
        """
        return pulumi.get(self, "url")

    @_builtins.property
    @pulumi.getter
    def username(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Username for this item.
        """
        return pulumi.get(self, "username")

    @_builtins.property
    @pulumi.getter
    def uuid(self) -> pulumi.Output[_builtins.str]:
        """
        The UUID of the item. Item identifiers are unique within a specific vault.
        """
        return pulumi.get(self, "uuid")

    @_builtins.property
    @pulumi.getter
    def vault(self) -> pulumi.Output[_builtins.str]:
        """
        The UUID of the vault the item is in.
        """
        return pulumi.get(self, "vault")

