# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'ItemPasswordRecipe',
    'ItemSection',
    'ItemSectionField',
    'ItemSectionFieldPasswordRecipe',
    'ItemSectionMap',
    'ItemSectionMapFieldMap',
    'ItemSectionMapFieldMapPasswordRecipe',
    'GetEnvironmentMetadataResult',
    'GetItemFileResult',
    'GetItemSectionResult',
    'GetItemSectionFieldResult',
    'GetItemSectionFileResult',
    'GetItemSectionMapResult',
    'GetItemSectionMapFieldMapResult',
    'GetItemSectionMapFileMapResult',
]

@pulumi.output_type
class ItemPasswordRecipe(dict):
    def __init__(__self__, *,
                 digits: Optional[_builtins.bool] = None,
                 length: Optional[_builtins.int] = None,
                 symbols: Optional[_builtins.bool] = None):
        """
        :param _builtins.bool digits: Use digits [0-9] when generating the password.
        :param _builtins.int length: The length of the password to be generated.
        :param _builtins.bool symbols: Use symbols [!@.-_*] when generating the password.
        """
        if digits is not None:
            pulumi.set(__self__, "digits", digits)
        if length is not None:
            pulumi.set(__self__, "length", length)
        if symbols is not None:
            pulumi.set(__self__, "symbols", symbols)

    @_builtins.property
    @pulumi.getter
    def digits(self) -> Optional[_builtins.bool]:
        """
        Use digits [0-9] when generating the password.
        """
        return pulumi.get(self, "digits")

    @_builtins.property
    @pulumi.getter
    def length(self) -> Optional[_builtins.int]:
        """
        The length of the password to be generated.
        """
        return pulumi.get(self, "length")

    @_builtins.property
    @pulumi.getter
    def symbols(self) -> Optional[_builtins.bool]:
        """
        Use symbols [!@.-_*] when generating the password.
        """
        return pulumi.get(self, "symbols")


@pulumi.output_type
class ItemSection(dict):
    def __init__(__self__, *,
                 label: _builtins.str,
                 fields: Optional[Sequence['outputs.ItemSectionField']] = None,
                 id: Optional[_builtins.str] = None):
        """
        :param _builtins.str label: The label for the section.
        :param Sequence['ItemSectionFieldArgs'] fields: A list of custom fields in the section
        :param _builtins.str id: A unique identifier for the section.
        """
        pulumi.set(__self__, "label", label)
        if fields is not None:
            pulumi.set(__self__, "fields", fields)
        if id is not None:
            pulumi.set(__self__, "id", id)

    @_builtins.property
    @pulumi.getter
    def label(self) -> _builtins.str:
        """
        The label for the section.
        """
        return pulumi.get(self, "label")

    @_builtins.property
    @pulumi.getter
    def fields(self) -> Optional[Sequence['outputs.ItemSectionField']]:
        """
        A list of custom fields in the section
        """
        return pulumi.get(self, "fields")

    @_builtins.property
    @pulumi.getter
    def id(self) -> Optional[_builtins.str]:
        """
        A unique identifier for the section.
        """
        return pulumi.get(self, "id")


@pulumi.output_type
class ItemSectionField(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "passwordRecipe":
            suggest = "password_recipe"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in ItemSectionField. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        ItemSectionField.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        ItemSectionField.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 label: _builtins.str,
                 id: Optional[_builtins.str] = None,
                 password_recipe: Optional['outputs.ItemSectionFieldPasswordRecipe'] = None,
                 type: Optional[_builtins.str] = None,
                 value: Optional[_builtins.str] = None):
        """
        :param _builtins.str label: The label for the field.
        :param _builtins.str id: A unique identifier for the field.
        :param 'ItemSectionFieldPasswordRecipeArgs' password_recipe: The recipe used to generate a new value for a password.
        :param _builtins.str type: The type of value stored in the field. One of ["STRING" "CONCEALED" "EMAIL" "URL" "OTP" "DATE" "MONTH_YEAR" "MENU"]
        :param _builtins.str value: The value of the field.
        """
        pulumi.set(__self__, "label", label)
        if id is not None:
            pulumi.set(__self__, "id", id)
        if password_recipe is not None:
            pulumi.set(__self__, "password_recipe", password_recipe)
        if type is not None:
            pulumi.set(__self__, "type", type)
        if value is not None:
            pulumi.set(__self__, "value", value)

    @_builtins.property
    @pulumi.getter
    def label(self) -> _builtins.str:
        """
        The label for the field.
        """
        return pulumi.get(self, "label")

    @_builtins.property
    @pulumi.getter
    def id(self) -> Optional[_builtins.str]:
        """
        A unique identifier for the field.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="passwordRecipe")
    def password_recipe(self) -> Optional['outputs.ItemSectionFieldPasswordRecipe']:
        """
        The recipe used to generate a new value for a password.
        """
        return pulumi.get(self, "password_recipe")

    @_builtins.property
    @pulumi.getter
    def type(self) -> Optional[_builtins.str]:
        """
        The type of value stored in the field. One of ["STRING" "CONCEALED" "EMAIL" "URL" "OTP" "DATE" "MONTH_YEAR" "MENU"]
        """
        return pulumi.get(self, "type")

    @_builtins.property
    @pulumi.getter
    def value(self) -> Optional[_builtins.str]:
        """
        The value of the field.
        """
        return pulumi.get(self, "value")


@pulumi.output_type
class ItemSectionFieldPasswordRecipe(dict):
    def __init__(__self__, *,
                 digits: Optional[_builtins.bool] = None,
                 length: Optional[_builtins.int] = None,
                 symbols: Optional[_builtins.bool] = None):
        """
        :param _builtins.bool digits: Use digits [0-9] when generating the password.
        :param _builtins.int length: The length of the password to be generated.
        :param _builtins.bool symbols: Use symbols [!@.-_*] when generating the password.
        """
        if digits is not None:
            pulumi.set(__self__, "digits", digits)
        if length is not None:
            pulumi.set(__self__, "length", length)
        if symbols is not None:
            pulumi.set(__self__, "symbols", symbols)

    @_builtins.property
    @pulumi.getter
    def digits(self) -> Optional[_builtins.bool]:
        """
        Use digits [0-9] when generating the password.
        """
        return pulumi.get(self, "digits")

    @_builtins.property
    @pulumi.getter
    def length(self) -> Optional[_builtins.int]:
        """
        The length of the password to be generated.
        """
        return pulumi.get(self, "length")

    @_builtins.property
    @pulumi.getter
    def symbols(self) -> Optional[_builtins.bool]:
        """
        Use symbols [!@.-_*] when generating the password.
        """
        return pulumi.get(self, "symbols")


@pulumi.output_type
class ItemSectionMap(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "fieldMap":
            suggest = "field_map"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in ItemSectionMap. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        ItemSectionMap.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        ItemSectionMap.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 field_map: Optional[Mapping[str, 'outputs.ItemSectionMapFieldMap']] = None,
                 id: Optional[_builtins.str] = None):
        """
        :param Mapping[str, 'ItemSectionMapFieldMapArgs'] field_map: A map of custom fields in the section, keyed by field label.
        :param _builtins.str id: A unique identifier for the section.
        """
        if field_map is not None:
            pulumi.set(__self__, "field_map", field_map)
        if id is not None:
            pulumi.set(__self__, "id", id)

    @_builtins.property
    @pulumi.getter(name="fieldMap")
    def field_map(self) -> Optional[Mapping[str, 'outputs.ItemSectionMapFieldMap']]:
        """
        A map of custom fields in the section, keyed by field label.
        """
        return pulumi.get(self, "field_map")

    @_builtins.property
    @pulumi.getter
    def id(self) -> Optional[_builtins.str]:
        """
        A unique identifier for the section.
        """
        return pulumi.get(self, "id")


@pulumi.output_type
class ItemSectionMapFieldMap(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "passwordRecipe":
            suggest = "password_recipe"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in ItemSectionMapFieldMap. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        ItemSectionMapFieldMap.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        ItemSectionMapFieldMap.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 id: Optional[_builtins.str] = None,
                 password_recipe: Optional['outputs.ItemSectionMapFieldMapPasswordRecipe'] = None,
                 type: Optional[_builtins.str] = None,
                 value: Optional[_builtins.str] = None):
        """
        :param _builtins.str id: A unique identifier for the field.
        :param 'ItemSectionMapFieldMapPasswordRecipeArgs' password_recipe: The recipe used to generate a new value for a password.
        :param _builtins.str type: The type of value stored in the field. One of ["STRING" "CONCEALED" "EMAIL" "URL" "OTP" "DATE" "MONTH_YEAR" "MENU"]
        :param _builtins.str value: The value of the field.
        """
        if id is not None:
            pulumi.set(__self__, "id", id)
        if password_recipe is not None:
            pulumi.set(__self__, "password_recipe", password_recipe)
        if type is not None:
            pulumi.set(__self__, "type", type)
        if value is not None:
            pulumi.set(__self__, "value", value)

    @_builtins.property
    @pulumi.getter
    def id(self) -> Optional[_builtins.str]:
        """
        A unique identifier for the field.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="passwordRecipe")
    def password_recipe(self) -> Optional['outputs.ItemSectionMapFieldMapPasswordRecipe']:
        """
        The recipe used to generate a new value for a password.
        """
        return pulumi.get(self, "password_recipe")

    @_builtins.property
    @pulumi.getter
    def type(self) -> Optional[_builtins.str]:
        """
        The type of value stored in the field. One of ["STRING" "CONCEALED" "EMAIL" "URL" "OTP" "DATE" "MONTH_YEAR" "MENU"]
        """
        return pulumi.get(self, "type")

    @_builtins.property
    @pulumi.getter
    def value(self) -> Optional[_builtins.str]:
        """
        The value of the field.
        """
        return pulumi.get(self, "value")


@pulumi.output_type
class ItemSectionMapFieldMapPasswordRecipe(dict):
    def __init__(__self__, *,
                 digits: Optional[_builtins.bool] = None,
                 length: Optional[_builtins.int] = None,
                 symbols: Optional[_builtins.bool] = None):
        """
        :param _builtins.bool digits: Use digits [0-9] when generating the password.
        :param _builtins.int length: The length of the password to be generated.
        :param _builtins.bool symbols: Use symbols [!@.-_*] when generating the password.
        """
        if digits is not None:
            pulumi.set(__self__, "digits", digits)
        if length is not None:
            pulumi.set(__self__, "length", length)
        if symbols is not None:
            pulumi.set(__self__, "symbols", symbols)

    @_builtins.property
    @pulumi.getter
    def digits(self) -> Optional[_builtins.bool]:
        """
        Use digits [0-9] when generating the password.
        """
        return pulumi.get(self, "digits")

    @_builtins.property
    @pulumi.getter
    def length(self) -> Optional[_builtins.int]:
        """
        The length of the password to be generated.
        """
        return pulumi.get(self, "length")

    @_builtins.property
    @pulumi.getter
    def symbols(self) -> Optional[_builtins.bool]:
        """
        Use symbols [!@.-_*] when generating the password.
        """
        return pulumi.get(self, "symbols")


@pulumi.output_type
class GetEnvironmentMetadataResult(dict):
    def __init__(__self__, *,
                 masked: _builtins.bool,
                 name: _builtins.str,
                 value: _builtins.str):
        """
        :param _builtins.bool masked: Whether the value is hidden by default in the 1Password app.
        :param _builtins.str name: The environment variable name.
        :param _builtins.str value: The environment variable value.
        """
        pulumi.set(__self__, "masked", masked)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "value", value)

    @_builtins.property
    @pulumi.getter
    def masked(self) -> _builtins.bool:
        """
        Whether the value is hidden by default in the 1Password app.
        """
        return pulumi.get(self, "masked")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        The environment variable name.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def value(self) -> _builtins.str:
        """
        The environment variable value.
        """
        return pulumi.get(self, "value")


@pulumi.output_type
class GetItemFileResult(dict):
    def __init__(__self__, *,
                 content: _builtins.str,
                 content_base64: _builtins.str,
                 id: _builtins.str,
                 name: _builtins.str):
        """
        :param _builtins.str content: The content of the file.
        :param _builtins.str content_base64: The content of the file in base64 encoding. (Use this for binary files.)
        :param _builtins.str id: The UUID of the file.
        :param _builtins.str name: The name of the file.
        """
        pulumi.set(__self__, "content", content)
        pulumi.set(__self__, "content_base64", content_base64)
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "name", name)

    @_builtins.property
    @pulumi.getter
    def content(self) -> _builtins.str:
        """
        The content of the file.
        """
        return pulumi.get(self, "content")

    @_builtins.property
    @pulumi.getter(name="contentBase64")
    def content_base64(self) -> _builtins.str:
        """
        The content of the file in base64 encoding. (Use this for binary files.)
        """
        return pulumi.get(self, "content_base64")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The UUID of the file.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        The name of the file.
        """
        return pulumi.get(self, "name")


@pulumi.output_type
class GetItemSectionResult(dict):
    def __init__(__self__, *,
                 id: _builtins.str,
                 label: _builtins.str,
                 fields: Optional[Sequence['outputs.GetItemSectionFieldResult']] = None,
                 files: Optional[Sequence['outputs.GetItemSectionFileResult']] = None):
        """
        :param _builtins.str id: A unique identifier for the section.
        :param _builtins.str label: The label for the section.
        :param Sequence['GetItemSectionFieldArgs'] fields: A list of custom fields in the section
        :param Sequence['GetItemSectionFileArgs'] files: A list of files attached to the section.
        """
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "label", label)
        if fields is not None:
            pulumi.set(__self__, "fields", fields)
        if files is not None:
            pulumi.set(__self__, "files", files)

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        A unique identifier for the section.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def label(self) -> _builtins.str:
        """
        The label for the section.
        """
        return pulumi.get(self, "label")

    @_builtins.property
    @pulumi.getter
    def fields(self) -> Optional[Sequence['outputs.GetItemSectionFieldResult']]:
        """
        A list of custom fields in the section
        """
        return pulumi.get(self, "fields")

    @_builtins.property
    @pulumi.getter
    def files(self) -> Optional[Sequence['outputs.GetItemSectionFileResult']]:
        """
        A list of files attached to the section.
        """
        return pulumi.get(self, "files")


@pulumi.output_type
class GetItemSectionFieldResult(dict):
    def __init__(__self__, *,
                 id: _builtins.str,
                 label: _builtins.str,
                 type: _builtins.str,
                 value: _builtins.str):
        """
        :param _builtins.str id: A unique identifier for the field.
        :param _builtins.str label: The label for the field.
        :param _builtins.str type: The type of value stored in the field. One of ["STRING" "CONCEALED" "EMAIL" "URL" "OTP" "DATE" "MONTH_YEAR" "MENU"]
        :param _builtins.str value: The value of the field.
        """
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "label", label)
        pulumi.set(__self__, "type", type)
        pulumi.set(__self__, "value", value)

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        A unique identifier for the field.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def label(self) -> _builtins.str:
        """
        The label for the field.
        """
        return pulumi.get(self, "label")

    @_builtins.property
    @pulumi.getter
    def type(self) -> _builtins.str:
        """
        The type of value stored in the field. One of ["STRING" "CONCEALED" "EMAIL" "URL" "OTP" "DATE" "MONTH_YEAR" "MENU"]
        """
        return pulumi.get(self, "type")

    @_builtins.property
    @pulumi.getter
    def value(self) -> _builtins.str:
        """
        The value of the field.
        """
        return pulumi.get(self, "value")


@pulumi.output_type
class GetItemSectionFileResult(dict):
    def __init__(__self__, *,
                 content: _builtins.str,
                 content_base64: _builtins.str,
                 id: _builtins.str,
                 name: _builtins.str):
        """
        :param _builtins.str content: The content of the file.
        :param _builtins.str content_base64: The content of the file in base64 encoding. (Use this for binary files.)
        :param _builtins.str id: The UUID of the file.
        :param _builtins.str name: The name of the file.
        """
        pulumi.set(__self__, "content", content)
        pulumi.set(__self__, "content_base64", content_base64)
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "name", name)

    @_builtins.property
    @pulumi.getter
    def content(self) -> _builtins.str:
        """
        The content of the file.
        """
        return pulumi.get(self, "content")

    @_builtins.property
    @pulumi.getter(name="contentBase64")
    def content_base64(self) -> _builtins.str:
        """
        The content of the file in base64 encoding. (Use this for binary files.)
        """
        return pulumi.get(self, "content_base64")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The UUID of the file.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        The name of the file.
        """
        return pulumi.get(self, "name")


@pulumi.output_type
class GetItemSectionMapResult(dict):
    def __init__(__self__, *,
                 field_map: Mapping[str, 'outputs.GetItemSectionMapFieldMapResult'],
                 file_map: Mapping[str, 'outputs.GetItemSectionMapFileMapResult'],
                 id: _builtins.str):
        """
        :param Mapping[str, 'GetItemSectionMapFieldMapArgs'] field_map: A map of custom fields in the section, keyed by field label.
        :param Mapping[str, 'GetItemSectionMapFileMapArgs'] file_map: A map of files attached to the section, keyed by file label.
        :param _builtins.str id: A unique identifier for the section.
        """
        pulumi.set(__self__, "field_map", field_map)
        pulumi.set(__self__, "file_map", file_map)
        pulumi.set(__self__, "id", id)

    @_builtins.property
    @pulumi.getter(name="fieldMap")
    def field_map(self) -> Mapping[str, 'outputs.GetItemSectionMapFieldMapResult']:
        """
        A map of custom fields in the section, keyed by field label.
        """
        return pulumi.get(self, "field_map")

    @_builtins.property
    @pulumi.getter(name="fileMap")
    def file_map(self) -> Mapping[str, 'outputs.GetItemSectionMapFileMapResult']:
        """
        A map of files attached to the section, keyed by file label.
        """
        return pulumi.get(self, "file_map")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        A unique identifier for the section.
        """
        return pulumi.get(self, "id")


@pulumi.output_type
class GetItemSectionMapFieldMapResult(dict):
    def __init__(__self__, *,
                 id: _builtins.str,
                 type: _builtins.str,
                 value: _builtins.str):
        """
        :param _builtins.str id: A unique identifier for the field.
        :param _builtins.str type: The type of value stored in the field. One of ["STRING" "CONCEALED" "EMAIL" "URL" "OTP" "DATE" "MONTH_YEAR" "MENU"]
        :param _builtins.str value: The value of the field.
        """
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "type", type)
        pulumi.set(__self__, "value", value)

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        A unique identifier for the field.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def type(self) -> _builtins.str:
        """
        The type of value stored in the field. One of ["STRING" "CONCEALED" "EMAIL" "URL" "OTP" "DATE" "MONTH_YEAR" "MENU"]
        """
        return pulumi.get(self, "type")

    @_builtins.property
    @pulumi.getter
    def value(self) -> _builtins.str:
        """
        The value of the field.
        """
        return pulumi.get(self, "value")


@pulumi.output_type
class GetItemSectionMapFileMapResult(dict):
    def __init__(__self__, *,
                 content: _builtins.str,
                 content_base64: _builtins.str,
                 id: _builtins.str):
        """
        :param _builtins.str content: The content of the file.
        :param _builtins.str content_base64: The content of the file in base64 encoding. (Use this for binary files.)
        :param _builtins.str id: The UUID of the file.
        """
        pulumi.set(__self__, "content", content)
        pulumi.set(__self__, "content_base64", content_base64)
        pulumi.set(__self__, "id", id)

    @_builtins.property
    @pulumi.getter
    def content(self) -> _builtins.str:
        """
        The content of the file.
        """
        return pulumi.get(self, "content")

    @_builtins.property
    @pulumi.getter(name="contentBase64")
    def content_base64(self) -> _builtins.str:
        """
        The content of the file in base64 encoding. (Use this for binary files.)
        """
        return pulumi.get(self, "content_base64")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The UUID of the file.
        """
        return pulumi.get(self, "id")


