# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['ProviderArgs', 'Provider']

@pulumi.input_type
class ProviderArgs:
    def __init__(__self__, *,
                 account: Optional[pulumi.Input[_builtins.str]] = None,
                 connect_token: Optional[pulumi.Input[_builtins.str]] = None,
                 connect_url: Optional[pulumi.Input[_builtins.str]] = None,
                 service_account_token: Optional[pulumi.Input[_builtins.str]] = None,
                 token: Optional[pulumi.Input[_builtins.str]] = None,
                 url: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a Provider resource.

        :param pulumi.Input[_builtins.str] account: A valid account name or ID to use desktop app authentication. Can also be sourced from `OP_ACCOUNT` environment variable.
        :param pulumi.Input[_builtins.str] connect_token: A valid token for your 1Password Connect server. Can also be sourced from `OP_CONNECT_TOKEN` environment variable. Provider will use 1Password Connect server if set.
        :param pulumi.Input[_builtins.str] connect_url: The HTTP(S) URL where your 1Password Connect server can be found. Can also be sourced `OP_CONNECT_HOST` environment variable. Provider will use 1Password Connect server if set.
        :param pulumi.Input[_builtins.str] service_account_token: A valid 1Password service account token. Can also be sourced from `OP_SERVICE_ACCOUNT_TOKEN` environment variable.
        :param pulumi.Input[_builtins.str] token: A valid token for your 1Password Connect server. Can also be sourced from `OP_CONNECT_TOKEN` environment variable. Provider will use 1Password Connect server if set. Deprecated: Use `connect_token` instead.
        :param pulumi.Input[_builtins.str] url: The HTTP(S) URL where your 1Password Connect server can be found. Can also be sourced `OP_CONNECT_HOST` environment variable. Provider will use 1Password Connect server if set. Deprecated: Use `connect_url` instead.
        """
        if account is None:
            account = _utilities.get_env('OP_ACCOUNT')
        if account is not None:
            pulumi.set(__self__, "account", account)
        if connect_token is not None:
            pulumi.set(__self__, "connect_token", connect_token)
        if connect_url is not None:
            pulumi.set(__self__, "connect_url", connect_url)
        if service_account_token is None:
            service_account_token = _utilities.get_env('OP_SERVICE_ACCOUNT_TOKEN')
        if service_account_token is not None:
            pulumi.set(__self__, "service_account_token", service_account_token)
        if token is not None:
            warnings.warn("""The \"token\" field is deprecated and will be removed in a future version. Use \"connect_token\" instead.""", DeprecationWarning)
            pulumi.log.warn("""token is deprecated: The \"token\" field is deprecated and will be removed in a future version. Use \"connect_token\" instead.""")
        if token is None:
            token = _utilities.get_env('OP_CONNECT_TOKEN')
        if token is not None:
            pulumi.set(__self__, "token", token)
        if url is not None:
            warnings.warn("""The \"url\" field is deprecated and will be removed in a future version. Use \"connect_url\" instead.""", DeprecationWarning)
            pulumi.log.warn("""url is deprecated: The \"url\" field is deprecated and will be removed in a future version. Use \"connect_url\" instead.""")
        if url is None:
            url = _utilities.get_env('OP_CONNECT_HOST')
        if url is not None:
            pulumi.set(__self__, "url", url)

    @_builtins.property
    @pulumi.getter
    def account(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        A valid account name or ID to use desktop app authentication. Can also be sourced from `OP_ACCOUNT` environment variable.
        """
        return pulumi.get(self, "account")

    @account.setter
    def account(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "account", value)

    @_builtins.property
    @pulumi.getter(name="connectToken")
    def connect_token(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        A valid token for your 1Password Connect server. Can also be sourced from `OP_CONNECT_TOKEN` environment variable. Provider will use 1Password Connect server if set.
        """
        return pulumi.get(self, "connect_token")

    @connect_token.setter
    def connect_token(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "connect_token", value)

    @_builtins.property
    @pulumi.getter(name="connectUrl")
    def connect_url(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The HTTP(S) URL where your 1Password Connect server can be found. Can also be sourced `OP_CONNECT_HOST` environment variable. Provider will use 1Password Connect server if set.
        """
        return pulumi.get(self, "connect_url")

    @connect_url.setter
    def connect_url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "connect_url", value)

    @_builtins.property
    @pulumi.getter(name="serviceAccountToken")
    def service_account_token(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        A valid 1Password service account token. Can also be sourced from `OP_SERVICE_ACCOUNT_TOKEN` environment variable.
        """
        return pulumi.get(self, "service_account_token")

    @service_account_token.setter
    def service_account_token(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "service_account_token", value)

    @_builtins.property
    @pulumi.getter
    @_utilities.deprecated("""The \"token\" field is deprecated and will be removed in a future version. Use \"connect_token\" instead.""")
    def token(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        A valid token for your 1Password Connect server. Can also be sourced from `OP_CONNECT_TOKEN` environment variable. Provider will use 1Password Connect server if set. Deprecated: Use `connect_token` instead.
        """
        return pulumi.get(self, "token")

    @token.setter
    def token(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "token", value)

    @_builtins.property
    @pulumi.getter
    @_utilities.deprecated("""The \"url\" field is deprecated and will be removed in a future version. Use \"connect_url\" instead.""")
    def url(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The HTTP(S) URL where your 1Password Connect server can be found. Can also be sourced `OP_CONNECT_HOST` environment variable. Provider will use 1Password Connect server if set. Deprecated: Use `connect_url` instead.
        """
        return pulumi.get(self, "url")

    @url.setter
    def url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "url", value)


@pulumi.type_token("pulumi:providers:onepassword")
class Provider(pulumi.ProviderResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 account: Optional[pulumi.Input[_builtins.str]] = None,
                 connect_token: Optional[pulumi.Input[_builtins.str]] = None,
                 connect_url: Optional[pulumi.Input[_builtins.str]] = None,
                 service_account_token: Optional[pulumi.Input[_builtins.str]] = None,
                 token: Optional[pulumi.Input[_builtins.str]] = None,
                 url: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        The provider type for the onepassword package. By default, resources use package-wide configuration
        settings, however an explicit `Provider` instance may be created and passed during resource
        construction to achieve fine-grained programmatic control over provider settings. See the
        [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] account: A valid account name or ID to use desktop app authentication. Can also be sourced from `OP_ACCOUNT` environment variable.
        :param pulumi.Input[_builtins.str] connect_token: A valid token for your 1Password Connect server. Can also be sourced from `OP_CONNECT_TOKEN` environment variable. Provider will use 1Password Connect server if set.
        :param pulumi.Input[_builtins.str] connect_url: The HTTP(S) URL where your 1Password Connect server can be found. Can also be sourced `OP_CONNECT_HOST` environment variable. Provider will use 1Password Connect server if set.
        :param pulumi.Input[_builtins.str] service_account_token: A valid 1Password service account token. Can also be sourced from `OP_SERVICE_ACCOUNT_TOKEN` environment variable.
        :param pulumi.Input[_builtins.str] token: A valid token for your 1Password Connect server. Can also be sourced from `OP_CONNECT_TOKEN` environment variable. Provider will use 1Password Connect server if set. Deprecated: Use `connect_token` instead.
        :param pulumi.Input[_builtins.str] url: The HTTP(S) URL where your 1Password Connect server can be found. Can also be sourced `OP_CONNECT_HOST` environment variable. Provider will use 1Password Connect server if set. Deprecated: Use `connect_url` instead.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[ProviderArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        The provider type for the onepassword package. By default, resources use package-wide configuration
        settings, however an explicit `Provider` instance may be created and passed during resource
        construction to achieve fine-grained programmatic control over provider settings. See the
        [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.


        :param str resource_name: The name of the resource.
        :param ProviderArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ProviderArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 account: Optional[pulumi.Input[_builtins.str]] = None,
                 connect_token: Optional[pulumi.Input[_builtins.str]] = None,
                 connect_url: Optional[pulumi.Input[_builtins.str]] = None,
                 service_account_token: Optional[pulumi.Input[_builtins.str]] = None,
                 token: Optional[pulumi.Input[_builtins.str]] = None,
                 url: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ProviderArgs.__new__(ProviderArgs)

            if account is None:
                account = _utilities.get_env('OP_ACCOUNT')
            __props__.__dict__["account"] = account
            __props__.__dict__["connect_token"] = None if connect_token is None else pulumi.Output.secret(connect_token)
            __props__.__dict__["connect_url"] = connect_url
            if service_account_token is None:
                service_account_token = _utilities.get_env('OP_SERVICE_ACCOUNT_TOKEN')
            __props__.__dict__["service_account_token"] = None if service_account_token is None else pulumi.Output.secret(service_account_token)
            if token is None:
                token = _utilities.get_env('OP_CONNECT_TOKEN')
            __props__.__dict__["token"] = None if token is None else pulumi.Output.secret(token)
            if url is None:
                url = _utilities.get_env('OP_CONNECT_HOST')
            __props__.__dict__["url"] = url
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["connectToken", "serviceAccountToken", "token"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(Provider, __self__).__init__(
            'onepassword',
            resource_name,
            __props__,
            opts)

    @_builtins.property
    @pulumi.getter
    def account(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        A valid account name or ID to use desktop app authentication. Can also be sourced from `OP_ACCOUNT` environment variable.
        """
        return pulumi.get(self, "account")

    @_builtins.property
    @pulumi.getter(name="connectToken")
    def connect_token(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        A valid token for your 1Password Connect server. Can also be sourced from `OP_CONNECT_TOKEN` environment variable. Provider will use 1Password Connect server if set.
        """
        return pulumi.get(self, "connect_token")

    @_builtins.property
    @pulumi.getter(name="connectUrl")
    def connect_url(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The HTTP(S) URL where your 1Password Connect server can be found. Can also be sourced `OP_CONNECT_HOST` environment variable. Provider will use 1Password Connect server if set.
        """
        return pulumi.get(self, "connect_url")

    @_builtins.property
    @pulumi.getter(name="serviceAccountToken")
    def service_account_token(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        A valid 1Password service account token. Can also be sourced from `OP_SERVICE_ACCOUNT_TOKEN` environment variable.
        """
        return pulumi.get(self, "service_account_token")

    @_builtins.property
    @pulumi.getter
    @_utilities.deprecated("""The \"token\" field is deprecated and will be removed in a future version. Use \"connect_token\" instead.""")
    def token(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        A valid token for your 1Password Connect server. Can also be sourced from `OP_CONNECT_TOKEN` environment variable. Provider will use 1Password Connect server if set. Deprecated: Use `connect_token` instead.
        """
        return pulumi.get(self, "token")

    @_builtins.property
    @pulumi.getter
    @_utilities.deprecated("""The \"url\" field is deprecated and will be removed in a future version. Use \"connect_url\" instead.""")
    def url(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The HTTP(S) URL where your 1Password Connect server can be found. Can also be sourced `OP_CONNECT_HOST` environment variable. Provider will use 1Password Connect server if set. Deprecated: Use `connect_url` instead.
        """
        return pulumi.get(self, "url")

    @pulumi.output_type
    class TerraformConfigResult:
        def __init__(__self__, result=None):
            if result and not isinstance(result, dict):
                raise TypeError("Expected argument 'result' to be a dict")
            pulumi.set(__self__, "result", result)

        @_builtins.property
        @pulumi.getter
        def result(self) -> Mapping[str, Any]:
            return pulumi.get(self, "result")

    def terraform_config(__self__) -> pulumi.Output['Provider.TerraformConfigResult']:
        """
        This function returns a Terraform config object with terraform-namecased keys,to be used with the Terraform Module Provider.
        """
        __args__ = dict()
        __args__['__self__'] = __self__
        return pulumi.runtime.call('pulumi:providers:onepassword/terraformConfig', __args__, res=__self__, typ=Provider.TerraformConfigResult)

