// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface GetEnvironmentMetadata {
    /**
     * Whether the value is hidden by default in the 1Password app.
     */
    masked?: boolean;
    /**
     * The environment variable name.
     */
    name?: string;
    /**
     * The environment variable value.
     */
    value?: string;
}

export interface GetEnvironmentMetadataArgs {
    /**
     * Whether the value is hidden by default in the 1Password app.
     */
    masked?: pulumi.Input<boolean>;
    /**
     * The environment variable name.
     */
    name?: pulumi.Input<string>;
    /**
     * The environment variable value.
     */
    value?: pulumi.Input<string>;
}

export interface GetItemFile {
    /**
     * The content of the file.
     */
    content?: string;
    /**
     * The content of the file in base64 encoding. (Use this for binary files.)
     */
    contentBase64?: string;
    /**
     * The UUID of the file.
     */
    id?: string;
    /**
     * The name of the file.
     */
    name?: string;
}

export interface GetItemFileArgs {
    /**
     * The content of the file.
     */
    content?: pulumi.Input<string>;
    /**
     * The content of the file in base64 encoding. (Use this for binary files.)
     */
    contentBase64?: pulumi.Input<string>;
    /**
     * The UUID of the file.
     */
    id?: pulumi.Input<string>;
    /**
     * The name of the file.
     */
    name?: pulumi.Input<string>;
}

export interface GetItemSection {
    /**
     * A list of custom fields in the section
     */
    fields?: inputs.GetItemSectionField[];
    /**
     * A list of files attached to the section.
     */
    files?: inputs.GetItemSectionFile[];
    /**
     * A unique identifier for the section.
     */
    id?: string;
    /**
     * The label for the section.
     */
    label?: string;
}

export interface GetItemSectionArgs {
    /**
     * A list of custom fields in the section
     */
    fields?: pulumi.Input<pulumi.Input<inputs.GetItemSectionFieldArgs>[]>;
    /**
     * A list of files attached to the section.
     */
    files?: pulumi.Input<pulumi.Input<inputs.GetItemSectionFileArgs>[]>;
    /**
     * A unique identifier for the section.
     */
    id?: pulumi.Input<string>;
    /**
     * The label for the section.
     */
    label?: pulumi.Input<string>;
}

export interface GetItemSectionField {
    /**
     * A unique identifier for the field.
     */
    id?: string;
    /**
     * The label for the field.
     */
    label?: string;
    /**
     * The type of value stored in the field. One of ["STRING" "CONCEALED" "EMAIL" "URL" "OTP" "DATE" "MONTH_YEAR" "MENU"]
     */
    type?: string;
    /**
     * The value of the field.
     */
    value?: string;
}

export interface GetItemSectionFieldArgs {
    /**
     * A unique identifier for the field.
     */
    id?: pulumi.Input<string>;
    /**
     * The label for the field.
     */
    label?: pulumi.Input<string>;
    /**
     * The type of value stored in the field. One of ["STRING" "CONCEALED" "EMAIL" "URL" "OTP" "DATE" "MONTH_YEAR" "MENU"]
     */
    type?: pulumi.Input<string>;
    /**
     * The value of the field.
     */
    value?: pulumi.Input<string>;
}

export interface GetItemSectionFile {
    /**
     * The content of the file.
     */
    content?: string;
    /**
     * The content of the file in base64 encoding. (Use this for binary files.)
     */
    contentBase64?: string;
    /**
     * The UUID of the file.
     */
    id?: string;
    /**
     * The name of the file.
     */
    name?: string;
}

export interface GetItemSectionFileArgs {
    /**
     * The content of the file.
     */
    content?: pulumi.Input<string>;
    /**
     * The content of the file in base64 encoding. (Use this for binary files.)
     */
    contentBase64?: pulumi.Input<string>;
    /**
     * The UUID of the file.
     */
    id?: pulumi.Input<string>;
    /**
     * The name of the file.
     */
    name?: pulumi.Input<string>;
}

export interface GetItemSectionMap {
    /**
     * A map of custom fields in the section, keyed by field label.
     */
    fieldMap?: {[key: string]: inputs.GetItemSectionMapFieldMap};
    /**
     * A map of files attached to the section, keyed by file label.
     */
    fileMap?: {[key: string]: inputs.GetItemSectionMapFileMap};
    /**
     * A unique identifier for the section.
     */
    id?: string;
}

export interface GetItemSectionMapArgs {
    /**
     * A map of custom fields in the section, keyed by field label.
     */
    fieldMap?: pulumi.Input<{[key: string]: pulumi.Input<inputs.GetItemSectionMapFieldMapArgs>}>;
    /**
     * A map of files attached to the section, keyed by file label.
     */
    fileMap?: pulumi.Input<{[key: string]: pulumi.Input<inputs.GetItemSectionMapFileMapArgs>}>;
    /**
     * A unique identifier for the section.
     */
    id?: pulumi.Input<string>;
}

export interface GetItemSectionMapFieldMap {
    /**
     * A unique identifier for the field.
     */
    id?: string;
    /**
     * The type of value stored in the field. One of ["STRING" "CONCEALED" "EMAIL" "URL" "OTP" "DATE" "MONTH_YEAR" "MENU"]
     */
    type?: string;
    /**
     * The value of the field.
     */
    value?: string;
}

export interface GetItemSectionMapFieldMapArgs {
    /**
     * A unique identifier for the field.
     */
    id?: pulumi.Input<string>;
    /**
     * The type of value stored in the field. One of ["STRING" "CONCEALED" "EMAIL" "URL" "OTP" "DATE" "MONTH_YEAR" "MENU"]
     */
    type?: pulumi.Input<string>;
    /**
     * The value of the field.
     */
    value?: pulumi.Input<string>;
}

export interface GetItemSectionMapFileMap {
    /**
     * The content of the file.
     */
    content?: string;
    /**
     * The content of the file in base64 encoding. (Use this for binary files.)
     */
    contentBase64?: string;
    /**
     * The UUID of the file.
     */
    id?: string;
}

export interface GetItemSectionMapFileMapArgs {
    /**
     * The content of the file.
     */
    content?: pulumi.Input<string>;
    /**
     * The content of the file in base64 encoding. (Use this for binary files.)
     */
    contentBase64?: pulumi.Input<string>;
    /**
     * The UUID of the file.
     */
    id?: pulumi.Input<string>;
}

export interface ItemPasswordRecipe {
    /**
     * Use digits [0-9] when generating the password.
     */
    digits?: pulumi.Input<boolean>;
    /**
     * The length of the password to be generated.
     */
    length?: pulumi.Input<number>;
    /**
     * Use symbols [!@.-_*] when generating the password.
     */
    symbols?: pulumi.Input<boolean>;
}

export interface ItemSection {
    /**
     * A list of custom fields in the section
     */
    fields?: pulumi.Input<pulumi.Input<inputs.ItemSectionField>[]>;
    /**
     * A unique identifier for the section.
     */
    id?: pulumi.Input<string>;
    /**
     * The label for the section.
     */
    label: pulumi.Input<string>;
}

export interface ItemSectionField {
    /**
     * A unique identifier for the field.
     */
    id?: pulumi.Input<string>;
    /**
     * The label for the field.
     */
    label: pulumi.Input<string>;
    /**
     * The recipe used to generate a new value for a password.
     */
    passwordRecipe?: pulumi.Input<inputs.ItemSectionFieldPasswordRecipe>;
    /**
     * The type of value stored in the field. One of ["STRING" "CONCEALED" "EMAIL" "URL" "OTP" "DATE" "MONTH_YEAR" "MENU"]
     */
    type?: pulumi.Input<string>;
    /**
     * The value of the field.
     */
    value?: pulumi.Input<string>;
}

export interface ItemSectionFieldPasswordRecipe {
    /**
     * Use digits [0-9] when generating the password.
     */
    digits?: pulumi.Input<boolean>;
    /**
     * The length of the password to be generated.
     */
    length?: pulumi.Input<number>;
    /**
     * Use symbols [!@.-_*] when generating the password.
     */
    symbols?: pulumi.Input<boolean>;
}

export interface ItemSectionMap {
    /**
     * A map of custom fields in the section, keyed by field label.
     */
    fieldMap?: pulumi.Input<{[key: string]: pulumi.Input<inputs.ItemSectionMapFieldMap>}>;
    /**
     * A unique identifier for the section.
     */
    id?: pulumi.Input<string>;
}

export interface ItemSectionMapFieldMap {
    /**
     * A unique identifier for the field.
     */
    id?: pulumi.Input<string>;
    /**
     * The recipe used to generate a new value for a password.
     */
    passwordRecipe?: pulumi.Input<inputs.ItemSectionMapFieldMapPasswordRecipe>;
    /**
     * The type of value stored in the field. One of ["STRING" "CONCEALED" "EMAIL" "URL" "OTP" "DATE" "MONTH_YEAR" "MENU"]
     */
    type?: pulumi.Input<string>;
    /**
     * The value of the field.
     */
    value?: pulumi.Input<string>;
}

export interface ItemSectionMapFieldMapPasswordRecipe {
    /**
     * Use digits [0-9] when generating the password.
     */
    digits?: pulumi.Input<boolean>;
    /**
     * The length of the password to be generated.
     */
    length?: pulumi.Input<number>;
    /**
     * Use symbols [!@.-_*] when generating the password.
     */
    symbols?: pulumi.Input<boolean>;
}
