// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface GetEnvironmentMetadata {
    /**
     * Whether the value is hidden by default in the 1Password app.
     */
    masked: boolean;
    /**
     * The environment variable name.
     */
    name: string;
    /**
     * The environment variable value.
     */
    value: string;
}

export interface GetItemFile {
    /**
     * The content of the file.
     */
    content: string;
    /**
     * The content of the file in base64 encoding. (Use this for binary files.)
     */
    contentBase64: string;
    /**
     * The UUID of the file.
     */
    id: string;
    /**
     * The name of the file.
     */
    name: string;
}

export interface GetItemSection {
    /**
     * A list of custom fields in the section
     */
    fields?: outputs.GetItemSectionField[];
    /**
     * A list of files attached to the section.
     */
    files?: outputs.GetItemSectionFile[];
    /**
     * A unique identifier for the section.
     */
    id: string;
    /**
     * The label for the section.
     */
    label: string;
}

export interface GetItemSectionField {
    /**
     * A unique identifier for the field.
     */
    id: string;
    /**
     * The label for the field.
     */
    label: string;
    /**
     * The type of value stored in the field. One of ["STRING" "CONCEALED" "EMAIL" "URL" "OTP" "DATE" "MONTH_YEAR" "MENU"]
     */
    type: string;
    /**
     * The value of the field.
     */
    value: string;
}

export interface GetItemSectionFile {
    /**
     * The content of the file.
     */
    content: string;
    /**
     * The content of the file in base64 encoding. (Use this for binary files.)
     */
    contentBase64: string;
    /**
     * The UUID of the file.
     */
    id: string;
    /**
     * The name of the file.
     */
    name: string;
}

export interface GetItemSectionMap {
    /**
     * A map of custom fields in the section, keyed by field label.
     */
    fieldMap: {[key: string]: outputs.GetItemSectionMapFieldMap};
    /**
     * A map of files attached to the section, keyed by file label.
     */
    fileMap: {[key: string]: outputs.GetItemSectionMapFileMap};
    /**
     * A unique identifier for the section.
     */
    id: string;
}

export interface GetItemSectionMapFieldMap {
    /**
     * A unique identifier for the field.
     */
    id: string;
    /**
     * The type of value stored in the field. One of ["STRING" "CONCEALED" "EMAIL" "URL" "OTP" "DATE" "MONTH_YEAR" "MENU"]
     */
    type: string;
    /**
     * The value of the field.
     */
    value: string;
}

export interface GetItemSectionMapFileMap {
    /**
     * The content of the file.
     */
    content: string;
    /**
     * The content of the file in base64 encoding. (Use this for binary files.)
     */
    contentBase64: string;
    /**
     * The UUID of the file.
     */
    id: string;
}

export interface ItemPasswordRecipe {
    /**
     * Use digits [0-9] when generating the password.
     */
    digits: boolean;
    /**
     * The length of the password to be generated.
     */
    length: number;
    /**
     * Use symbols [!@.-_*] when generating the password.
     */
    symbols: boolean;
}

export interface ItemSection {
    /**
     * A list of custom fields in the section
     */
    fields?: outputs.ItemSectionField[];
    /**
     * A unique identifier for the section.
     */
    id: string;
    /**
     * The label for the section.
     */
    label: string;
}

export interface ItemSectionField {
    /**
     * A unique identifier for the field.
     */
    id: string;
    /**
     * The label for the field.
     */
    label: string;
    /**
     * The recipe used to generate a new value for a password.
     */
    passwordRecipe?: outputs.ItemSectionFieldPasswordRecipe;
    /**
     * The type of value stored in the field. One of ["STRING" "CONCEALED" "EMAIL" "URL" "OTP" "DATE" "MONTH_YEAR" "MENU"]
     */
    type: string;
    /**
     * The value of the field.
     */
    value: string;
}

export interface ItemSectionFieldPasswordRecipe {
    /**
     * Use digits [0-9] when generating the password.
     */
    digits: boolean;
    /**
     * The length of the password to be generated.
     */
    length: number;
    /**
     * Use symbols [!@.-_*] when generating the password.
     */
    symbols: boolean;
}

export interface ItemSectionMap {
    /**
     * A map of custom fields in the section, keyed by field label.
     */
    fieldMap?: {[key: string]: outputs.ItemSectionMapFieldMap};
    /**
     * A unique identifier for the section.
     */
    id: string;
}

export interface ItemSectionMapFieldMap {
    /**
     * A unique identifier for the field.
     */
    id: string;
    /**
     * The recipe used to generate a new value for a password.
     */
    passwordRecipe?: outputs.ItemSectionMapFieldMapPasswordRecipe;
    /**
     * The type of value stored in the field. One of ["STRING" "CONCEALED" "EMAIL" "URL" "OTP" "DATE" "MONTH_YEAR" "MENU"]
     */
    type: string;
    /**
     * The value of the field.
     */
    value: string;
}

export interface ItemSectionMapFieldMapPasswordRecipe {
    /**
     * Use digits [0-9] when generating the password.
     */
    digits: boolean;
    /**
     * The length of the password to be generated.
     */
    length: number;
    /**
     * Use symbols [!@.-_*] when generating the password.
     */
    symbols: boolean;
}

