// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package onepassword

import (
	"context"
	"reflect"

	"github.com/1Password/pulumi-onepassword/sdk/go/onepassword/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type ItemPasswordRecipe struct {
	// Use digits [0-9] when generating the password.
	Digits *bool `pulumi:"digits"`
	// The length of the password to be generated.
	Length *int `pulumi:"length"`
	// Use symbols [!@.-_*] when generating the password.
	Symbols *bool `pulumi:"symbols"`
}

// ItemPasswordRecipeInput is an input type that accepts ItemPasswordRecipeArgs and ItemPasswordRecipeOutput values.
// You can construct a concrete instance of `ItemPasswordRecipeInput` via:
//
//	ItemPasswordRecipeArgs{...}
type ItemPasswordRecipeInput interface {
	pulumi.Input

	ToItemPasswordRecipeOutput() ItemPasswordRecipeOutput
	ToItemPasswordRecipeOutputWithContext(context.Context) ItemPasswordRecipeOutput
}

type ItemPasswordRecipeArgs struct {
	// Use digits [0-9] when generating the password.
	Digits pulumi.BoolPtrInput `pulumi:"digits"`
	// The length of the password to be generated.
	Length pulumi.IntPtrInput `pulumi:"length"`
	// Use symbols [!@.-_*] when generating the password.
	Symbols pulumi.BoolPtrInput `pulumi:"symbols"`
}

func (ItemPasswordRecipeArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ItemPasswordRecipe)(nil)).Elem()
}

func (i ItemPasswordRecipeArgs) ToItemPasswordRecipeOutput() ItemPasswordRecipeOutput {
	return i.ToItemPasswordRecipeOutputWithContext(context.Background())
}

func (i ItemPasswordRecipeArgs) ToItemPasswordRecipeOutputWithContext(ctx context.Context) ItemPasswordRecipeOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ItemPasswordRecipeOutput)
}

func (i ItemPasswordRecipeArgs) ToItemPasswordRecipePtrOutput() ItemPasswordRecipePtrOutput {
	return i.ToItemPasswordRecipePtrOutputWithContext(context.Background())
}

func (i ItemPasswordRecipeArgs) ToItemPasswordRecipePtrOutputWithContext(ctx context.Context) ItemPasswordRecipePtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ItemPasswordRecipeOutput).ToItemPasswordRecipePtrOutputWithContext(ctx)
}

// ItemPasswordRecipePtrInput is an input type that accepts ItemPasswordRecipeArgs, ItemPasswordRecipePtr and ItemPasswordRecipePtrOutput values.
// You can construct a concrete instance of `ItemPasswordRecipePtrInput` via:
//
//	        ItemPasswordRecipeArgs{...}
//
//	or:
//
//	        nil
type ItemPasswordRecipePtrInput interface {
	pulumi.Input

	ToItemPasswordRecipePtrOutput() ItemPasswordRecipePtrOutput
	ToItemPasswordRecipePtrOutputWithContext(context.Context) ItemPasswordRecipePtrOutput
}

type itemPasswordRecipePtrType ItemPasswordRecipeArgs

func ItemPasswordRecipePtr(v *ItemPasswordRecipeArgs) ItemPasswordRecipePtrInput {
	return (*itemPasswordRecipePtrType)(v)
}

func (*itemPasswordRecipePtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**ItemPasswordRecipe)(nil)).Elem()
}

func (i *itemPasswordRecipePtrType) ToItemPasswordRecipePtrOutput() ItemPasswordRecipePtrOutput {
	return i.ToItemPasswordRecipePtrOutputWithContext(context.Background())
}

func (i *itemPasswordRecipePtrType) ToItemPasswordRecipePtrOutputWithContext(ctx context.Context) ItemPasswordRecipePtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ItemPasswordRecipePtrOutput)
}

type ItemPasswordRecipeOutput struct{ *pulumi.OutputState }

func (ItemPasswordRecipeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ItemPasswordRecipe)(nil)).Elem()
}

func (o ItemPasswordRecipeOutput) ToItemPasswordRecipeOutput() ItemPasswordRecipeOutput {
	return o
}

func (o ItemPasswordRecipeOutput) ToItemPasswordRecipeOutputWithContext(ctx context.Context) ItemPasswordRecipeOutput {
	return o
}

func (o ItemPasswordRecipeOutput) ToItemPasswordRecipePtrOutput() ItemPasswordRecipePtrOutput {
	return o.ToItemPasswordRecipePtrOutputWithContext(context.Background())
}

func (o ItemPasswordRecipeOutput) ToItemPasswordRecipePtrOutputWithContext(ctx context.Context) ItemPasswordRecipePtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v ItemPasswordRecipe) *ItemPasswordRecipe {
		return &v
	}).(ItemPasswordRecipePtrOutput)
}

// Use digits [0-9] when generating the password.
func (o ItemPasswordRecipeOutput) Digits() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v ItemPasswordRecipe) *bool { return v.Digits }).(pulumi.BoolPtrOutput)
}

// The length of the password to be generated.
func (o ItemPasswordRecipeOutput) Length() pulumi.IntPtrOutput {
	return o.ApplyT(func(v ItemPasswordRecipe) *int { return v.Length }).(pulumi.IntPtrOutput)
}

// Use symbols [!@.-_*] when generating the password.
func (o ItemPasswordRecipeOutput) Symbols() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v ItemPasswordRecipe) *bool { return v.Symbols }).(pulumi.BoolPtrOutput)
}

type ItemPasswordRecipePtrOutput struct{ *pulumi.OutputState }

func (ItemPasswordRecipePtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ItemPasswordRecipe)(nil)).Elem()
}

func (o ItemPasswordRecipePtrOutput) ToItemPasswordRecipePtrOutput() ItemPasswordRecipePtrOutput {
	return o
}

func (o ItemPasswordRecipePtrOutput) ToItemPasswordRecipePtrOutputWithContext(ctx context.Context) ItemPasswordRecipePtrOutput {
	return o
}

func (o ItemPasswordRecipePtrOutput) Elem() ItemPasswordRecipeOutput {
	return o.ApplyT(func(v *ItemPasswordRecipe) ItemPasswordRecipe {
		if v != nil {
			return *v
		}
		var ret ItemPasswordRecipe
		return ret
	}).(ItemPasswordRecipeOutput)
}

// Use digits [0-9] when generating the password.
func (o ItemPasswordRecipePtrOutput) Digits() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ItemPasswordRecipe) *bool {
		if v == nil {
			return nil
		}
		return v.Digits
	}).(pulumi.BoolPtrOutput)
}

// The length of the password to be generated.
func (o ItemPasswordRecipePtrOutput) Length() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *ItemPasswordRecipe) *int {
		if v == nil {
			return nil
		}
		return v.Length
	}).(pulumi.IntPtrOutput)
}

// Use symbols [!@.-_*] when generating the password.
func (o ItemPasswordRecipePtrOutput) Symbols() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ItemPasswordRecipe) *bool {
		if v == nil {
			return nil
		}
		return v.Symbols
	}).(pulumi.BoolPtrOutput)
}

type ItemSection struct {
	// A list of custom fields in the section
	Fields []ItemSectionField `pulumi:"fields"`
	// A unique identifier for the section.
	Id *string `pulumi:"id"`
	// The label for the section.
	Label string `pulumi:"label"`
}

// ItemSectionInput is an input type that accepts ItemSectionArgs and ItemSectionOutput values.
// You can construct a concrete instance of `ItemSectionInput` via:
//
//	ItemSectionArgs{...}
type ItemSectionInput interface {
	pulumi.Input

	ToItemSectionOutput() ItemSectionOutput
	ToItemSectionOutputWithContext(context.Context) ItemSectionOutput
}

type ItemSectionArgs struct {
	// A list of custom fields in the section
	Fields ItemSectionFieldArrayInput `pulumi:"fields"`
	// A unique identifier for the section.
	Id pulumi.StringPtrInput `pulumi:"id"`
	// The label for the section.
	Label pulumi.StringInput `pulumi:"label"`
}

func (ItemSectionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ItemSection)(nil)).Elem()
}

func (i ItemSectionArgs) ToItemSectionOutput() ItemSectionOutput {
	return i.ToItemSectionOutputWithContext(context.Background())
}

func (i ItemSectionArgs) ToItemSectionOutputWithContext(ctx context.Context) ItemSectionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ItemSectionOutput)
}

// ItemSectionArrayInput is an input type that accepts ItemSectionArray and ItemSectionArrayOutput values.
// You can construct a concrete instance of `ItemSectionArrayInput` via:
//
//	ItemSectionArray{ ItemSectionArgs{...} }
type ItemSectionArrayInput interface {
	pulumi.Input

	ToItemSectionArrayOutput() ItemSectionArrayOutput
	ToItemSectionArrayOutputWithContext(context.Context) ItemSectionArrayOutput
}

type ItemSectionArray []ItemSectionInput

func (ItemSectionArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]ItemSection)(nil)).Elem()
}

func (i ItemSectionArray) ToItemSectionArrayOutput() ItemSectionArrayOutput {
	return i.ToItemSectionArrayOutputWithContext(context.Background())
}

func (i ItemSectionArray) ToItemSectionArrayOutputWithContext(ctx context.Context) ItemSectionArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ItemSectionArrayOutput)
}

type ItemSectionOutput struct{ *pulumi.OutputState }

func (ItemSectionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ItemSection)(nil)).Elem()
}

func (o ItemSectionOutput) ToItemSectionOutput() ItemSectionOutput {
	return o
}

func (o ItemSectionOutput) ToItemSectionOutputWithContext(ctx context.Context) ItemSectionOutput {
	return o
}

// A list of custom fields in the section
func (o ItemSectionOutput) Fields() ItemSectionFieldArrayOutput {
	return o.ApplyT(func(v ItemSection) []ItemSectionField { return v.Fields }).(ItemSectionFieldArrayOutput)
}

// A unique identifier for the section.
func (o ItemSectionOutput) Id() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ItemSection) *string { return v.Id }).(pulumi.StringPtrOutput)
}

// The label for the section.
func (o ItemSectionOutput) Label() pulumi.StringOutput {
	return o.ApplyT(func(v ItemSection) string { return v.Label }).(pulumi.StringOutput)
}

type ItemSectionArrayOutput struct{ *pulumi.OutputState }

func (ItemSectionArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]ItemSection)(nil)).Elem()
}

func (o ItemSectionArrayOutput) ToItemSectionArrayOutput() ItemSectionArrayOutput {
	return o
}

func (o ItemSectionArrayOutput) ToItemSectionArrayOutputWithContext(ctx context.Context) ItemSectionArrayOutput {
	return o
}

func (o ItemSectionArrayOutput) Index(i pulumi.IntInput) ItemSectionOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) ItemSection {
		return vs[0].([]ItemSection)[vs[1].(int)]
	}).(ItemSectionOutput)
}

type ItemSectionField struct {
	// A unique identifier for the field.
	Id *string `pulumi:"id"`
	// The label for the field.
	Label string `pulumi:"label"`
	// The recipe used to generate a new value for a password.
	PasswordRecipe *ItemSectionFieldPasswordRecipe `pulumi:"passwordRecipe"`
	// The type of value stored in the field. One of ["STRING" "CONCEALED" "EMAIL" "URL" "OTP" "DATE" "MONTH_YEAR" "MENU"]
	Type *string `pulumi:"type"`
	// The value of the field.
	Value *string `pulumi:"value"`
}

// ItemSectionFieldInput is an input type that accepts ItemSectionFieldArgs and ItemSectionFieldOutput values.
// You can construct a concrete instance of `ItemSectionFieldInput` via:
//
//	ItemSectionFieldArgs{...}
type ItemSectionFieldInput interface {
	pulumi.Input

	ToItemSectionFieldOutput() ItemSectionFieldOutput
	ToItemSectionFieldOutputWithContext(context.Context) ItemSectionFieldOutput
}

type ItemSectionFieldArgs struct {
	// A unique identifier for the field.
	Id pulumi.StringPtrInput `pulumi:"id"`
	// The label for the field.
	Label pulumi.StringInput `pulumi:"label"`
	// The recipe used to generate a new value for a password.
	PasswordRecipe ItemSectionFieldPasswordRecipePtrInput `pulumi:"passwordRecipe"`
	// The type of value stored in the field. One of ["STRING" "CONCEALED" "EMAIL" "URL" "OTP" "DATE" "MONTH_YEAR" "MENU"]
	Type pulumi.StringPtrInput `pulumi:"type"`
	// The value of the field.
	Value pulumi.StringPtrInput `pulumi:"value"`
}

func (ItemSectionFieldArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ItemSectionField)(nil)).Elem()
}

func (i ItemSectionFieldArgs) ToItemSectionFieldOutput() ItemSectionFieldOutput {
	return i.ToItemSectionFieldOutputWithContext(context.Background())
}

func (i ItemSectionFieldArgs) ToItemSectionFieldOutputWithContext(ctx context.Context) ItemSectionFieldOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ItemSectionFieldOutput)
}

// ItemSectionFieldArrayInput is an input type that accepts ItemSectionFieldArray and ItemSectionFieldArrayOutput values.
// You can construct a concrete instance of `ItemSectionFieldArrayInput` via:
//
//	ItemSectionFieldArray{ ItemSectionFieldArgs{...} }
type ItemSectionFieldArrayInput interface {
	pulumi.Input

	ToItemSectionFieldArrayOutput() ItemSectionFieldArrayOutput
	ToItemSectionFieldArrayOutputWithContext(context.Context) ItemSectionFieldArrayOutput
}

type ItemSectionFieldArray []ItemSectionFieldInput

func (ItemSectionFieldArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]ItemSectionField)(nil)).Elem()
}

func (i ItemSectionFieldArray) ToItemSectionFieldArrayOutput() ItemSectionFieldArrayOutput {
	return i.ToItemSectionFieldArrayOutputWithContext(context.Background())
}

func (i ItemSectionFieldArray) ToItemSectionFieldArrayOutputWithContext(ctx context.Context) ItemSectionFieldArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ItemSectionFieldArrayOutput)
}

type ItemSectionFieldOutput struct{ *pulumi.OutputState }

func (ItemSectionFieldOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ItemSectionField)(nil)).Elem()
}

func (o ItemSectionFieldOutput) ToItemSectionFieldOutput() ItemSectionFieldOutput {
	return o
}

func (o ItemSectionFieldOutput) ToItemSectionFieldOutputWithContext(ctx context.Context) ItemSectionFieldOutput {
	return o
}

// A unique identifier for the field.
func (o ItemSectionFieldOutput) Id() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ItemSectionField) *string { return v.Id }).(pulumi.StringPtrOutput)
}

// The label for the field.
func (o ItemSectionFieldOutput) Label() pulumi.StringOutput {
	return o.ApplyT(func(v ItemSectionField) string { return v.Label }).(pulumi.StringOutput)
}

// The recipe used to generate a new value for a password.
func (o ItemSectionFieldOutput) PasswordRecipe() ItemSectionFieldPasswordRecipePtrOutput {
	return o.ApplyT(func(v ItemSectionField) *ItemSectionFieldPasswordRecipe { return v.PasswordRecipe }).(ItemSectionFieldPasswordRecipePtrOutput)
}

// The type of value stored in the field. One of ["STRING" "CONCEALED" "EMAIL" "URL" "OTP" "DATE" "MONTH_YEAR" "MENU"]
func (o ItemSectionFieldOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ItemSectionField) *string { return v.Type }).(pulumi.StringPtrOutput)
}

// The value of the field.
func (o ItemSectionFieldOutput) Value() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ItemSectionField) *string { return v.Value }).(pulumi.StringPtrOutput)
}

type ItemSectionFieldArrayOutput struct{ *pulumi.OutputState }

func (ItemSectionFieldArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]ItemSectionField)(nil)).Elem()
}

func (o ItemSectionFieldArrayOutput) ToItemSectionFieldArrayOutput() ItemSectionFieldArrayOutput {
	return o
}

func (o ItemSectionFieldArrayOutput) ToItemSectionFieldArrayOutputWithContext(ctx context.Context) ItemSectionFieldArrayOutput {
	return o
}

func (o ItemSectionFieldArrayOutput) Index(i pulumi.IntInput) ItemSectionFieldOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) ItemSectionField {
		return vs[0].([]ItemSectionField)[vs[1].(int)]
	}).(ItemSectionFieldOutput)
}

type ItemSectionFieldPasswordRecipe struct {
	// Use digits [0-9] when generating the password.
	Digits *bool `pulumi:"digits"`
	// The length of the password to be generated.
	Length *int `pulumi:"length"`
	// Use symbols [!@.-_*] when generating the password.
	Symbols *bool `pulumi:"symbols"`
}

// ItemSectionFieldPasswordRecipeInput is an input type that accepts ItemSectionFieldPasswordRecipeArgs and ItemSectionFieldPasswordRecipeOutput values.
// You can construct a concrete instance of `ItemSectionFieldPasswordRecipeInput` via:
//
//	ItemSectionFieldPasswordRecipeArgs{...}
type ItemSectionFieldPasswordRecipeInput interface {
	pulumi.Input

	ToItemSectionFieldPasswordRecipeOutput() ItemSectionFieldPasswordRecipeOutput
	ToItemSectionFieldPasswordRecipeOutputWithContext(context.Context) ItemSectionFieldPasswordRecipeOutput
}

type ItemSectionFieldPasswordRecipeArgs struct {
	// Use digits [0-9] when generating the password.
	Digits pulumi.BoolPtrInput `pulumi:"digits"`
	// The length of the password to be generated.
	Length pulumi.IntPtrInput `pulumi:"length"`
	// Use symbols [!@.-_*] when generating the password.
	Symbols pulumi.BoolPtrInput `pulumi:"symbols"`
}

func (ItemSectionFieldPasswordRecipeArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ItemSectionFieldPasswordRecipe)(nil)).Elem()
}

func (i ItemSectionFieldPasswordRecipeArgs) ToItemSectionFieldPasswordRecipeOutput() ItemSectionFieldPasswordRecipeOutput {
	return i.ToItemSectionFieldPasswordRecipeOutputWithContext(context.Background())
}

func (i ItemSectionFieldPasswordRecipeArgs) ToItemSectionFieldPasswordRecipeOutputWithContext(ctx context.Context) ItemSectionFieldPasswordRecipeOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ItemSectionFieldPasswordRecipeOutput)
}

func (i ItemSectionFieldPasswordRecipeArgs) ToItemSectionFieldPasswordRecipePtrOutput() ItemSectionFieldPasswordRecipePtrOutput {
	return i.ToItemSectionFieldPasswordRecipePtrOutputWithContext(context.Background())
}

func (i ItemSectionFieldPasswordRecipeArgs) ToItemSectionFieldPasswordRecipePtrOutputWithContext(ctx context.Context) ItemSectionFieldPasswordRecipePtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ItemSectionFieldPasswordRecipeOutput).ToItemSectionFieldPasswordRecipePtrOutputWithContext(ctx)
}

// ItemSectionFieldPasswordRecipePtrInput is an input type that accepts ItemSectionFieldPasswordRecipeArgs, ItemSectionFieldPasswordRecipePtr and ItemSectionFieldPasswordRecipePtrOutput values.
// You can construct a concrete instance of `ItemSectionFieldPasswordRecipePtrInput` via:
//
//	        ItemSectionFieldPasswordRecipeArgs{...}
//
//	or:
//
//	        nil
type ItemSectionFieldPasswordRecipePtrInput interface {
	pulumi.Input

	ToItemSectionFieldPasswordRecipePtrOutput() ItemSectionFieldPasswordRecipePtrOutput
	ToItemSectionFieldPasswordRecipePtrOutputWithContext(context.Context) ItemSectionFieldPasswordRecipePtrOutput
}

type itemSectionFieldPasswordRecipePtrType ItemSectionFieldPasswordRecipeArgs

func ItemSectionFieldPasswordRecipePtr(v *ItemSectionFieldPasswordRecipeArgs) ItemSectionFieldPasswordRecipePtrInput {
	return (*itemSectionFieldPasswordRecipePtrType)(v)
}

func (*itemSectionFieldPasswordRecipePtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**ItemSectionFieldPasswordRecipe)(nil)).Elem()
}

func (i *itemSectionFieldPasswordRecipePtrType) ToItemSectionFieldPasswordRecipePtrOutput() ItemSectionFieldPasswordRecipePtrOutput {
	return i.ToItemSectionFieldPasswordRecipePtrOutputWithContext(context.Background())
}

func (i *itemSectionFieldPasswordRecipePtrType) ToItemSectionFieldPasswordRecipePtrOutputWithContext(ctx context.Context) ItemSectionFieldPasswordRecipePtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ItemSectionFieldPasswordRecipePtrOutput)
}

type ItemSectionFieldPasswordRecipeOutput struct{ *pulumi.OutputState }

func (ItemSectionFieldPasswordRecipeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ItemSectionFieldPasswordRecipe)(nil)).Elem()
}

func (o ItemSectionFieldPasswordRecipeOutput) ToItemSectionFieldPasswordRecipeOutput() ItemSectionFieldPasswordRecipeOutput {
	return o
}

func (o ItemSectionFieldPasswordRecipeOutput) ToItemSectionFieldPasswordRecipeOutputWithContext(ctx context.Context) ItemSectionFieldPasswordRecipeOutput {
	return o
}

func (o ItemSectionFieldPasswordRecipeOutput) ToItemSectionFieldPasswordRecipePtrOutput() ItemSectionFieldPasswordRecipePtrOutput {
	return o.ToItemSectionFieldPasswordRecipePtrOutputWithContext(context.Background())
}

func (o ItemSectionFieldPasswordRecipeOutput) ToItemSectionFieldPasswordRecipePtrOutputWithContext(ctx context.Context) ItemSectionFieldPasswordRecipePtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v ItemSectionFieldPasswordRecipe) *ItemSectionFieldPasswordRecipe {
		return &v
	}).(ItemSectionFieldPasswordRecipePtrOutput)
}

// Use digits [0-9] when generating the password.
func (o ItemSectionFieldPasswordRecipeOutput) Digits() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v ItemSectionFieldPasswordRecipe) *bool { return v.Digits }).(pulumi.BoolPtrOutput)
}

// The length of the password to be generated.
func (o ItemSectionFieldPasswordRecipeOutput) Length() pulumi.IntPtrOutput {
	return o.ApplyT(func(v ItemSectionFieldPasswordRecipe) *int { return v.Length }).(pulumi.IntPtrOutput)
}

// Use symbols [!@.-_*] when generating the password.
func (o ItemSectionFieldPasswordRecipeOutput) Symbols() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v ItemSectionFieldPasswordRecipe) *bool { return v.Symbols }).(pulumi.BoolPtrOutput)
}

type ItemSectionFieldPasswordRecipePtrOutput struct{ *pulumi.OutputState }

func (ItemSectionFieldPasswordRecipePtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ItemSectionFieldPasswordRecipe)(nil)).Elem()
}

func (o ItemSectionFieldPasswordRecipePtrOutput) ToItemSectionFieldPasswordRecipePtrOutput() ItemSectionFieldPasswordRecipePtrOutput {
	return o
}

func (o ItemSectionFieldPasswordRecipePtrOutput) ToItemSectionFieldPasswordRecipePtrOutputWithContext(ctx context.Context) ItemSectionFieldPasswordRecipePtrOutput {
	return o
}

func (o ItemSectionFieldPasswordRecipePtrOutput) Elem() ItemSectionFieldPasswordRecipeOutput {
	return o.ApplyT(func(v *ItemSectionFieldPasswordRecipe) ItemSectionFieldPasswordRecipe {
		if v != nil {
			return *v
		}
		var ret ItemSectionFieldPasswordRecipe
		return ret
	}).(ItemSectionFieldPasswordRecipeOutput)
}

// Use digits [0-9] when generating the password.
func (o ItemSectionFieldPasswordRecipePtrOutput) Digits() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ItemSectionFieldPasswordRecipe) *bool {
		if v == nil {
			return nil
		}
		return v.Digits
	}).(pulumi.BoolPtrOutput)
}

// The length of the password to be generated.
func (o ItemSectionFieldPasswordRecipePtrOutput) Length() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *ItemSectionFieldPasswordRecipe) *int {
		if v == nil {
			return nil
		}
		return v.Length
	}).(pulumi.IntPtrOutput)
}

// Use symbols [!@.-_*] when generating the password.
func (o ItemSectionFieldPasswordRecipePtrOutput) Symbols() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ItemSectionFieldPasswordRecipe) *bool {
		if v == nil {
			return nil
		}
		return v.Symbols
	}).(pulumi.BoolPtrOutput)
}

type ItemSectionMap struct {
	// A map of custom fields in the section, keyed by field label.
	FieldMap map[string]ItemSectionMapFieldMap `pulumi:"fieldMap"`
	// A unique identifier for the section.
	Id *string `pulumi:"id"`
}

// ItemSectionMapInput is an input type that accepts ItemSectionMap and ItemSectionMapOutput values.
// You can construct a concrete instance of `ItemSectionMapInput` via:
//
//	ItemSectionMap{ "key": ItemSectionArgs{...} }
type ItemSectionMapInput interface {
	pulumi.Input

	ToItemSectionMapOutput() ItemSectionMapOutput
	ToItemSectionMapOutputWithContext(context.Context) ItemSectionMapOutput
}

type ItemSectionMapArgs struct {
	// A map of custom fields in the section, keyed by field label.
	FieldMap ItemSectionMapFieldMapMapInput `pulumi:"fieldMap"`
	// A unique identifier for the section.
	Id pulumi.StringPtrInput `pulumi:"id"`
}

func (ItemSectionMapArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ItemSectionMap)(nil)).Elem()
}

func (i ItemSectionMapArgs) ToItemSectionMapOutput() ItemSectionMapOutput {
	return i.ToItemSectionMapOutputWithContext(context.Background())
}

func (i ItemSectionMapArgs) ToItemSectionMapOutputWithContext(ctx context.Context) ItemSectionMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ItemSectionMapOutput)
}

// ItemSectionMapMapInput is an input type that accepts ItemSectionMapMap and ItemSectionMapMapOutput values.
// You can construct a concrete instance of `ItemSectionMapMapInput` via:
//
//	ItemSectionMapMap{ "key": ItemSectionMapArgs{...} }
type ItemSectionMapMapInput interface {
	pulumi.Input

	ToItemSectionMapMapOutput() ItemSectionMapMapOutput
	ToItemSectionMapMapOutputWithContext(context.Context) ItemSectionMapMapOutput
}

type ItemSectionMapMap map[string]ItemSectionMapInput

func (ItemSectionMapMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]ItemSectionMap)(nil)).Elem()
}

func (i ItemSectionMapMap) ToItemSectionMapMapOutput() ItemSectionMapMapOutput {
	return i.ToItemSectionMapMapOutputWithContext(context.Background())
}

func (i ItemSectionMapMap) ToItemSectionMapMapOutputWithContext(ctx context.Context) ItemSectionMapMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ItemSectionMapMapOutput)
}

type ItemSectionMapOutput struct{ *pulumi.OutputState }

func (ItemSectionMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ItemSectionMap)(nil)).Elem()
}

func (o ItemSectionMapOutput) ToItemSectionMapOutput() ItemSectionMapOutput {
	return o
}

func (o ItemSectionMapOutput) ToItemSectionMapOutputWithContext(ctx context.Context) ItemSectionMapOutput {
	return o
}

// A map of custom fields in the section, keyed by field label.
func (o ItemSectionMapOutput) FieldMap() ItemSectionMapFieldMapMapOutput {
	return o.ApplyT(func(v ItemSectionMap) map[string]ItemSectionMapFieldMap { return v.FieldMap }).(ItemSectionMapFieldMapMapOutput)
}

// A unique identifier for the section.
func (o ItemSectionMapOutput) Id() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ItemSectionMap) *string { return v.Id }).(pulumi.StringPtrOutput)
}

type ItemSectionMapMapOutput struct{ *pulumi.OutputState }

func (ItemSectionMapMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]ItemSectionMap)(nil)).Elem()
}

func (o ItemSectionMapMapOutput) ToItemSectionMapMapOutput() ItemSectionMapMapOutput {
	return o
}

func (o ItemSectionMapMapOutput) ToItemSectionMapMapOutputWithContext(ctx context.Context) ItemSectionMapMapOutput {
	return o
}

func (o ItemSectionMapMapOutput) MapIndex(k pulumi.StringInput) ItemSectionMapOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) ItemSectionMap {
		return vs[0].(map[string]ItemSectionMap)[vs[1].(string)]
	}).(ItemSectionMapOutput)
}

type ItemSectionMapFieldMap struct {
	// A unique identifier for the field.
	Id *string `pulumi:"id"`
	// The recipe used to generate a new value for a password.
	PasswordRecipe *ItemSectionMapFieldMapPasswordRecipe `pulumi:"passwordRecipe"`
	// The type of value stored in the field. One of ["STRING" "CONCEALED" "EMAIL" "URL" "OTP" "DATE" "MONTH_YEAR" "MENU"]
	Type *string `pulumi:"type"`
	// The value of the field.
	Value *string `pulumi:"value"`
}

// ItemSectionMapFieldMapInput is an input type that accepts ItemSectionMapFieldMap and ItemSectionMapFieldMapOutput values.
// You can construct a concrete instance of `ItemSectionMapFieldMapInput` via:
//
//	ItemSectionMapFieldMap{ "key": ItemSectionMapFieldArgs{...} }
type ItemSectionMapFieldMapInput interface {
	pulumi.Input

	ToItemSectionMapFieldMapOutput() ItemSectionMapFieldMapOutput
	ToItemSectionMapFieldMapOutputWithContext(context.Context) ItemSectionMapFieldMapOutput
}

type ItemSectionMapFieldMapArgs struct {
	// A unique identifier for the field.
	Id pulumi.StringPtrInput `pulumi:"id"`
	// The recipe used to generate a new value for a password.
	PasswordRecipe ItemSectionMapFieldMapPasswordRecipePtrInput `pulumi:"passwordRecipe"`
	// The type of value stored in the field. One of ["STRING" "CONCEALED" "EMAIL" "URL" "OTP" "DATE" "MONTH_YEAR" "MENU"]
	Type pulumi.StringPtrInput `pulumi:"type"`
	// The value of the field.
	Value pulumi.StringPtrInput `pulumi:"value"`
}

func (ItemSectionMapFieldMapArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ItemSectionMapFieldMap)(nil)).Elem()
}

func (i ItemSectionMapFieldMapArgs) ToItemSectionMapFieldMapOutput() ItemSectionMapFieldMapOutput {
	return i.ToItemSectionMapFieldMapOutputWithContext(context.Background())
}

func (i ItemSectionMapFieldMapArgs) ToItemSectionMapFieldMapOutputWithContext(ctx context.Context) ItemSectionMapFieldMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ItemSectionMapFieldMapOutput)
}

// ItemSectionMapFieldMapMapInput is an input type that accepts ItemSectionMapFieldMapMap and ItemSectionMapFieldMapMapOutput values.
// You can construct a concrete instance of `ItemSectionMapFieldMapMapInput` via:
//
//	ItemSectionMapFieldMapMap{ "key": ItemSectionMapFieldMapArgs{...} }
type ItemSectionMapFieldMapMapInput interface {
	pulumi.Input

	ToItemSectionMapFieldMapMapOutput() ItemSectionMapFieldMapMapOutput
	ToItemSectionMapFieldMapMapOutputWithContext(context.Context) ItemSectionMapFieldMapMapOutput
}

type ItemSectionMapFieldMapMap map[string]ItemSectionMapFieldMapInput

func (ItemSectionMapFieldMapMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]ItemSectionMapFieldMap)(nil)).Elem()
}

func (i ItemSectionMapFieldMapMap) ToItemSectionMapFieldMapMapOutput() ItemSectionMapFieldMapMapOutput {
	return i.ToItemSectionMapFieldMapMapOutputWithContext(context.Background())
}

func (i ItemSectionMapFieldMapMap) ToItemSectionMapFieldMapMapOutputWithContext(ctx context.Context) ItemSectionMapFieldMapMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ItemSectionMapFieldMapMapOutput)
}

type ItemSectionMapFieldMapOutput struct{ *pulumi.OutputState }

func (ItemSectionMapFieldMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ItemSectionMapFieldMap)(nil)).Elem()
}

func (o ItemSectionMapFieldMapOutput) ToItemSectionMapFieldMapOutput() ItemSectionMapFieldMapOutput {
	return o
}

func (o ItemSectionMapFieldMapOutput) ToItemSectionMapFieldMapOutputWithContext(ctx context.Context) ItemSectionMapFieldMapOutput {
	return o
}

// A unique identifier for the field.
func (o ItemSectionMapFieldMapOutput) Id() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ItemSectionMapFieldMap) *string { return v.Id }).(pulumi.StringPtrOutput)
}

// The recipe used to generate a new value for a password.
func (o ItemSectionMapFieldMapOutput) PasswordRecipe() ItemSectionMapFieldMapPasswordRecipePtrOutput {
	return o.ApplyT(func(v ItemSectionMapFieldMap) *ItemSectionMapFieldMapPasswordRecipe { return v.PasswordRecipe }).(ItemSectionMapFieldMapPasswordRecipePtrOutput)
}

// The type of value stored in the field. One of ["STRING" "CONCEALED" "EMAIL" "URL" "OTP" "DATE" "MONTH_YEAR" "MENU"]
func (o ItemSectionMapFieldMapOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ItemSectionMapFieldMap) *string { return v.Type }).(pulumi.StringPtrOutput)
}

// The value of the field.
func (o ItemSectionMapFieldMapOutput) Value() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ItemSectionMapFieldMap) *string { return v.Value }).(pulumi.StringPtrOutput)
}

type ItemSectionMapFieldMapMapOutput struct{ *pulumi.OutputState }

func (ItemSectionMapFieldMapMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]ItemSectionMapFieldMap)(nil)).Elem()
}

func (o ItemSectionMapFieldMapMapOutput) ToItemSectionMapFieldMapMapOutput() ItemSectionMapFieldMapMapOutput {
	return o
}

func (o ItemSectionMapFieldMapMapOutput) ToItemSectionMapFieldMapMapOutputWithContext(ctx context.Context) ItemSectionMapFieldMapMapOutput {
	return o
}

func (o ItemSectionMapFieldMapMapOutput) MapIndex(k pulumi.StringInput) ItemSectionMapFieldMapOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) ItemSectionMapFieldMap {
		return vs[0].(map[string]ItemSectionMapFieldMap)[vs[1].(string)]
	}).(ItemSectionMapFieldMapOutput)
}

type ItemSectionMapFieldMapPasswordRecipe struct {
	// Use digits [0-9] when generating the password.
	Digits *bool `pulumi:"digits"`
	// The length of the password to be generated.
	Length *int `pulumi:"length"`
	// Use symbols [!@.-_*] when generating the password.
	Symbols *bool `pulumi:"symbols"`
}

// ItemSectionMapFieldMapPasswordRecipeInput is an input type that accepts ItemSectionMapFieldMapPasswordRecipeArgs and ItemSectionMapFieldMapPasswordRecipeOutput values.
// You can construct a concrete instance of `ItemSectionMapFieldMapPasswordRecipeInput` via:
//
//	ItemSectionMapFieldMapPasswordRecipeArgs{...}
type ItemSectionMapFieldMapPasswordRecipeInput interface {
	pulumi.Input

	ToItemSectionMapFieldMapPasswordRecipeOutput() ItemSectionMapFieldMapPasswordRecipeOutput
	ToItemSectionMapFieldMapPasswordRecipeOutputWithContext(context.Context) ItemSectionMapFieldMapPasswordRecipeOutput
}

type ItemSectionMapFieldMapPasswordRecipeArgs struct {
	// Use digits [0-9] when generating the password.
	Digits pulumi.BoolPtrInput `pulumi:"digits"`
	// The length of the password to be generated.
	Length pulumi.IntPtrInput `pulumi:"length"`
	// Use symbols [!@.-_*] when generating the password.
	Symbols pulumi.BoolPtrInput `pulumi:"symbols"`
}

func (ItemSectionMapFieldMapPasswordRecipeArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ItemSectionMapFieldMapPasswordRecipe)(nil)).Elem()
}

func (i ItemSectionMapFieldMapPasswordRecipeArgs) ToItemSectionMapFieldMapPasswordRecipeOutput() ItemSectionMapFieldMapPasswordRecipeOutput {
	return i.ToItemSectionMapFieldMapPasswordRecipeOutputWithContext(context.Background())
}

func (i ItemSectionMapFieldMapPasswordRecipeArgs) ToItemSectionMapFieldMapPasswordRecipeOutputWithContext(ctx context.Context) ItemSectionMapFieldMapPasswordRecipeOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ItemSectionMapFieldMapPasswordRecipeOutput)
}

func (i ItemSectionMapFieldMapPasswordRecipeArgs) ToItemSectionMapFieldMapPasswordRecipePtrOutput() ItemSectionMapFieldMapPasswordRecipePtrOutput {
	return i.ToItemSectionMapFieldMapPasswordRecipePtrOutputWithContext(context.Background())
}

func (i ItemSectionMapFieldMapPasswordRecipeArgs) ToItemSectionMapFieldMapPasswordRecipePtrOutputWithContext(ctx context.Context) ItemSectionMapFieldMapPasswordRecipePtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ItemSectionMapFieldMapPasswordRecipeOutput).ToItemSectionMapFieldMapPasswordRecipePtrOutputWithContext(ctx)
}

// ItemSectionMapFieldMapPasswordRecipePtrInput is an input type that accepts ItemSectionMapFieldMapPasswordRecipeArgs, ItemSectionMapFieldMapPasswordRecipePtr and ItemSectionMapFieldMapPasswordRecipePtrOutput values.
// You can construct a concrete instance of `ItemSectionMapFieldMapPasswordRecipePtrInput` via:
//
//	        ItemSectionMapFieldMapPasswordRecipeArgs{...}
//
//	or:
//
//	        nil
type ItemSectionMapFieldMapPasswordRecipePtrInput interface {
	pulumi.Input

	ToItemSectionMapFieldMapPasswordRecipePtrOutput() ItemSectionMapFieldMapPasswordRecipePtrOutput
	ToItemSectionMapFieldMapPasswordRecipePtrOutputWithContext(context.Context) ItemSectionMapFieldMapPasswordRecipePtrOutput
}

type itemSectionMapFieldMapPasswordRecipePtrType ItemSectionMapFieldMapPasswordRecipeArgs

func ItemSectionMapFieldMapPasswordRecipePtr(v *ItemSectionMapFieldMapPasswordRecipeArgs) ItemSectionMapFieldMapPasswordRecipePtrInput {
	return (*itemSectionMapFieldMapPasswordRecipePtrType)(v)
}

func (*itemSectionMapFieldMapPasswordRecipePtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**ItemSectionMapFieldMapPasswordRecipe)(nil)).Elem()
}

func (i *itemSectionMapFieldMapPasswordRecipePtrType) ToItemSectionMapFieldMapPasswordRecipePtrOutput() ItemSectionMapFieldMapPasswordRecipePtrOutput {
	return i.ToItemSectionMapFieldMapPasswordRecipePtrOutputWithContext(context.Background())
}

func (i *itemSectionMapFieldMapPasswordRecipePtrType) ToItemSectionMapFieldMapPasswordRecipePtrOutputWithContext(ctx context.Context) ItemSectionMapFieldMapPasswordRecipePtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ItemSectionMapFieldMapPasswordRecipePtrOutput)
}

type ItemSectionMapFieldMapPasswordRecipeOutput struct{ *pulumi.OutputState }

func (ItemSectionMapFieldMapPasswordRecipeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ItemSectionMapFieldMapPasswordRecipe)(nil)).Elem()
}

func (o ItemSectionMapFieldMapPasswordRecipeOutput) ToItemSectionMapFieldMapPasswordRecipeOutput() ItemSectionMapFieldMapPasswordRecipeOutput {
	return o
}

func (o ItemSectionMapFieldMapPasswordRecipeOutput) ToItemSectionMapFieldMapPasswordRecipeOutputWithContext(ctx context.Context) ItemSectionMapFieldMapPasswordRecipeOutput {
	return o
}

func (o ItemSectionMapFieldMapPasswordRecipeOutput) ToItemSectionMapFieldMapPasswordRecipePtrOutput() ItemSectionMapFieldMapPasswordRecipePtrOutput {
	return o.ToItemSectionMapFieldMapPasswordRecipePtrOutputWithContext(context.Background())
}

func (o ItemSectionMapFieldMapPasswordRecipeOutput) ToItemSectionMapFieldMapPasswordRecipePtrOutputWithContext(ctx context.Context) ItemSectionMapFieldMapPasswordRecipePtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v ItemSectionMapFieldMapPasswordRecipe) *ItemSectionMapFieldMapPasswordRecipe {
		return &v
	}).(ItemSectionMapFieldMapPasswordRecipePtrOutput)
}

// Use digits [0-9] when generating the password.
func (o ItemSectionMapFieldMapPasswordRecipeOutput) Digits() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v ItemSectionMapFieldMapPasswordRecipe) *bool { return v.Digits }).(pulumi.BoolPtrOutput)
}

// The length of the password to be generated.
func (o ItemSectionMapFieldMapPasswordRecipeOutput) Length() pulumi.IntPtrOutput {
	return o.ApplyT(func(v ItemSectionMapFieldMapPasswordRecipe) *int { return v.Length }).(pulumi.IntPtrOutput)
}

// Use symbols [!@.-_*] when generating the password.
func (o ItemSectionMapFieldMapPasswordRecipeOutput) Symbols() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v ItemSectionMapFieldMapPasswordRecipe) *bool { return v.Symbols }).(pulumi.BoolPtrOutput)
}

type ItemSectionMapFieldMapPasswordRecipePtrOutput struct{ *pulumi.OutputState }

func (ItemSectionMapFieldMapPasswordRecipePtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ItemSectionMapFieldMapPasswordRecipe)(nil)).Elem()
}

func (o ItemSectionMapFieldMapPasswordRecipePtrOutput) ToItemSectionMapFieldMapPasswordRecipePtrOutput() ItemSectionMapFieldMapPasswordRecipePtrOutput {
	return o
}

func (o ItemSectionMapFieldMapPasswordRecipePtrOutput) ToItemSectionMapFieldMapPasswordRecipePtrOutputWithContext(ctx context.Context) ItemSectionMapFieldMapPasswordRecipePtrOutput {
	return o
}

func (o ItemSectionMapFieldMapPasswordRecipePtrOutput) Elem() ItemSectionMapFieldMapPasswordRecipeOutput {
	return o.ApplyT(func(v *ItemSectionMapFieldMapPasswordRecipe) ItemSectionMapFieldMapPasswordRecipe {
		if v != nil {
			return *v
		}
		var ret ItemSectionMapFieldMapPasswordRecipe
		return ret
	}).(ItemSectionMapFieldMapPasswordRecipeOutput)
}

// Use digits [0-9] when generating the password.
func (o ItemSectionMapFieldMapPasswordRecipePtrOutput) Digits() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ItemSectionMapFieldMapPasswordRecipe) *bool {
		if v == nil {
			return nil
		}
		return v.Digits
	}).(pulumi.BoolPtrOutput)
}

// The length of the password to be generated.
func (o ItemSectionMapFieldMapPasswordRecipePtrOutput) Length() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *ItemSectionMapFieldMapPasswordRecipe) *int {
		if v == nil {
			return nil
		}
		return v.Length
	}).(pulumi.IntPtrOutput)
}

// Use symbols [!@.-_*] when generating the password.
func (o ItemSectionMapFieldMapPasswordRecipePtrOutput) Symbols() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ItemSectionMapFieldMapPasswordRecipe) *bool {
		if v == nil {
			return nil
		}
		return v.Symbols
	}).(pulumi.BoolPtrOutput)
}

type GetEnvironmentMetadata struct {
	// Whether the value is hidden by default in the 1Password app.
	Masked bool `pulumi:"masked"`
	// The environment variable name.
	Name string `pulumi:"name"`
	// The environment variable value.
	Value string `pulumi:"value"`
}

// GetEnvironmentMetadataInput is an input type that accepts GetEnvironmentMetadataArgs and GetEnvironmentMetadataOutput values.
// You can construct a concrete instance of `GetEnvironmentMetadataInput` via:
//
//	GetEnvironmentMetadataArgs{...}
type GetEnvironmentMetadataInput interface {
	pulumi.Input

	ToGetEnvironmentMetadataOutput() GetEnvironmentMetadataOutput
	ToGetEnvironmentMetadataOutputWithContext(context.Context) GetEnvironmentMetadataOutput
}

type GetEnvironmentMetadataArgs struct {
	// Whether the value is hidden by default in the 1Password app.
	Masked pulumi.BoolInput `pulumi:"masked"`
	// The environment variable name.
	Name pulumi.StringInput `pulumi:"name"`
	// The environment variable value.
	Value pulumi.StringInput `pulumi:"value"`
}

func (GetEnvironmentMetadataArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetEnvironmentMetadata)(nil)).Elem()
}

func (i GetEnvironmentMetadataArgs) ToGetEnvironmentMetadataOutput() GetEnvironmentMetadataOutput {
	return i.ToGetEnvironmentMetadataOutputWithContext(context.Background())
}

func (i GetEnvironmentMetadataArgs) ToGetEnvironmentMetadataOutputWithContext(ctx context.Context) GetEnvironmentMetadataOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetEnvironmentMetadataOutput)
}

// GetEnvironmentMetadataArrayInput is an input type that accepts GetEnvironmentMetadataArray and GetEnvironmentMetadataArrayOutput values.
// You can construct a concrete instance of `GetEnvironmentMetadataArrayInput` via:
//
//	GetEnvironmentMetadataArray{ GetEnvironmentMetadataArgs{...} }
type GetEnvironmentMetadataArrayInput interface {
	pulumi.Input

	ToGetEnvironmentMetadataArrayOutput() GetEnvironmentMetadataArrayOutput
	ToGetEnvironmentMetadataArrayOutputWithContext(context.Context) GetEnvironmentMetadataArrayOutput
}

type GetEnvironmentMetadataArray []GetEnvironmentMetadataInput

func (GetEnvironmentMetadataArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetEnvironmentMetadata)(nil)).Elem()
}

func (i GetEnvironmentMetadataArray) ToGetEnvironmentMetadataArrayOutput() GetEnvironmentMetadataArrayOutput {
	return i.ToGetEnvironmentMetadataArrayOutputWithContext(context.Background())
}

func (i GetEnvironmentMetadataArray) ToGetEnvironmentMetadataArrayOutputWithContext(ctx context.Context) GetEnvironmentMetadataArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetEnvironmentMetadataArrayOutput)
}

type GetEnvironmentMetadataOutput struct{ *pulumi.OutputState }

func (GetEnvironmentMetadataOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetEnvironmentMetadata)(nil)).Elem()
}

func (o GetEnvironmentMetadataOutput) ToGetEnvironmentMetadataOutput() GetEnvironmentMetadataOutput {
	return o
}

func (o GetEnvironmentMetadataOutput) ToGetEnvironmentMetadataOutputWithContext(ctx context.Context) GetEnvironmentMetadataOutput {
	return o
}

// Whether the value is hidden by default in the 1Password app.
func (o GetEnvironmentMetadataOutput) Masked() pulumi.BoolOutput {
	return o.ApplyT(func(v GetEnvironmentMetadata) bool { return v.Masked }).(pulumi.BoolOutput)
}

// The environment variable name.
func (o GetEnvironmentMetadataOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetEnvironmentMetadata) string { return v.Name }).(pulumi.StringOutput)
}

// The environment variable value.
func (o GetEnvironmentMetadataOutput) Value() pulumi.StringOutput {
	return o.ApplyT(func(v GetEnvironmentMetadata) string { return v.Value }).(pulumi.StringOutput)
}

type GetEnvironmentMetadataArrayOutput struct{ *pulumi.OutputState }

func (GetEnvironmentMetadataArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetEnvironmentMetadata)(nil)).Elem()
}

func (o GetEnvironmentMetadataArrayOutput) ToGetEnvironmentMetadataArrayOutput() GetEnvironmentMetadataArrayOutput {
	return o
}

func (o GetEnvironmentMetadataArrayOutput) ToGetEnvironmentMetadataArrayOutputWithContext(ctx context.Context) GetEnvironmentMetadataArrayOutput {
	return o
}

func (o GetEnvironmentMetadataArrayOutput) Index(i pulumi.IntInput) GetEnvironmentMetadataOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetEnvironmentMetadata {
		return vs[0].([]GetEnvironmentMetadata)[vs[1].(int)]
	}).(GetEnvironmentMetadataOutput)
}

type GetItemFile struct {
	// The content of the file.
	Content string `pulumi:"content"`
	// The content of the file in base64 encoding. (Use this for binary files.)
	ContentBase64 string `pulumi:"contentBase64"`
	// The UUID of the file.
	Id string `pulumi:"id"`
	// The name of the file.
	Name string `pulumi:"name"`
}

// GetItemFileInput is an input type that accepts GetItemFileArgs and GetItemFileOutput values.
// You can construct a concrete instance of `GetItemFileInput` via:
//
//	GetItemFileArgs{...}
type GetItemFileInput interface {
	pulumi.Input

	ToGetItemFileOutput() GetItemFileOutput
	ToGetItemFileOutputWithContext(context.Context) GetItemFileOutput
}

type GetItemFileArgs struct {
	// The content of the file.
	Content pulumi.StringInput `pulumi:"content"`
	// The content of the file in base64 encoding. (Use this for binary files.)
	ContentBase64 pulumi.StringInput `pulumi:"contentBase64"`
	// The UUID of the file.
	Id pulumi.StringInput `pulumi:"id"`
	// The name of the file.
	Name pulumi.StringInput `pulumi:"name"`
}

func (GetItemFileArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetItemFile)(nil)).Elem()
}

func (i GetItemFileArgs) ToGetItemFileOutput() GetItemFileOutput {
	return i.ToGetItemFileOutputWithContext(context.Background())
}

func (i GetItemFileArgs) ToGetItemFileOutputWithContext(ctx context.Context) GetItemFileOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetItemFileOutput)
}

// GetItemFileArrayInput is an input type that accepts GetItemFileArray and GetItemFileArrayOutput values.
// You can construct a concrete instance of `GetItemFileArrayInput` via:
//
//	GetItemFileArray{ GetItemFileArgs{...} }
type GetItemFileArrayInput interface {
	pulumi.Input

	ToGetItemFileArrayOutput() GetItemFileArrayOutput
	ToGetItemFileArrayOutputWithContext(context.Context) GetItemFileArrayOutput
}

type GetItemFileArray []GetItemFileInput

func (GetItemFileArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetItemFile)(nil)).Elem()
}

func (i GetItemFileArray) ToGetItemFileArrayOutput() GetItemFileArrayOutput {
	return i.ToGetItemFileArrayOutputWithContext(context.Background())
}

func (i GetItemFileArray) ToGetItemFileArrayOutputWithContext(ctx context.Context) GetItemFileArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetItemFileArrayOutput)
}

type GetItemFileOutput struct{ *pulumi.OutputState }

func (GetItemFileOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetItemFile)(nil)).Elem()
}

func (o GetItemFileOutput) ToGetItemFileOutput() GetItemFileOutput {
	return o
}

func (o GetItemFileOutput) ToGetItemFileOutputWithContext(ctx context.Context) GetItemFileOutput {
	return o
}

// The content of the file.
func (o GetItemFileOutput) Content() pulumi.StringOutput {
	return o.ApplyT(func(v GetItemFile) string { return v.Content }).(pulumi.StringOutput)
}

// The content of the file in base64 encoding. (Use this for binary files.)
func (o GetItemFileOutput) ContentBase64() pulumi.StringOutput {
	return o.ApplyT(func(v GetItemFile) string { return v.ContentBase64 }).(pulumi.StringOutput)
}

// The UUID of the file.
func (o GetItemFileOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetItemFile) string { return v.Id }).(pulumi.StringOutput)
}

// The name of the file.
func (o GetItemFileOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetItemFile) string { return v.Name }).(pulumi.StringOutput)
}

type GetItemFileArrayOutput struct{ *pulumi.OutputState }

func (GetItemFileArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetItemFile)(nil)).Elem()
}

func (o GetItemFileArrayOutput) ToGetItemFileArrayOutput() GetItemFileArrayOutput {
	return o
}

func (o GetItemFileArrayOutput) ToGetItemFileArrayOutputWithContext(ctx context.Context) GetItemFileArrayOutput {
	return o
}

func (o GetItemFileArrayOutput) Index(i pulumi.IntInput) GetItemFileOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetItemFile {
		return vs[0].([]GetItemFile)[vs[1].(int)]
	}).(GetItemFileOutput)
}

type GetItemSection struct {
	// A list of custom fields in the section
	Fields []GetItemSectionField `pulumi:"fields"`
	// A list of files attached to the section.
	Files []GetItemSectionFile `pulumi:"files"`
	// A unique identifier for the section.
	Id string `pulumi:"id"`
	// The label for the section.
	Label string `pulumi:"label"`
}

// GetItemSectionInput is an input type that accepts GetItemSectionArgs and GetItemSectionOutput values.
// You can construct a concrete instance of `GetItemSectionInput` via:
//
//	GetItemSectionArgs{...}
type GetItemSectionInput interface {
	pulumi.Input

	ToGetItemSectionOutput() GetItemSectionOutput
	ToGetItemSectionOutputWithContext(context.Context) GetItemSectionOutput
}

type GetItemSectionArgs struct {
	// A list of custom fields in the section
	Fields GetItemSectionFieldArrayInput `pulumi:"fields"`
	// A list of files attached to the section.
	Files GetItemSectionFileArrayInput `pulumi:"files"`
	// A unique identifier for the section.
	Id pulumi.StringInput `pulumi:"id"`
	// The label for the section.
	Label pulumi.StringInput `pulumi:"label"`
}

func (GetItemSectionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetItemSection)(nil)).Elem()
}

func (i GetItemSectionArgs) ToGetItemSectionOutput() GetItemSectionOutput {
	return i.ToGetItemSectionOutputWithContext(context.Background())
}

func (i GetItemSectionArgs) ToGetItemSectionOutputWithContext(ctx context.Context) GetItemSectionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetItemSectionOutput)
}

// GetItemSectionArrayInput is an input type that accepts GetItemSectionArray and GetItemSectionArrayOutput values.
// You can construct a concrete instance of `GetItemSectionArrayInput` via:
//
//	GetItemSectionArray{ GetItemSectionArgs{...} }
type GetItemSectionArrayInput interface {
	pulumi.Input

	ToGetItemSectionArrayOutput() GetItemSectionArrayOutput
	ToGetItemSectionArrayOutputWithContext(context.Context) GetItemSectionArrayOutput
}

type GetItemSectionArray []GetItemSectionInput

func (GetItemSectionArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetItemSection)(nil)).Elem()
}

func (i GetItemSectionArray) ToGetItemSectionArrayOutput() GetItemSectionArrayOutput {
	return i.ToGetItemSectionArrayOutputWithContext(context.Background())
}

func (i GetItemSectionArray) ToGetItemSectionArrayOutputWithContext(ctx context.Context) GetItemSectionArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetItemSectionArrayOutput)
}

type GetItemSectionOutput struct{ *pulumi.OutputState }

func (GetItemSectionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetItemSection)(nil)).Elem()
}

func (o GetItemSectionOutput) ToGetItemSectionOutput() GetItemSectionOutput {
	return o
}

func (o GetItemSectionOutput) ToGetItemSectionOutputWithContext(ctx context.Context) GetItemSectionOutput {
	return o
}

// A list of custom fields in the section
func (o GetItemSectionOutput) Fields() GetItemSectionFieldArrayOutput {
	return o.ApplyT(func(v GetItemSection) []GetItemSectionField { return v.Fields }).(GetItemSectionFieldArrayOutput)
}

// A list of files attached to the section.
func (o GetItemSectionOutput) Files() GetItemSectionFileArrayOutput {
	return o.ApplyT(func(v GetItemSection) []GetItemSectionFile { return v.Files }).(GetItemSectionFileArrayOutput)
}

// A unique identifier for the section.
func (o GetItemSectionOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetItemSection) string { return v.Id }).(pulumi.StringOutput)
}

// The label for the section.
func (o GetItemSectionOutput) Label() pulumi.StringOutput {
	return o.ApplyT(func(v GetItemSection) string { return v.Label }).(pulumi.StringOutput)
}

type GetItemSectionArrayOutput struct{ *pulumi.OutputState }

func (GetItemSectionArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetItemSection)(nil)).Elem()
}

func (o GetItemSectionArrayOutput) ToGetItemSectionArrayOutput() GetItemSectionArrayOutput {
	return o
}

func (o GetItemSectionArrayOutput) ToGetItemSectionArrayOutputWithContext(ctx context.Context) GetItemSectionArrayOutput {
	return o
}

func (o GetItemSectionArrayOutput) Index(i pulumi.IntInput) GetItemSectionOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetItemSection {
		return vs[0].([]GetItemSection)[vs[1].(int)]
	}).(GetItemSectionOutput)
}

type GetItemSectionField struct {
	// A unique identifier for the field.
	Id string `pulumi:"id"`
	// The label for the field.
	Label string `pulumi:"label"`
	// The type of value stored in the field. One of ["STRING" "CONCEALED" "EMAIL" "URL" "OTP" "DATE" "MONTH_YEAR" "MENU"]
	Type string `pulumi:"type"`
	// The value of the field.
	Value string `pulumi:"value"`
}

// GetItemSectionFieldInput is an input type that accepts GetItemSectionFieldArgs and GetItemSectionFieldOutput values.
// You can construct a concrete instance of `GetItemSectionFieldInput` via:
//
//	GetItemSectionFieldArgs{...}
type GetItemSectionFieldInput interface {
	pulumi.Input

	ToGetItemSectionFieldOutput() GetItemSectionFieldOutput
	ToGetItemSectionFieldOutputWithContext(context.Context) GetItemSectionFieldOutput
}

type GetItemSectionFieldArgs struct {
	// A unique identifier for the field.
	Id pulumi.StringInput `pulumi:"id"`
	// The label for the field.
	Label pulumi.StringInput `pulumi:"label"`
	// The type of value stored in the field. One of ["STRING" "CONCEALED" "EMAIL" "URL" "OTP" "DATE" "MONTH_YEAR" "MENU"]
	Type pulumi.StringInput `pulumi:"type"`
	// The value of the field.
	Value pulumi.StringInput `pulumi:"value"`
}

func (GetItemSectionFieldArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetItemSectionField)(nil)).Elem()
}

func (i GetItemSectionFieldArgs) ToGetItemSectionFieldOutput() GetItemSectionFieldOutput {
	return i.ToGetItemSectionFieldOutputWithContext(context.Background())
}

func (i GetItemSectionFieldArgs) ToGetItemSectionFieldOutputWithContext(ctx context.Context) GetItemSectionFieldOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetItemSectionFieldOutput)
}

// GetItemSectionFieldArrayInput is an input type that accepts GetItemSectionFieldArray and GetItemSectionFieldArrayOutput values.
// You can construct a concrete instance of `GetItemSectionFieldArrayInput` via:
//
//	GetItemSectionFieldArray{ GetItemSectionFieldArgs{...} }
type GetItemSectionFieldArrayInput interface {
	pulumi.Input

	ToGetItemSectionFieldArrayOutput() GetItemSectionFieldArrayOutput
	ToGetItemSectionFieldArrayOutputWithContext(context.Context) GetItemSectionFieldArrayOutput
}

type GetItemSectionFieldArray []GetItemSectionFieldInput

func (GetItemSectionFieldArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetItemSectionField)(nil)).Elem()
}

func (i GetItemSectionFieldArray) ToGetItemSectionFieldArrayOutput() GetItemSectionFieldArrayOutput {
	return i.ToGetItemSectionFieldArrayOutputWithContext(context.Background())
}

func (i GetItemSectionFieldArray) ToGetItemSectionFieldArrayOutputWithContext(ctx context.Context) GetItemSectionFieldArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetItemSectionFieldArrayOutput)
}

type GetItemSectionFieldOutput struct{ *pulumi.OutputState }

func (GetItemSectionFieldOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetItemSectionField)(nil)).Elem()
}

func (o GetItemSectionFieldOutput) ToGetItemSectionFieldOutput() GetItemSectionFieldOutput {
	return o
}

func (o GetItemSectionFieldOutput) ToGetItemSectionFieldOutputWithContext(ctx context.Context) GetItemSectionFieldOutput {
	return o
}

// A unique identifier for the field.
func (o GetItemSectionFieldOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetItemSectionField) string { return v.Id }).(pulumi.StringOutput)
}

// The label for the field.
func (o GetItemSectionFieldOutput) Label() pulumi.StringOutput {
	return o.ApplyT(func(v GetItemSectionField) string { return v.Label }).(pulumi.StringOutput)
}

// The type of value stored in the field. One of ["STRING" "CONCEALED" "EMAIL" "URL" "OTP" "DATE" "MONTH_YEAR" "MENU"]
func (o GetItemSectionFieldOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v GetItemSectionField) string { return v.Type }).(pulumi.StringOutput)
}

// The value of the field.
func (o GetItemSectionFieldOutput) Value() pulumi.StringOutput {
	return o.ApplyT(func(v GetItemSectionField) string { return v.Value }).(pulumi.StringOutput)
}

type GetItemSectionFieldArrayOutput struct{ *pulumi.OutputState }

func (GetItemSectionFieldArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetItemSectionField)(nil)).Elem()
}

func (o GetItemSectionFieldArrayOutput) ToGetItemSectionFieldArrayOutput() GetItemSectionFieldArrayOutput {
	return o
}

func (o GetItemSectionFieldArrayOutput) ToGetItemSectionFieldArrayOutputWithContext(ctx context.Context) GetItemSectionFieldArrayOutput {
	return o
}

func (o GetItemSectionFieldArrayOutput) Index(i pulumi.IntInput) GetItemSectionFieldOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetItemSectionField {
		return vs[0].([]GetItemSectionField)[vs[1].(int)]
	}).(GetItemSectionFieldOutput)
}

type GetItemSectionFile struct {
	// The content of the file.
	Content string `pulumi:"content"`
	// The content of the file in base64 encoding. (Use this for binary files.)
	ContentBase64 string `pulumi:"contentBase64"`
	// The UUID of the file.
	Id string `pulumi:"id"`
	// The name of the file.
	Name string `pulumi:"name"`
}

// GetItemSectionFileInput is an input type that accepts GetItemSectionFileArgs and GetItemSectionFileOutput values.
// You can construct a concrete instance of `GetItemSectionFileInput` via:
//
//	GetItemSectionFileArgs{...}
type GetItemSectionFileInput interface {
	pulumi.Input

	ToGetItemSectionFileOutput() GetItemSectionFileOutput
	ToGetItemSectionFileOutputWithContext(context.Context) GetItemSectionFileOutput
}

type GetItemSectionFileArgs struct {
	// The content of the file.
	Content pulumi.StringInput `pulumi:"content"`
	// The content of the file in base64 encoding. (Use this for binary files.)
	ContentBase64 pulumi.StringInput `pulumi:"contentBase64"`
	// The UUID of the file.
	Id pulumi.StringInput `pulumi:"id"`
	// The name of the file.
	Name pulumi.StringInput `pulumi:"name"`
}

func (GetItemSectionFileArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetItemSectionFile)(nil)).Elem()
}

func (i GetItemSectionFileArgs) ToGetItemSectionFileOutput() GetItemSectionFileOutput {
	return i.ToGetItemSectionFileOutputWithContext(context.Background())
}

func (i GetItemSectionFileArgs) ToGetItemSectionFileOutputWithContext(ctx context.Context) GetItemSectionFileOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetItemSectionFileOutput)
}

// GetItemSectionFileArrayInput is an input type that accepts GetItemSectionFileArray and GetItemSectionFileArrayOutput values.
// You can construct a concrete instance of `GetItemSectionFileArrayInput` via:
//
//	GetItemSectionFileArray{ GetItemSectionFileArgs{...} }
type GetItemSectionFileArrayInput interface {
	pulumi.Input

	ToGetItemSectionFileArrayOutput() GetItemSectionFileArrayOutput
	ToGetItemSectionFileArrayOutputWithContext(context.Context) GetItemSectionFileArrayOutput
}

type GetItemSectionFileArray []GetItemSectionFileInput

func (GetItemSectionFileArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetItemSectionFile)(nil)).Elem()
}

func (i GetItemSectionFileArray) ToGetItemSectionFileArrayOutput() GetItemSectionFileArrayOutput {
	return i.ToGetItemSectionFileArrayOutputWithContext(context.Background())
}

func (i GetItemSectionFileArray) ToGetItemSectionFileArrayOutputWithContext(ctx context.Context) GetItemSectionFileArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetItemSectionFileArrayOutput)
}

type GetItemSectionFileOutput struct{ *pulumi.OutputState }

func (GetItemSectionFileOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetItemSectionFile)(nil)).Elem()
}

func (o GetItemSectionFileOutput) ToGetItemSectionFileOutput() GetItemSectionFileOutput {
	return o
}

func (o GetItemSectionFileOutput) ToGetItemSectionFileOutputWithContext(ctx context.Context) GetItemSectionFileOutput {
	return o
}

// The content of the file.
func (o GetItemSectionFileOutput) Content() pulumi.StringOutput {
	return o.ApplyT(func(v GetItemSectionFile) string { return v.Content }).(pulumi.StringOutput)
}

// The content of the file in base64 encoding. (Use this for binary files.)
func (o GetItemSectionFileOutput) ContentBase64() pulumi.StringOutput {
	return o.ApplyT(func(v GetItemSectionFile) string { return v.ContentBase64 }).(pulumi.StringOutput)
}

// The UUID of the file.
func (o GetItemSectionFileOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetItemSectionFile) string { return v.Id }).(pulumi.StringOutput)
}

// The name of the file.
func (o GetItemSectionFileOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetItemSectionFile) string { return v.Name }).(pulumi.StringOutput)
}

type GetItemSectionFileArrayOutput struct{ *pulumi.OutputState }

func (GetItemSectionFileArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetItemSectionFile)(nil)).Elem()
}

func (o GetItemSectionFileArrayOutput) ToGetItemSectionFileArrayOutput() GetItemSectionFileArrayOutput {
	return o
}

func (o GetItemSectionFileArrayOutput) ToGetItemSectionFileArrayOutputWithContext(ctx context.Context) GetItemSectionFileArrayOutput {
	return o
}

func (o GetItemSectionFileArrayOutput) Index(i pulumi.IntInput) GetItemSectionFileOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetItemSectionFile {
		return vs[0].([]GetItemSectionFile)[vs[1].(int)]
	}).(GetItemSectionFileOutput)
}

type GetItemSectionMap struct {
	// A map of custom fields in the section, keyed by field label.
	FieldMap map[string]GetItemSectionMapFieldMap `pulumi:"fieldMap"`
	// A map of files attached to the section, keyed by file label.
	FileMap map[string]GetItemSectionMapFileMap `pulumi:"fileMap"`
	// A unique identifier for the section.
	Id string `pulumi:"id"`
}

// GetItemSectionMapInput is an input type that accepts GetItemSectionMap and GetItemSectionMapOutput values.
// You can construct a concrete instance of `GetItemSectionMapInput` via:
//
//	GetItemSectionMap{ "key": GetItemSectionArgs{...} }
type GetItemSectionMapInput interface {
	pulumi.Input

	ToGetItemSectionMapOutput() GetItemSectionMapOutput
	ToGetItemSectionMapOutputWithContext(context.Context) GetItemSectionMapOutput
}

type GetItemSectionMapArgs struct {
	// A map of custom fields in the section, keyed by field label.
	FieldMap GetItemSectionMapFieldMapMapInput `pulumi:"fieldMap"`
	// A map of files attached to the section, keyed by file label.
	FileMap GetItemSectionMapFileMapMapInput `pulumi:"fileMap"`
	// A unique identifier for the section.
	Id pulumi.StringInput `pulumi:"id"`
}

func (GetItemSectionMapArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetItemSectionMap)(nil)).Elem()
}

func (i GetItemSectionMapArgs) ToGetItemSectionMapOutput() GetItemSectionMapOutput {
	return i.ToGetItemSectionMapOutputWithContext(context.Background())
}

func (i GetItemSectionMapArgs) ToGetItemSectionMapOutputWithContext(ctx context.Context) GetItemSectionMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetItemSectionMapOutput)
}

// GetItemSectionMapMapInput is an input type that accepts GetItemSectionMapMap and GetItemSectionMapMapOutput values.
// You can construct a concrete instance of `GetItemSectionMapMapInput` via:
//
//	GetItemSectionMapMap{ "key": GetItemSectionMapArgs{...} }
type GetItemSectionMapMapInput interface {
	pulumi.Input

	ToGetItemSectionMapMapOutput() GetItemSectionMapMapOutput
	ToGetItemSectionMapMapOutputWithContext(context.Context) GetItemSectionMapMapOutput
}

type GetItemSectionMapMap map[string]GetItemSectionMapInput

func (GetItemSectionMapMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]GetItemSectionMap)(nil)).Elem()
}

func (i GetItemSectionMapMap) ToGetItemSectionMapMapOutput() GetItemSectionMapMapOutput {
	return i.ToGetItemSectionMapMapOutputWithContext(context.Background())
}

func (i GetItemSectionMapMap) ToGetItemSectionMapMapOutputWithContext(ctx context.Context) GetItemSectionMapMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetItemSectionMapMapOutput)
}

type GetItemSectionMapOutput struct{ *pulumi.OutputState }

func (GetItemSectionMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetItemSectionMap)(nil)).Elem()
}

func (o GetItemSectionMapOutput) ToGetItemSectionMapOutput() GetItemSectionMapOutput {
	return o
}

func (o GetItemSectionMapOutput) ToGetItemSectionMapOutputWithContext(ctx context.Context) GetItemSectionMapOutput {
	return o
}

// A map of custom fields in the section, keyed by field label.
func (o GetItemSectionMapOutput) FieldMap() GetItemSectionMapFieldMapMapOutput {
	return o.ApplyT(func(v GetItemSectionMap) map[string]GetItemSectionMapFieldMap { return v.FieldMap }).(GetItemSectionMapFieldMapMapOutput)
}

// A map of files attached to the section, keyed by file label.
func (o GetItemSectionMapOutput) FileMap() GetItemSectionMapFileMapMapOutput {
	return o.ApplyT(func(v GetItemSectionMap) map[string]GetItemSectionMapFileMap { return v.FileMap }).(GetItemSectionMapFileMapMapOutput)
}

// A unique identifier for the section.
func (o GetItemSectionMapOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetItemSectionMap) string { return v.Id }).(pulumi.StringOutput)
}

type GetItemSectionMapMapOutput struct{ *pulumi.OutputState }

func (GetItemSectionMapMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]GetItemSectionMap)(nil)).Elem()
}

func (o GetItemSectionMapMapOutput) ToGetItemSectionMapMapOutput() GetItemSectionMapMapOutput {
	return o
}

func (o GetItemSectionMapMapOutput) ToGetItemSectionMapMapOutputWithContext(ctx context.Context) GetItemSectionMapMapOutput {
	return o
}

func (o GetItemSectionMapMapOutput) MapIndex(k pulumi.StringInput) GetItemSectionMapOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) GetItemSectionMap {
		return vs[0].(map[string]GetItemSectionMap)[vs[1].(string)]
	}).(GetItemSectionMapOutput)
}

type GetItemSectionMapFieldMap struct {
	// A unique identifier for the field.
	Id string `pulumi:"id"`
	// The type of value stored in the field. One of ["STRING" "CONCEALED" "EMAIL" "URL" "OTP" "DATE" "MONTH_YEAR" "MENU"]
	Type string `pulumi:"type"`
	// The value of the field.
	Value string `pulumi:"value"`
}

// GetItemSectionMapFieldMapInput is an input type that accepts GetItemSectionMapFieldMap and GetItemSectionMapFieldMapOutput values.
// You can construct a concrete instance of `GetItemSectionMapFieldMapInput` via:
//
//	GetItemSectionMapFieldMap{ "key": GetItemSectionMapFieldArgs{...} }
type GetItemSectionMapFieldMapInput interface {
	pulumi.Input

	ToGetItemSectionMapFieldMapOutput() GetItemSectionMapFieldMapOutput
	ToGetItemSectionMapFieldMapOutputWithContext(context.Context) GetItemSectionMapFieldMapOutput
}

type GetItemSectionMapFieldMapArgs struct {
	// A unique identifier for the field.
	Id pulumi.StringInput `pulumi:"id"`
	// The type of value stored in the field. One of ["STRING" "CONCEALED" "EMAIL" "URL" "OTP" "DATE" "MONTH_YEAR" "MENU"]
	Type pulumi.StringInput `pulumi:"type"`
	// The value of the field.
	Value pulumi.StringInput `pulumi:"value"`
}

func (GetItemSectionMapFieldMapArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetItemSectionMapFieldMap)(nil)).Elem()
}

func (i GetItemSectionMapFieldMapArgs) ToGetItemSectionMapFieldMapOutput() GetItemSectionMapFieldMapOutput {
	return i.ToGetItemSectionMapFieldMapOutputWithContext(context.Background())
}

func (i GetItemSectionMapFieldMapArgs) ToGetItemSectionMapFieldMapOutputWithContext(ctx context.Context) GetItemSectionMapFieldMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetItemSectionMapFieldMapOutput)
}

// GetItemSectionMapFieldMapMapInput is an input type that accepts GetItemSectionMapFieldMapMap and GetItemSectionMapFieldMapMapOutput values.
// You can construct a concrete instance of `GetItemSectionMapFieldMapMapInput` via:
//
//	GetItemSectionMapFieldMapMap{ "key": GetItemSectionMapFieldMapArgs{...} }
type GetItemSectionMapFieldMapMapInput interface {
	pulumi.Input

	ToGetItemSectionMapFieldMapMapOutput() GetItemSectionMapFieldMapMapOutput
	ToGetItemSectionMapFieldMapMapOutputWithContext(context.Context) GetItemSectionMapFieldMapMapOutput
}

type GetItemSectionMapFieldMapMap map[string]GetItemSectionMapFieldMapInput

func (GetItemSectionMapFieldMapMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]GetItemSectionMapFieldMap)(nil)).Elem()
}

func (i GetItemSectionMapFieldMapMap) ToGetItemSectionMapFieldMapMapOutput() GetItemSectionMapFieldMapMapOutput {
	return i.ToGetItemSectionMapFieldMapMapOutputWithContext(context.Background())
}

func (i GetItemSectionMapFieldMapMap) ToGetItemSectionMapFieldMapMapOutputWithContext(ctx context.Context) GetItemSectionMapFieldMapMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetItemSectionMapFieldMapMapOutput)
}

type GetItemSectionMapFieldMapOutput struct{ *pulumi.OutputState }

func (GetItemSectionMapFieldMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetItemSectionMapFieldMap)(nil)).Elem()
}

func (o GetItemSectionMapFieldMapOutput) ToGetItemSectionMapFieldMapOutput() GetItemSectionMapFieldMapOutput {
	return o
}

func (o GetItemSectionMapFieldMapOutput) ToGetItemSectionMapFieldMapOutputWithContext(ctx context.Context) GetItemSectionMapFieldMapOutput {
	return o
}

// A unique identifier for the field.
func (o GetItemSectionMapFieldMapOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetItemSectionMapFieldMap) string { return v.Id }).(pulumi.StringOutput)
}

// The type of value stored in the field. One of ["STRING" "CONCEALED" "EMAIL" "URL" "OTP" "DATE" "MONTH_YEAR" "MENU"]
func (o GetItemSectionMapFieldMapOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v GetItemSectionMapFieldMap) string { return v.Type }).(pulumi.StringOutput)
}

// The value of the field.
func (o GetItemSectionMapFieldMapOutput) Value() pulumi.StringOutput {
	return o.ApplyT(func(v GetItemSectionMapFieldMap) string { return v.Value }).(pulumi.StringOutput)
}

type GetItemSectionMapFieldMapMapOutput struct{ *pulumi.OutputState }

func (GetItemSectionMapFieldMapMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]GetItemSectionMapFieldMap)(nil)).Elem()
}

func (o GetItemSectionMapFieldMapMapOutput) ToGetItemSectionMapFieldMapMapOutput() GetItemSectionMapFieldMapMapOutput {
	return o
}

func (o GetItemSectionMapFieldMapMapOutput) ToGetItemSectionMapFieldMapMapOutputWithContext(ctx context.Context) GetItemSectionMapFieldMapMapOutput {
	return o
}

func (o GetItemSectionMapFieldMapMapOutput) MapIndex(k pulumi.StringInput) GetItemSectionMapFieldMapOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) GetItemSectionMapFieldMap {
		return vs[0].(map[string]GetItemSectionMapFieldMap)[vs[1].(string)]
	}).(GetItemSectionMapFieldMapOutput)
}

type GetItemSectionMapFileMap struct {
	// The content of the file.
	Content string `pulumi:"content"`
	// The content of the file in base64 encoding. (Use this for binary files.)
	ContentBase64 string `pulumi:"contentBase64"`
	// The UUID of the file.
	Id string `pulumi:"id"`
}

// GetItemSectionMapFileMapInput is an input type that accepts GetItemSectionMapFileMap and GetItemSectionMapFileMapOutput values.
// You can construct a concrete instance of `GetItemSectionMapFileMapInput` via:
//
//	GetItemSectionMapFileMap{ "key": GetItemSectionMapFileArgs{...} }
type GetItemSectionMapFileMapInput interface {
	pulumi.Input

	ToGetItemSectionMapFileMapOutput() GetItemSectionMapFileMapOutput
	ToGetItemSectionMapFileMapOutputWithContext(context.Context) GetItemSectionMapFileMapOutput
}

type GetItemSectionMapFileMapArgs struct {
	// The content of the file.
	Content pulumi.StringInput `pulumi:"content"`
	// The content of the file in base64 encoding. (Use this for binary files.)
	ContentBase64 pulumi.StringInput `pulumi:"contentBase64"`
	// The UUID of the file.
	Id pulumi.StringInput `pulumi:"id"`
}

func (GetItemSectionMapFileMapArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetItemSectionMapFileMap)(nil)).Elem()
}

func (i GetItemSectionMapFileMapArgs) ToGetItemSectionMapFileMapOutput() GetItemSectionMapFileMapOutput {
	return i.ToGetItemSectionMapFileMapOutputWithContext(context.Background())
}

func (i GetItemSectionMapFileMapArgs) ToGetItemSectionMapFileMapOutputWithContext(ctx context.Context) GetItemSectionMapFileMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetItemSectionMapFileMapOutput)
}

// GetItemSectionMapFileMapMapInput is an input type that accepts GetItemSectionMapFileMapMap and GetItemSectionMapFileMapMapOutput values.
// You can construct a concrete instance of `GetItemSectionMapFileMapMapInput` via:
//
//	GetItemSectionMapFileMapMap{ "key": GetItemSectionMapFileMapArgs{...} }
type GetItemSectionMapFileMapMapInput interface {
	pulumi.Input

	ToGetItemSectionMapFileMapMapOutput() GetItemSectionMapFileMapMapOutput
	ToGetItemSectionMapFileMapMapOutputWithContext(context.Context) GetItemSectionMapFileMapMapOutput
}

type GetItemSectionMapFileMapMap map[string]GetItemSectionMapFileMapInput

func (GetItemSectionMapFileMapMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]GetItemSectionMapFileMap)(nil)).Elem()
}

func (i GetItemSectionMapFileMapMap) ToGetItemSectionMapFileMapMapOutput() GetItemSectionMapFileMapMapOutput {
	return i.ToGetItemSectionMapFileMapMapOutputWithContext(context.Background())
}

func (i GetItemSectionMapFileMapMap) ToGetItemSectionMapFileMapMapOutputWithContext(ctx context.Context) GetItemSectionMapFileMapMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetItemSectionMapFileMapMapOutput)
}

type GetItemSectionMapFileMapOutput struct{ *pulumi.OutputState }

func (GetItemSectionMapFileMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetItemSectionMapFileMap)(nil)).Elem()
}

func (o GetItemSectionMapFileMapOutput) ToGetItemSectionMapFileMapOutput() GetItemSectionMapFileMapOutput {
	return o
}

func (o GetItemSectionMapFileMapOutput) ToGetItemSectionMapFileMapOutputWithContext(ctx context.Context) GetItemSectionMapFileMapOutput {
	return o
}

// The content of the file.
func (o GetItemSectionMapFileMapOutput) Content() pulumi.StringOutput {
	return o.ApplyT(func(v GetItemSectionMapFileMap) string { return v.Content }).(pulumi.StringOutput)
}

// The content of the file in base64 encoding. (Use this for binary files.)
func (o GetItemSectionMapFileMapOutput) ContentBase64() pulumi.StringOutput {
	return o.ApplyT(func(v GetItemSectionMapFileMap) string { return v.ContentBase64 }).(pulumi.StringOutput)
}

// The UUID of the file.
func (o GetItemSectionMapFileMapOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetItemSectionMapFileMap) string { return v.Id }).(pulumi.StringOutput)
}

type GetItemSectionMapFileMapMapOutput struct{ *pulumi.OutputState }

func (GetItemSectionMapFileMapMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]GetItemSectionMapFileMap)(nil)).Elem()
}

func (o GetItemSectionMapFileMapMapOutput) ToGetItemSectionMapFileMapMapOutput() GetItemSectionMapFileMapMapOutput {
	return o
}

func (o GetItemSectionMapFileMapMapOutput) ToGetItemSectionMapFileMapMapOutputWithContext(ctx context.Context) GetItemSectionMapFileMapMapOutput {
	return o
}

func (o GetItemSectionMapFileMapMapOutput) MapIndex(k pulumi.StringInput) GetItemSectionMapFileMapOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) GetItemSectionMapFileMap {
		return vs[0].(map[string]GetItemSectionMapFileMap)[vs[1].(string)]
	}).(GetItemSectionMapFileMapOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ItemPasswordRecipeInput)(nil)).Elem(), ItemPasswordRecipeArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ItemPasswordRecipePtrInput)(nil)).Elem(), ItemPasswordRecipeArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ItemSectionInput)(nil)).Elem(), ItemSectionArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ItemSectionArrayInput)(nil)).Elem(), ItemSectionArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ItemSectionFieldInput)(nil)).Elem(), ItemSectionFieldArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ItemSectionFieldArrayInput)(nil)).Elem(), ItemSectionFieldArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ItemSectionFieldPasswordRecipeInput)(nil)).Elem(), ItemSectionFieldPasswordRecipeArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ItemSectionFieldPasswordRecipePtrInput)(nil)).Elem(), ItemSectionFieldPasswordRecipeArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ItemSectionMapInput)(nil)).Elem(), ItemSectionMapArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ItemSectionMapMapInput)(nil)).Elem(), ItemSectionMapMap{})
	pulumi.RegisterInputType(reflect.TypeOf((*ItemSectionMapFieldMapInput)(nil)).Elem(), ItemSectionMapFieldMapArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ItemSectionMapFieldMapMapInput)(nil)).Elem(), ItemSectionMapFieldMapMap{})
	pulumi.RegisterInputType(reflect.TypeOf((*ItemSectionMapFieldMapPasswordRecipeInput)(nil)).Elem(), ItemSectionMapFieldMapPasswordRecipeArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ItemSectionMapFieldMapPasswordRecipePtrInput)(nil)).Elem(), ItemSectionMapFieldMapPasswordRecipeArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetEnvironmentMetadataInput)(nil)).Elem(), GetEnvironmentMetadataArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetEnvironmentMetadataArrayInput)(nil)).Elem(), GetEnvironmentMetadataArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetItemFileInput)(nil)).Elem(), GetItemFileArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetItemFileArrayInput)(nil)).Elem(), GetItemFileArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetItemSectionInput)(nil)).Elem(), GetItemSectionArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetItemSectionArrayInput)(nil)).Elem(), GetItemSectionArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetItemSectionFieldInput)(nil)).Elem(), GetItemSectionFieldArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetItemSectionFieldArrayInput)(nil)).Elem(), GetItemSectionFieldArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetItemSectionFileInput)(nil)).Elem(), GetItemSectionFileArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetItemSectionFileArrayInput)(nil)).Elem(), GetItemSectionFileArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetItemSectionMapInput)(nil)).Elem(), GetItemSectionMapArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetItemSectionMapMapInput)(nil)).Elem(), GetItemSectionMapMap{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetItemSectionMapFieldMapInput)(nil)).Elem(), GetItemSectionMapFieldMapArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetItemSectionMapFieldMapMapInput)(nil)).Elem(), GetItemSectionMapFieldMapMap{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetItemSectionMapFileMapInput)(nil)).Elem(), GetItemSectionMapFileMapArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetItemSectionMapFileMapMapInput)(nil)).Elem(), GetItemSectionMapFileMapMap{})
	pulumi.RegisterOutputType(ItemPasswordRecipeOutput{})
	pulumi.RegisterOutputType(ItemPasswordRecipePtrOutput{})
	pulumi.RegisterOutputType(ItemSectionOutput{})
	pulumi.RegisterOutputType(ItemSectionArrayOutput{})
	pulumi.RegisterOutputType(ItemSectionFieldOutput{})
	pulumi.RegisterOutputType(ItemSectionFieldArrayOutput{})
	pulumi.RegisterOutputType(ItemSectionFieldPasswordRecipeOutput{})
	pulumi.RegisterOutputType(ItemSectionFieldPasswordRecipePtrOutput{})
	pulumi.RegisterOutputType(ItemSectionMapOutput{})
	pulumi.RegisterOutputType(ItemSectionMapMapOutput{})
	pulumi.RegisterOutputType(ItemSectionMapFieldMapOutput{})
	pulumi.RegisterOutputType(ItemSectionMapFieldMapMapOutput{})
	pulumi.RegisterOutputType(ItemSectionMapFieldMapPasswordRecipeOutput{})
	pulumi.RegisterOutputType(ItemSectionMapFieldMapPasswordRecipePtrOutput{})
	pulumi.RegisterOutputType(GetEnvironmentMetadataOutput{})
	pulumi.RegisterOutputType(GetEnvironmentMetadataArrayOutput{})
	pulumi.RegisterOutputType(GetItemFileOutput{})
	pulumi.RegisterOutputType(GetItemFileArrayOutput{})
	pulumi.RegisterOutputType(GetItemSectionOutput{})
	pulumi.RegisterOutputType(GetItemSectionArrayOutput{})
	pulumi.RegisterOutputType(GetItemSectionFieldOutput{})
	pulumi.RegisterOutputType(GetItemSectionFieldArrayOutput{})
	pulumi.RegisterOutputType(GetItemSectionFileOutput{})
	pulumi.RegisterOutputType(GetItemSectionFileArrayOutput{})
	pulumi.RegisterOutputType(GetItemSectionMapOutput{})
	pulumi.RegisterOutputType(GetItemSectionMapMapOutput{})
	pulumi.RegisterOutputType(GetItemSectionMapFieldMapOutput{})
	pulumi.RegisterOutputType(GetItemSectionMapFieldMapMapOutput{})
	pulumi.RegisterOutputType(GetItemSectionMapFileMapOutput{})
	pulumi.RegisterOutputType(GetItemSectionMapFileMapMapOutput{})
}
