// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Onepassword.Inputs
{

    public sealed class GetEnvironmentMetadataInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether the value is hidden by default in the 1Password app.
        /// </summary>
        [Input("masked", required: true)]
        public Input<bool> Masked { get; set; } = null!;

        /// <summary>
        /// The environment variable name.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("value", required: true)]
        private Input<string>? _value;

        /// <summary>
        /// The environment variable value.
        /// </summary>
        public Input<string>? Value
        {
            get => _value;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _value = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        public GetEnvironmentMetadataInputArgs()
        {
        }
        public static new GetEnvironmentMetadataInputArgs Empty => new GetEnvironmentMetadataInputArgs();
    }
}
