// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Onepassword.Inputs
{

    public sealed class GetEnvironmentMetadataArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Whether the value is hidden by default in the 1Password app.
        /// </summary>
        [Input("masked", required: true)]
        public bool Masked { get; set; }

        /// <summary>
        /// The environment variable name.
        /// </summary>
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        [Input("value", required: true)]
        private string? _value;

        /// <summary>
        /// The environment variable value.
        /// </summary>
        public string? Value
        {
            get => _value;
            set => _value = value;
        }

        public GetEnvironmentMetadataArgs()
        {
        }
        public static new GetEnvironmentMetadataArgs Empty => new GetEnvironmentMetadataArgs();
    }
}
