// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Onepassword.Inputs
{

    public sealed class GetItemSectionMapArgs : global::Pulumi.InvokeArgs
    {
        [Input("fieldMap", required: true)]
        private Dictionary<string, Inputs.GetItemSectionMapFieldMapArgs>? _fieldMap;

        /// <summary>
        /// A map of custom fields in the section, keyed by field label.
        /// </summary>
        public Dictionary<string, Inputs.GetItemSectionMapFieldMapArgs> FieldMap
        {
            get => _fieldMap ?? (_fieldMap = new Dictionary<string, Inputs.GetItemSectionMapFieldMapArgs>());
            set => _fieldMap = value;
        }

        [Input("fileMap", required: true)]
        private Dictionary<string, Inputs.GetItemSectionMapFileMapArgs>? _fileMap;

        /// <summary>
        /// A map of files attached to the section, keyed by file label.
        /// </summary>
        public Dictionary<string, Inputs.GetItemSectionMapFileMapArgs> FileMap
        {
            get => _fileMap ?? (_fileMap = new Dictionary<string, Inputs.GetItemSectionMapFileMapArgs>());
            set => _fileMap = value;
        }

        /// <summary>
        /// A unique identifier for the section.
        /// </summary>
        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        public GetItemSectionMapArgs()
        {
        }
        public static new GetItemSectionMapArgs Empty => new GetItemSectionMapArgs();
    }
}
