// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Onepassword.Inputs
{

    public sealed class GetItemSectionMapInputArgs : global::Pulumi.ResourceArgs
    {
        [Input("fieldMap", required: true)]
        private InputMap<Inputs.GetItemSectionMapFieldMapInputArgs>? _fieldMap;

        /// <summary>
        /// A map of custom fields in the section, keyed by field label.
        /// </summary>
        public InputMap<Inputs.GetItemSectionMapFieldMapInputArgs> FieldMap
        {
            get => _fieldMap ?? (_fieldMap = new InputMap<Inputs.GetItemSectionMapFieldMapInputArgs>());
            set => _fieldMap = value;
        }

        [Input("fileMap", required: true)]
        private InputMap<Inputs.GetItemSectionMapFileMapInputArgs>? _fileMap;

        /// <summary>
        /// A map of files attached to the section, keyed by file label.
        /// </summary>
        public InputMap<Inputs.GetItemSectionMapFileMapInputArgs> FileMap
        {
            get => _fileMap ?? (_fileMap = new InputMap<Inputs.GetItemSectionMapFileMapInputArgs>());
            set => _fileMap = value;
        }

        /// <summary>
        /// A unique identifier for the section.
        /// </summary>
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        public GetItemSectionMapInputArgs()
        {
        }
        public static new GetItemSectionMapInputArgs Empty => new GetItemSectionMapInputArgs();
    }
}
