// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Onepassword.Inputs
{

    public sealed class ItemSectionMapArgs : global::Pulumi.ResourceArgs
    {
        [Input("fieldMap")]
        private InputMap<Inputs.ItemSectionMapFieldMapArgs>? _fieldMap;

        /// <summary>
        /// A map of custom fields in the section, keyed by field label.
        /// </summary>
        public InputMap<Inputs.ItemSectionMapFieldMapArgs> FieldMap
        {
            get => _fieldMap ?? (_fieldMap = new InputMap<Inputs.ItemSectionMapFieldMapArgs>());
            set => _fieldMap = value;
        }

        /// <summary>
        /// A unique identifier for the section.
        /// </summary>
        [Input("id")]
        public Input<string>? Id { get; set; }

        public ItemSectionMapArgs()
        {
        }
        public static new ItemSectionMapArgs Empty => new ItemSectionMapArgs();
    }
}
