// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Use this data source to read environment variables from a [1Password Environment](https://developer.1password.com/docs/environments/). 1Password Environments allow you to organize and manage project secrets as environment variables. This data source is only supported when using **service account** or **desktop app** authentication; it is not available with 1Password Connect.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as onepassword from "@1password/pulumi-onepassword";
 *
 * // Read environment variables from a 1Password Environment.
 * // Requires service account or desktop app authentication (not 1Password Connect).
 * const example = onepassword.getEnvironment({
 *     environmentId: "your-environment-id",
 * });
 * export const envVariables = example.then(example => example.variables);
 * ```
 */
export function getEnvironment(args: GetEnvironmentArgs, opts?: pulumi.InvokeOptions): Promise<GetEnvironmentResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("onepassword:index/getEnvironment:getEnvironment", {
        "environmentId": args.environmentId,
        "metadatas": args.metadatas,
    }, opts);
}

/**
 * A collection of arguments for invoking getEnvironment.
 */
export interface GetEnvironmentArgs {
    /**
     * The unique identifier of the 1Password Environment. You can find this in the 1Password desktop app under Developer > View Environments > Manage environment > Copy environment ID.
     */
    environmentId: string;
    /**
     * Metadata for each environment variable (name, value, and masked flag). Use this when you need the full structure; use `variables` for a simple name-to-value map.
     */
    metadatas?: inputs.GetEnvironmentMetadata[];
}

/**
 * A collection of values returned by getEnvironment.
 */
export interface GetEnvironmentResult {
    /**
     * The unique identifier of the 1Password Environment. You can find this in the 1Password desktop app under Developer > View Environments > Manage environment > Copy environment ID.
     */
    readonly environmentId: string;
    /**
     * The Terraform resource identifier for this environment in the format `environments/<environment_id>`.
     */
    readonly id: string;
    /**
     * Metadata for each environment variable (name, value, and masked flag). Use this when you need the full structure; use `variables` for a simple name-to-value map.
     */
    readonly metadatas?: outputs.GetEnvironmentMetadata[];
    /**
     * A map of environment variable names to their values. Use this for passing secrets into Terraform resources or for use in `environment` blocks.
     */
    readonly variables: {[key: string]: string};
}
/**
 * Use this data source to read environment variables from a [1Password Environment](https://developer.1password.com/docs/environments/). 1Password Environments allow you to organize and manage project secrets as environment variables. This data source is only supported when using **service account** or **desktop app** authentication; it is not available with 1Password Connect.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as onepassword from "@1password/pulumi-onepassword";
 *
 * // Read environment variables from a 1Password Environment.
 * // Requires service account or desktop app authentication (not 1Password Connect).
 * const example = onepassword.getEnvironment({
 *     environmentId: "your-environment-id",
 * });
 * export const envVariables = example.then(example => example.variables);
 * ```
 */
export function getEnvironmentOutput(args: GetEnvironmentOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetEnvironmentResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("onepassword:index/getEnvironment:getEnvironment", {
        "environmentId": args.environmentId,
        "metadatas": args.metadatas,
    }, opts);
}

/**
 * A collection of arguments for invoking getEnvironment.
 */
export interface GetEnvironmentOutputArgs {
    /**
     * The unique identifier of the 1Password Environment. You can find this in the 1Password desktop app under Developer > View Environments > Manage environment > Copy environment ID.
     */
    environmentId: pulumi.Input<string>;
    /**
     * Metadata for each environment variable (name, value, and masked flag). Use this when you need the full structure; use `variables` for a simple name-to-value map.
     */
    metadatas?: pulumi.Input<pulumi.Input<inputs.GetEnvironmentMetadataArgs>[]>;
}
