// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Use this to get details of an item by its vault uuid and either the title or the uuid of the item.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as onepassword from "@1password/pulumi-onepassword";
 *
 * const example = onepassword.getItem({
 *     vault: "your-vault-id",
 *     title: "your-item-title",
 * });
 * ```
 */
export function getItem(args: GetItemArgs, opts?: pulumi.InvokeOptions): Promise<GetItemResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("onepassword:index/getItem:getItem", {
        "files": args.files,
        "noteValue": args.noteValue,
        "sectionMap": args.sectionMap,
        "sections": args.sections,
        "title": args.title,
        "uuid": args.uuid,
        "vault": args.vault,
    }, opts);
}

/**
 * A collection of arguments for invoking getItem.
 */
export interface GetItemArgs {
    /**
     * A list of files attached to the document item.
     */
    files?: inputs.GetItemFile[];
    /**
     * Secure Note value.
     */
    noteValue?: string;
    /**
     * A map of custom sections in an item, keyed by section label. This allows direct lookup of sections and their fields by label. Cannot be used together with `section`. Use either `section` (list) or `sectionMap` (map), but not both.
     */
    sectionMap?: {[key: string]: inputs.GetItemSectionMap};
    /**
     * A list of custom sections in an item. Cannot be used together with `sectionMap`. Use either `section` (list) or `sectionMap` (map), but not both.
     */
    sections?: inputs.GetItemSection[];
    /**
     * The title of the item to retrieve. This field will be populated with the title of the item if the item it looked up by its UUID.
     */
    title?: string;
    /**
     * The UUID of the item to retrieve. This field will be populated with the UUID of the item if the item it looked up by its title.
     */
    uuid?: string;
    /**
     * The UUID of the vault the item is in.
     */
    vault: string;
}

/**
 * A collection of values returned by getItem.
 */
export interface GetItemResult {
    /**
     * The category of the item. One of ["login" "password" "database" "secure*note" "document" "ssh*key" "apiCredential"]
     */
    readonly category: string;
    /**
     * (Only applies to the API credential category) API credential for this item.
     */
    readonly credential: string;
    /**
     * (Only applies to the database category) The name of the database.
     */
    readonly database: string;
    /**
     * (Only applies to the API credential category) The filename associated with the API credential.
     */
    readonly filename: string;
    /**
     * A list of files attached to the document item.
     */
    readonly files?: outputs.GetItemFile[];
    /**
     * (Only applies to the database category) The address where the database can be found
     */
    readonly hostname: string;
    /**
     * The Terraform resource identifier for this item in the format `vaults/<vault_id>/items/<item_id>`.
     */
    readonly id: string;
    /**
     * Secure Note value.
     */
    readonly noteValue: string;
    /**
     * Password for this item.
     */
    readonly password: string;
    /**
     * (Only applies to the database category) The port the database is listening on.
     */
    readonly port: string;
    /**
     * SSH Private Key in PKCS#8 for this item.
     */
    readonly privateKey: string;
    /**
     * SSH Private key in OpenSSH format.
     */
    readonly privateKeyOpenssh: string;
    /**
     * SSH Public Key for this item.
     */
    readonly publicKey: string;
    /**
     * A map of custom sections in an item, keyed by section label. This allows direct lookup of sections and their fields by label. Cannot be used together with `section`. Use either `section` (list) or `sectionMap` (map), but not both.
     */
    readonly sectionMap: {[key: string]: outputs.GetItemSectionMap};
    /**
     * A list of custom sections in an item. Cannot be used together with `sectionMap`. Use either `section` (list) or `sectionMap` (map), but not both.
     */
    readonly sections?: outputs.GetItemSection[];
    /**
     * An array of strings of the tags assigned to the item.
     */
    readonly tags: string[];
    /**
     * The title of the item to retrieve. This field will be populated with the title of the item if the item it looked up by its UUID.
     */
    readonly title: string;
    /**
     * (Only applies to database and API credential categories) The type of database or API Credential.
     */
    readonly type: string;
    /**
     * The primary URL for the item.
     */
    readonly url: string;
    /**
     * Username for this item.
     */
    readonly username: string;
    /**
     * The UUID of the item to retrieve. This field will be populated with the UUID of the item if the item it looked up by its title.
     */
    readonly uuid: string;
    /**
     * (Only applies to the API credential category) The timestamp from which the API credential is valid.
     */
    readonly validFrom: string;
    /**
     * The UUID of the vault the item is in.
     */
    readonly vault: string;
}
/**
 * Use this to get details of an item by its vault uuid and either the title or the uuid of the item.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as onepassword from "@1password/pulumi-onepassword";
 *
 * const example = onepassword.getItem({
 *     vault: "your-vault-id",
 *     title: "your-item-title",
 * });
 * ```
 */
export function getItemOutput(args: GetItemOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetItemResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("onepassword:index/getItem:getItem", {
        "files": args.files,
        "noteValue": args.noteValue,
        "sectionMap": args.sectionMap,
        "sections": args.sections,
        "title": args.title,
        "uuid": args.uuid,
        "vault": args.vault,
    }, opts);
}

/**
 * A collection of arguments for invoking getItem.
 */
export interface GetItemOutputArgs {
    /**
     * A list of files attached to the document item.
     */
    files?: pulumi.Input<pulumi.Input<inputs.GetItemFileArgs>[]>;
    /**
     * Secure Note value.
     */
    noteValue?: pulumi.Input<string>;
    /**
     * A map of custom sections in an item, keyed by section label. This allows direct lookup of sections and their fields by label. Cannot be used together with `section`. Use either `section` (list) or `sectionMap` (map), but not both.
     */
    sectionMap?: pulumi.Input<{[key: string]: pulumi.Input<inputs.GetItemSectionMapArgs>}>;
    /**
     * A list of custom sections in an item. Cannot be used together with `sectionMap`. Use either `section` (list) or `sectionMap` (map), but not both.
     */
    sections?: pulumi.Input<pulumi.Input<inputs.GetItemSectionArgs>[]>;
    /**
     * The title of the item to retrieve. This field will be populated with the title of the item if the item it looked up by its UUID.
     */
    title?: pulumi.Input<string>;
    /**
     * The UUID of the item to retrieve. This field will be populated with the UUID of the item if the item it looked up by its title.
     */
    uuid?: pulumi.Input<string>;
    /**
     * The UUID of the vault the item is in.
     */
    vault: pulumi.Input<string>;
}
