// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * A 1Password Item.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as onepassword from "@1password/pulumi-onepassword";
 *
 * // Example using section_map (map-based sections for direct field access)
 * const exampleWithMap = new onepassword.Item("example_with_map", {
 *     vault: "your-vault-id",
 *     title: "Example Item with Section Map",
 *     category: "login",
 *     sectionMap: {
 *         credentials: {
 *             fieldMap: {
 *                 api_key: {
 *                     type: "CONCEALED",
 *                     value: "my-secret-api-key",
 *                 },
 *                 api_endpoint: {
 *                     type: "URL",
 *                     value: "https://api.example.com",
 *                 },
 *             },
 *         },
 *         metadata: {
 *             fieldMap: {
 *                 environment: {
 *                     type: "STRING",
 *                     value: "production",
 *                 },
 *                 created_by: {
 *                     type: "STRING",
 *                     value: "terraform",
 *                 },
 *             },
 *         },
 *     },
 * });
 * // Example using section (list-based sections)
 * const exampleWithList = new onepassword.Item("example_with_list", {
 *     vault: "your-vault-id",
 *     title: "Example Item with Section List",
 *     category: "login",
 *     passwordRecipe: {
 *         length: 40,
 *         symbols: false,
 *     },
 *     sections: [{
 *         label: "Example section",
 *         fields: [{
 *             label: "Example field",
 *             type: "DATE",
 *             value: "2024-01-31",
 *         }],
 *     }],
 * });
 * ```
 *
 * ## Import
 *
 * The `pulumi import` command can be used, for example:
 *
 * ```sh
 * # import an existing 1Password item
 * terraform import onepassword_item.myitem vaults/<vault uuid>/items/<item uuid>
 * ```
 */
export class Item extends pulumi.CustomResource {
    /**
     * Get an existing Item resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ItemState, opts?: pulumi.CustomResourceOptions): Item {
        return new Item(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'onepassword:index/item:Item';

    /**
     * Returns true if the given object is an instance of Item.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Item {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Item.__pulumiType;
    }

    /**
     * The category of the item. One of ["login" "password" "database" "secureNote"]
     */
    declare public readonly category: pulumi.Output<string>;
    /**
     * (Only applies to the database category) The name of the database.
     */
    declare public readonly database: pulumi.Output<string | undefined>;
    /**
     * (Only applies to the database category) The address where the database can be found
     */
    declare public readonly hostname: pulumi.Output<string | undefined>;
    /**
     * Secure Note value.
     */
    declare public readonly noteValue: pulumi.Output<string | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * A write-only secure note value for this item. This value is not stored in the state and is intended for use with ephemeral values. **Note**: Write-only arguments require Terraform 1.11 or later.
     */
    declare public readonly noteValueWo: pulumi.Output<string | undefined>;
    /**
     * An integer that must be incremented to trigger an update to the 'note_value_wo' field.
     */
    declare public readonly noteValueWoVersion: pulumi.Output<number | undefined>;
    /**
     * Password for this item.
     */
    declare public readonly password: pulumi.Output<string>;
    /**
     * The recipe used to generate a new value for a password.
     */
    declare public readonly passwordRecipe: pulumi.Output<outputs.ItemPasswordRecipe | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * A write-only password for this item. This value is not stored in the state and is intended for use with ephemeral values. **Note**: Write-only arguments require Terraform 1.11 or later.
     */
    declare public readonly passwordWo: pulumi.Output<string | undefined>;
    /**
     * An integer that must be incremented to trigger an update to the 'password_wo' field.
     */
    declare public readonly passwordWoVersion: pulumi.Output<number | undefined>;
    /**
     * (Only applies to the database category) The port the database is listening on.
     */
    declare public readonly port: pulumi.Output<string | undefined>;
    /**
     * A map of custom sections in an item, keyed by section label. This allows direct lookup of sections and their fields by label. Cannot be used together with `section`. Use either `section` (list) or `sectionMap` (map), but not both.
     */
    declare public readonly sectionMap: pulumi.Output<{[key: string]: outputs.ItemSectionMap} | undefined>;
    /**
     * A list of custom sections in an item. Cannot be used together with `sectionMap`. Use either `section` (list) or `sectionMap` (map), but not both.
     */
    declare public readonly sections: pulumi.Output<outputs.ItemSection[] | undefined>;
    /**
     * An array of strings of the tags assigned to the item.
     */
    declare public readonly tags: pulumi.Output<string[] | undefined>;
    /**
     * The title of the item.
     */
    declare public readonly title: pulumi.Output<string | undefined>;
    /**
     * (Only applies to the database category) The type of database. One of ["db2" "filemaker" "msaccess" "mssql" "mysql" "oracle" "postgresql" "sqlite" "other"]
     */
    declare public readonly type: pulumi.Output<string | undefined>;
    /**
     * The primary URL for the item.
     */
    declare public readonly url: pulumi.Output<string | undefined>;
    /**
     * Username for this item.
     */
    declare public readonly username: pulumi.Output<string | undefined>;
    /**
     * The UUID of the item. Item identifiers are unique within a specific vault.
     */
    declare public /*out*/ readonly uuid: pulumi.Output<string>;
    /**
     * The UUID of the vault the item is in.
     */
    declare public readonly vault: pulumi.Output<string>;

    /**
     * Create a Item resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ItemArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ItemArgs | ItemState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ItemState | undefined;
            resourceInputs["category"] = state?.category;
            resourceInputs["database"] = state?.database;
            resourceInputs["hostname"] = state?.hostname;
            resourceInputs["noteValue"] = state?.noteValue;
            resourceInputs["noteValueWo"] = state?.noteValueWo;
            resourceInputs["noteValueWoVersion"] = state?.noteValueWoVersion;
            resourceInputs["password"] = state?.password;
            resourceInputs["passwordRecipe"] = state?.passwordRecipe;
            resourceInputs["passwordWo"] = state?.passwordWo;
            resourceInputs["passwordWoVersion"] = state?.passwordWoVersion;
            resourceInputs["port"] = state?.port;
            resourceInputs["sectionMap"] = state?.sectionMap;
            resourceInputs["sections"] = state?.sections;
            resourceInputs["tags"] = state?.tags;
            resourceInputs["title"] = state?.title;
            resourceInputs["type"] = state?.type;
            resourceInputs["url"] = state?.url;
            resourceInputs["username"] = state?.username;
            resourceInputs["uuid"] = state?.uuid;
            resourceInputs["vault"] = state?.vault;
        } else {
            const args = argsOrState as ItemArgs | undefined;
            if (args?.vault === undefined && !opts.urn) {
                throw new Error("Missing required property 'vault'");
            }
            resourceInputs["category"] = args?.category;
            resourceInputs["database"] = args?.database;
            resourceInputs["hostname"] = args?.hostname;
            resourceInputs["noteValue"] = args?.noteValue ? pulumi.secret(args.noteValue) : undefined;
            resourceInputs["noteValueWo"] = args?.noteValueWo ? pulumi.secret(args.noteValueWo) : undefined;
            resourceInputs["noteValueWoVersion"] = args?.noteValueWoVersion;
            resourceInputs["password"] = args?.password ? pulumi.secret(args.password) : undefined;
            resourceInputs["passwordRecipe"] = args?.passwordRecipe;
            resourceInputs["passwordWo"] = args?.passwordWo ? pulumi.secret(args.passwordWo) : undefined;
            resourceInputs["passwordWoVersion"] = args?.passwordWoVersion;
            resourceInputs["port"] = args?.port;
            resourceInputs["sectionMap"] = args?.sectionMap;
            resourceInputs["sections"] = args?.sections;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["title"] = args?.title;
            resourceInputs["type"] = args?.type;
            resourceInputs["url"] = args?.url;
            resourceInputs["username"] = args?.username;
            resourceInputs["vault"] = args?.vault;
            resourceInputs["uuid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["noteValue", "noteValueWo", "password", "passwordWo"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Item.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Item resources.
 */
export interface ItemState {
    /**
     * The category of the item. One of ["login" "password" "database" "secureNote"]
     */
    category?: pulumi.Input<string>;
    /**
     * (Only applies to the database category) The name of the database.
     */
    database?: pulumi.Input<string>;
    /**
     * (Only applies to the database category) The address where the database can be found
     */
    hostname?: pulumi.Input<string>;
    /**
     * Secure Note value.
     */
    noteValue?: pulumi.Input<string>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * A write-only secure note value for this item. This value is not stored in the state and is intended for use with ephemeral values. **Note**: Write-only arguments require Terraform 1.11 or later.
     */
    noteValueWo?: pulumi.Input<string>;
    /**
     * An integer that must be incremented to trigger an update to the 'note_value_wo' field.
     */
    noteValueWoVersion?: pulumi.Input<number>;
    /**
     * Password for this item.
     */
    password?: pulumi.Input<string>;
    /**
     * The recipe used to generate a new value for a password.
     */
    passwordRecipe?: pulumi.Input<inputs.ItemPasswordRecipe>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * A write-only password for this item. This value is not stored in the state and is intended for use with ephemeral values. **Note**: Write-only arguments require Terraform 1.11 or later.
     */
    passwordWo?: pulumi.Input<string>;
    /**
     * An integer that must be incremented to trigger an update to the 'password_wo' field.
     */
    passwordWoVersion?: pulumi.Input<number>;
    /**
     * (Only applies to the database category) The port the database is listening on.
     */
    port?: pulumi.Input<string>;
    /**
     * A map of custom sections in an item, keyed by section label. This allows direct lookup of sections and their fields by label. Cannot be used together with `section`. Use either `section` (list) or `sectionMap` (map), but not both.
     */
    sectionMap?: pulumi.Input<{[key: string]: pulumi.Input<inputs.ItemSectionMap>}>;
    /**
     * A list of custom sections in an item. Cannot be used together with `sectionMap`. Use either `section` (list) or `sectionMap` (map), but not both.
     */
    sections?: pulumi.Input<pulumi.Input<inputs.ItemSection>[]>;
    /**
     * An array of strings of the tags assigned to the item.
     */
    tags?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The title of the item.
     */
    title?: pulumi.Input<string>;
    /**
     * (Only applies to the database category) The type of database. One of ["db2" "filemaker" "msaccess" "mssql" "mysql" "oracle" "postgresql" "sqlite" "other"]
     */
    type?: pulumi.Input<string>;
    /**
     * The primary URL for the item.
     */
    url?: pulumi.Input<string>;
    /**
     * Username for this item.
     */
    username?: pulumi.Input<string>;
    /**
     * The UUID of the item. Item identifiers are unique within a specific vault.
     */
    uuid?: pulumi.Input<string>;
    /**
     * The UUID of the vault the item is in.
     */
    vault?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Item resource.
 */
export interface ItemArgs {
    /**
     * The category of the item. One of ["login" "password" "database" "secureNote"]
     */
    category?: pulumi.Input<string>;
    /**
     * (Only applies to the database category) The name of the database.
     */
    database?: pulumi.Input<string>;
    /**
     * (Only applies to the database category) The address where the database can be found
     */
    hostname?: pulumi.Input<string>;
    /**
     * Secure Note value.
     */
    noteValue?: pulumi.Input<string>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * A write-only secure note value for this item. This value is not stored in the state and is intended for use with ephemeral values. **Note**: Write-only arguments require Terraform 1.11 or later.
     */
    noteValueWo?: pulumi.Input<string>;
    /**
     * An integer that must be incremented to trigger an update to the 'note_value_wo' field.
     */
    noteValueWoVersion?: pulumi.Input<number>;
    /**
     * Password for this item.
     */
    password?: pulumi.Input<string>;
    /**
     * The recipe used to generate a new value for a password.
     */
    passwordRecipe?: pulumi.Input<inputs.ItemPasswordRecipe>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * A write-only password for this item. This value is not stored in the state and is intended for use with ephemeral values. **Note**: Write-only arguments require Terraform 1.11 or later.
     */
    passwordWo?: pulumi.Input<string>;
    /**
     * An integer that must be incremented to trigger an update to the 'password_wo' field.
     */
    passwordWoVersion?: pulumi.Input<number>;
    /**
     * (Only applies to the database category) The port the database is listening on.
     */
    port?: pulumi.Input<string>;
    /**
     * A map of custom sections in an item, keyed by section label. This allows direct lookup of sections and their fields by label. Cannot be used together with `section`. Use either `section` (list) or `sectionMap` (map), but not both.
     */
    sectionMap?: pulumi.Input<{[key: string]: pulumi.Input<inputs.ItemSectionMap>}>;
    /**
     * A list of custom sections in an item. Cannot be used together with `sectionMap`. Use either `section` (list) or `sectionMap` (map), but not both.
     */
    sections?: pulumi.Input<pulumi.Input<inputs.ItemSection>[]>;
    /**
     * An array of strings of the tags assigned to the item.
     */
    tags?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The title of the item.
     */
    title?: pulumi.Input<string>;
    /**
     * (Only applies to the database category) The type of database. One of ["db2" "filemaker" "msaccess" "mssql" "mysql" "oracle" "postgresql" "sqlite" "other"]
     */
    type?: pulumi.Input<string>;
    /**
     * The primary URL for the item.
     */
    url?: pulumi.Input<string>;
    /**
     * Username for this item.
     */
    username?: pulumi.Input<string>;
    /**
     * The UUID of the vault the item is in.
     */
    vault: pulumi.Input<string>;
}
