// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * The provider type for the onepassword package. By default, resources use package-wide configuration
 * settings, however an explicit `Provider` instance may be created and passed during resource
 * construction to achieve fine-grained programmatic control over provider settings. See the
 * [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
 */
export class Provider extends pulumi.ProviderResource {
    /** @internal */
    public static readonly __pulumiType = 'onepassword';

    /**
     * Returns true if the given object is an instance of Provider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Provider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === "pulumi:providers:" + Provider.__pulumiType;
    }

    /**
     * A valid account name or ID to use desktop app authentication. Can also be sourced from `OP_ACCOUNT` environment variable.
     */
    declare public readonly account: pulumi.Output<string | undefined>;
    /**
     * A valid token for your 1Password Connect server. Can also be sourced from `OP_CONNECT_TOKEN` environment variable. Provider will use 1Password Connect server if set.
     */
    declare public readonly connectToken: pulumi.Output<string | undefined>;
    /**
     * The HTTP(S) URL where your 1Password Connect server can be found. Can also be sourced `OP_CONNECT_HOST` environment variable. Provider will use 1Password Connect server if set.
     */
    declare public readonly connectUrl: pulumi.Output<string | undefined>;
    /**
     * A valid 1Password service account token. Can also be sourced from `OP_SERVICE_ACCOUNT_TOKEN` environment variable.
     */
    declare public readonly serviceAccountToken: pulumi.Output<string | undefined>;
    /**
     * A valid token for your 1Password Connect server. Can also be sourced from `OP_CONNECT_TOKEN` environment variable. Provider will use 1Password Connect server if set. Deprecated: Use `connectToken` instead.
     *
     * @deprecated The "token" field is deprecated and will be removed in a future version. Use "connectToken" instead.
     */
    declare public readonly token: pulumi.Output<string | undefined>;
    /**
     * The HTTP(S) URL where your 1Password Connect server can be found. Can also be sourced `OP_CONNECT_HOST` environment variable. Provider will use 1Password Connect server if set. Deprecated: Use `connectUrl` instead.
     *
     * @deprecated The "url" field is deprecated and will be removed in a future version. Use "connectUrl" instead.
     */
    declare public readonly url: pulumi.Output<string | undefined>;

    /**
     * Create a Provider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ProviderArgs, opts?: pulumi.ResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        {
            resourceInputs["account"] = (args?.account) ?? utilities.getEnv("OP_ACCOUNT");
            resourceInputs["connectToken"] = args?.connectToken ? pulumi.secret(args.connectToken) : undefined;
            resourceInputs["connectUrl"] = args?.connectUrl;
            resourceInputs["serviceAccountToken"] = (args?.serviceAccountToken ? pulumi.secret(args.serviceAccountToken) : undefined) ?? utilities.getEnv("OP_SERVICE_ACCOUNT_TOKEN");
            resourceInputs["token"] = (args?.token ? pulumi.secret(args.token) : undefined) ?? utilities.getEnv("OP_CONNECT_TOKEN");
            resourceInputs["url"] = (args?.url) ?? utilities.getEnv("OP_CONNECT_HOST");
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["connectToken", "serviceAccountToken", "token"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Provider.__pulumiType, name, resourceInputs, opts);
    }

    /**
     * This function returns a Terraform config object with terraform-namecased keys,to be used with the Terraform Module Provider.
     */
    terraformConfig(): pulumi.Output<Provider.TerraformConfigResult> {
        return pulumi.runtime.call("pulumi:providers:onepassword/terraformConfig", {
            "__self__": this,
        }, this);
    }
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
    /**
     * A valid account name or ID to use desktop app authentication. Can also be sourced from `OP_ACCOUNT` environment variable.
     */
    account?: pulumi.Input<string>;
    /**
     * A valid token for your 1Password Connect server. Can also be sourced from `OP_CONNECT_TOKEN` environment variable. Provider will use 1Password Connect server if set.
     */
    connectToken?: pulumi.Input<string>;
    /**
     * The HTTP(S) URL where your 1Password Connect server can be found. Can also be sourced `OP_CONNECT_HOST` environment variable. Provider will use 1Password Connect server if set.
     */
    connectUrl?: pulumi.Input<string>;
    /**
     * A valid 1Password service account token. Can also be sourced from `OP_SERVICE_ACCOUNT_TOKEN` environment variable.
     */
    serviceAccountToken?: pulumi.Input<string>;
    /**
     * A valid token for your 1Password Connect server. Can also be sourced from `OP_CONNECT_TOKEN` environment variable. Provider will use 1Password Connect server if set. Deprecated: Use `connectToken` instead.
     *
     * @deprecated The "token" field is deprecated and will be removed in a future version. Use "connectToken" instead.
     */
    token?: pulumi.Input<string>;
    /**
     * The HTTP(S) URL where your 1Password Connect server can be found. Can also be sourced `OP_CONNECT_HOST` environment variable. Provider will use 1Password Connect server if set. Deprecated: Use `connectUrl` instead.
     *
     * @deprecated The "url" field is deprecated and will be removed in a future version. Use "connectUrl" instead.
     */
    url?: pulumi.Input<string>;
}

export namespace Provider {
    /**
     * The results of the Provider.terraformConfig method.
     */
    export interface TerraformConfigResult {
        readonly result: {[key: string]: any};
    }

}
